### ISSUE TITLE
New install of 2.2.6 fails

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/commerce#1085]
### Description

Doing a new Craft install with Commerce 2.2.6 fails with the following error:

```

> applying existing project config ... Exception: Undefined index: description (/app/user/vendor/craftcms/commerce/src/services/OrderStatuses.php:247)
--
  | #0 /app/user/vendor/craftcms/commerce/src/services/OrderStatuses.php(247): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/app/user/vendo...', 247, Array)
  | #1 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(867): craft\commerce\services\OrderStatuses->handleChangedOrderStatus(Object(craft\events\ConfigEvent))
  | #2 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
  | #3 /app/user/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
  | #4 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(546): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
  | #5 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(861): craft\services\ProjectConfig->processConfigChanges('commerce.orderS...')
  | #6 [internal function]: craft\services\ProjectConfig->craft\services\{closure}(Object(craft\events\ConfigEvent))
  | #7 /app/user/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Object(Closure), Object(craft\events\ConfigEvent))
  | #8 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(546): yii\base\Component->trigger('addItem', Object(craft\events\ConfigEvent))
  | #9 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(949): craft\services\ProjectConfig->processConfigChanges('commerce.orderS...')
  | #10 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(436): craft\services\ProjectConfig->_applyChanges(Array)
  | #11 /app/user/vendor/craftcms/cms/src/migrations/Install.php(1036): craft\services\ProjectConfig->applyYamlChanges()
  | #12 /app/user/vendor/craftcms/cms/src/migrations/Install.php(73): craft\migrations\Install->insertDefaultData()
  | #13 /app/user/vendor/craftcms/cms/src/db/Migration.php(58): craft\migrations\Install->safeUp()
  | #14 /app/user/vendor/craftcms/cms/src/db/MigrationManager.php(239): craft\db\Migration->up(true)
  | #15 /app/user/vendor/craftcms/cms/src/console/controllers/InstallController.php(161): craft\db\MigrationManager->migrateUp(Object(craft\migrations\Install))
  | #16 [internal function]: craft\console\controllers\InstallController->actionCraft()
  | #17 /app/user/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
  | #18 /app/user/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
  | #19 /app/user/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
  | #20 /app/user/vendor/craftcms/cms/src/console/Controller.php(199): yii\console\Controller->runAction('', Array)
  | #21 /app/user/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('', Array)
  | #22 /app/user/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('install', Array)
  | #23 /app/user/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('install', Array)
  | #24 /app/user/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('install', Array)
  | #25 /app/user/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
  | #26 /app/user/craft(23): yii\base\Application->run()
  | #27 {main}
  | Exception 'craft\errors\MigrationException' with message 'An error occurred while executing the "craft\migrations\Install migration: Undefined index: description'
  |  
  | in /app/user/vendor/craftcms/cms/src/db/MigrationManager.php:256
  |  
  | Stack trace:
  | #0 /app/user/vendor/craftcms/cms/src/console/controllers/InstallController.php(161): craft\db\MigrationManager->migrateUp(Object(craft\migrations\Install))
  | #1 [internal function]: craft\console\controllers\InstallController->actionCraft()
  | #2 /app/user/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
  | #3 /app/user/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
  | #4 /app/user/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('', Array)
  | #5 /app/user/vendor/craftcms/cms/src/console/Controller.php(199): yii\console\Controller->runAction('', Array)
  | #6 /app/user/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('', Array)
  | #7 /app/user/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('install', Array)
  | #8 /app/user/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('install', Array)
  | #9 /app/user/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('install', Array)
  | #10 /app/user/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
  | #11 /app/user/craft(23): yii\base\Application->run()
  | #12 {main}


```

### Steps to reproduce

1. Do a new Craft install with an existing project config file and Commerce 2.2.6

### Additional info

- Craft version: 3.3.13
- PHP version: 7.3.11
- Database driver & version: PostgreSQL 10.10
- Plugins & versions: Commerce 2.2.6

**Comment by lukeholder** [comment]
Could you send your project config file to support@craftcms.com

**Comment by nfourtythree** [comment]
Hey @boboldehampsink 

This looked to be an issue with changing an order status while also updating Commerce.

Have pushed up a fix for this.

**Comment by boboldehampsink** [comment]
Thanks. Will this be released anytime soon? This prevents me from upgrading at all at the moment.

**Comment by lukeholder** [comment]
@boboldehampsink hopefully today

**Comment by lukeholder** [comment]
Just released 2.2.7

**Comment by boboldehampsink** [comment]
Thanks guys, but did you test this through? The `description` error has dissappeared, but a new one is now popping up:

```

> applying existing project config ... Exception: Undefined index: cc (/app/user/vendor/craftcms/commerce/src/services/Emails.php:221)
--


```

**Comment by nfourtythree** [comment]
Hi @boboldehampsink 

Did you happen to be making project config changes at the same time as updating?

**Comment by boboldehampsink** [comment]
Nope. Still using the same project.yaml file I already sent for this issue.
