### ISSUE TITLE
Unable to remove currency

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/commerce#127]
After adding a currency I'm unable to delete it, a generic "Unknown error has occurred" message is shown.

```
[error][yii\web\HttpException:404] yii\base\InvalidRouteException: Unable to resolve the request "commerce/paymentCurrencies/delete". in /srv/users/serverpilot/apps/craft-demo/craft/vendor/yiisoft/yii2/base/Module.php:537
Stack trace:
#0 /srv/users/serverpilot/apps/craft-demo/craft/vendor/craftcms/cms/src/web/Application.php(237): yii\base\Module->runAction('commerce/paymen...', Array)
#1 /srv/users/serverpilot/apps/craft-demo/craft/vendor/craftcms/cms/src/web/Application.php(445): craft\web\Application->runAction('commerce/paymen...', Array)
#2 /srv/users/serverpilot/apps/craft-demo/craft/vendor/craftcms/cms/src/web/Application.php(221): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#3 /srv/users/serverpilot/apps/craft-demo/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#4 /srv/users/serverpilot/apps/craft-demo/public/index.php(21): yii\base\Application->run()
```

**Comment by lukeyouell** [comment]
@lukeholder weird one, running `composer update` removed commerce?
