### ISSUE TITLE
"Session does not exist in a console request." when running resave/orders from the console

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#1279]
When running `craft resave/orders` we are running into the following error:

`error: Session does not exist in a console request.`

```
2020-02-16 20:29:25 [-][-][-][profile end][yii\db\Command::query] SELECT *
FROM `commerce_addresses`
WHERE `id`='648'
2020-02-16 20:29:25 [-][-][-][trace][yii\db\Transaction::rollBack] Roll back transaction
2020-02-16 20:29:25 [-][-][-][error][craft\errors\MissingComponentException] craft\errors\MissingComponentException: Session does not exist in a console request. in /Users/samhibberd/Sites/forwardvia/vendor/craftcms/cms/src/console/Application.php:127
Stack trace:
#0 /Users/samhibberd/Sites/forwardvia/vendor/craftcms/commerce/src/services/Customers.php(98): craft\console\Application->getSession()
#1 /Users/samhibberd/Sites/forwardvia/modules/site/src/services/Events.php(1275): craft\commerce\services\Customers->getCustomer()
#2 [internal function]: modules\site\services\Events->afterSaveAddress(Object(craft\commerce\events\AddressEvent))
#3 /Users/samhibberd/Sites/forwardvia/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(craft\commerce\events\AddressEvent))
#4 /Users/samhibberd/Sites/forwardvia/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\commerce\\...', 'afterSaveAddres...', Object(craft\commerce\events\AddressEvent))
#5 /Users/samhibberd/Sites/forwardvia/vendor/craftcms/commerce/src/services/Addresses.php(248): yii\base\Component->trigger('afterSaveAddres...', Object(craft\commerce\events\AddressEvent))
#6 /Users/samhibberd/Sites/forwardvia/vendor/craftcms/commerce/src/elements/Order.php(1473): craft\commerce\services\Addresses->saveAddress(Object(craft\commerce\models\Address), false)
#7 /Users/samhibberd/Sites/forwardvia/vendor/craftcms/cms/src/services/Elements.php(2117): craft\commerce\elements\Order->afterSave(false)
#8 /Users/samhibberd/Sites/forwardvia/vendor/craftcms/cms/src/services/Elements.php(596): craft\services\Elements->_saveElementInternal(Object(craft\commerce\elements\Order), true, false, false)
#9 /Users/samhibberd/Sites/forwardvia/vendor/craftcms/cms/src/console/controllers/ResaveController.php(308): craft\services\Elements->resaveElements(Object(craft\commerce\elements\db\OrderQuery), true, true, false)
#10 /Users/samhibberd/Sites/forwardvia/vendor/craftcms/commerce/src/Plugin.php(701): craft\console\controllers\ResaveController->saveElements(Object(craft\commerce\elements\db\OrderQuery))
#11 [internal function]: craft\commerce\Plugin->craft\commerce\{closure}()
#12 /Users/samhibberd/Sites/forwardvia/vendor/craftcms/cms/src/console/CallableAction.php(41): call_user_func_array(Object(Closure), Array)
#13 /Users/samhibberd/Sites/forwardvia/vendor/yiisoft/yii2/base/Controller.php(157): craft\console\CallableAction->runWithParams(Array)
#14 /Users/samhibberd/Sites/forwardvia/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('orders', Array)
#15 /Users/samhibberd/Sites/forwardvia/vendor/craftcms/cms/src/console/Controller.php(187): yii\console\Controller->runAction('orders', Array)
#16 /Users/samhibberd/Sites/forwardvia/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('orders', Array)
#17 /Users/samhibberd/Sites/forwardvia/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('resave/orders', Array)
#18 /Users/samhibberd/Sites/forwardvia/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('resave/orders', Array)
#19 /Users/samhibberd/Sites/forwardvia/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('resave/orders', Array)
#20 /Users/samhibberd/Sites/forwardvia/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#21 /Users/samhibberd/Sites/forwardvia/craft(22): yii\base\Application->run()
#22 {main}
```

Craft 3.4.5
Commerce 3.0.6

**Comment by lukeholder** [comment]
Hi @samhibberd - from the stack trace it looks like you have a module named forwardvia that tries to access the session when listening to the `EVENT_AFTER_SAVE_ADDRESS` event.

Since an address can be saved when re-saving the order with the CLI command, the session is not available for you to use. Not sure what the module is doing, but you might need to wrap it in something like this:

```
if(!Craft::$app->getRequest()->getIsConsoleRequest()){
```
