### ISSUE TITLE
Can't save Products

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/commerce#129]
![image](https://user-images.githubusercontent.com/764292/37401771-734249ca-2789-11e8-9b62-d472bf82c501.png)

```
Internal Server Error
Call to a member function getType() on null
```

**Comment by davidhellmann** [comment]
With the Dummy Content it works. Try it again…

**Comment by davidhellmann** [comment]
No, does not work with new Products.

**Comment by davidhellmann** [comment]
Thanks!

**Comment by davidhellmann** [comment]
@lukeholder the problem is back :/ 
I'm on the latest version / commit.

When you need any future infos, let me know.


```
Error: Call to a member function getType() on null in /Users/davidhellmann/___DEV/___Fredmansky/XXX.www/___dist/vendor/craftcms/commerce/src/elements/Variant.php:183
Stack trace:
#0 /Users/davidhellmann/___DEV/___Fredmansky/XXX.www/___dist/vendor/craftcms/cms/src/base/Element.php(1944): craft\commerce\elements\Variant->getFieldLayout()
#1 /Users/davidhellmann/___DEV/___Fredmansky/XXX.www/___dist/vendor/craftcms/cms/src/base/Element.php(1581): craft\base\Element->fieldLayoutFields()
#2 /Users/davidhellmann/___DEV/___Fredmansky/XXX.www/___dist/vendor/craftcms/commerce/src/helpers/Product.php(59): craft\base\Element->setFieldValuesFromRequest('fields')
#3 /Users/davidhellmann/___DEV/___Fredmansky/XXX.www/___dist/vendor/craftcms/commerce/src/elements/Product.php(419): craft\commerce\helpers\Product::populateProductVariantModel(Object(craft\commerce\elements\Product), Array, 'new1')
#4 /Users/davidhellmann/___DEV/___Fredmansky/XXX.www/___dist/vendor/craftcms/commerce/src/controllers/ProductsController.php(525): craft\commerce\elements\Product->setVariants(Array)
#5 /Users/davidhellmann/___DEV/___Fredmansky/XXX.www/___dist/vendor/craftcms/commerce/src/controllers/ProductsController.php(278): craft\commerce\controllers\ProductsController->_setProductFromPost()
#6 [internal function]: craft\commerce\controllers\ProductsController->actionSaveProduct()
#7 /Users/davidhellmann/___DEV/___Fredmansky/XXX.www/___dist/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /Users/davidhellmann/___DEV/___Fredmansky/XXX.www/___dist/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#9 /Users/davidhellmann/___DEV/___Fredmansky/XXX.www/___dist/vendor/craftcms/cms/src/web/Controller.php(74): yii\base\Controller->runAction('save-product', Array)
#10 /Users/davidhellmann/___DEV/___Fredmansky/XXX.www/___dist/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-product', Array)
#11 /Users/davidhellmann/___DEV/___Fredmansky/XXX.www/___dist/vendor/craftcms/cms/src/web/Application.php(237): yii\base\Module->runAction('commerce/produc...', Array)
#12 /Users/davidhellmann/___DEV/___Fredmansky/XXX.www/___dist/vendor/craftcms/cms/src/web/Application.php(445): craft\web\Application->runAction('commerce/produc...', Array)
#13 /Users/davidhellmann/___DEV/___Fredmansky/XXX.www/___dist/vendor/craftcms/cms/src/web/Application.php(221): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#14 /Users/davidhellmann/___DEV/___Fredmansky/XXX.www/___dist/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#15 /Users/davidhellmann/___DEV/___Fredmansky/XXX.www/___dist/web/index.php(41): yii\base\Application->run()
#16 /Users/davidhellmann/.composer/vendor/laravel/valet/server.php(133): require('/Users/davidhel...')
#17 {main}
```

**Comment by davidhellmann** [comment]
@brandonkelly / @lukeholder Should I open a new Issue or do you reopen this one?
