### ISSUE TITLE
Add to cart exception after Commerce 2 to 3 upgrade

### ISSUE THREAD

**Issue by timkelty** [craftcms/commerce#1326]
```
yii\\base\\UnknownPropertyException: Setting unknown property: craft\\commerce\\records\\Order::dateAuthorized in /app/vendor/composer/yiisoft/yii2/base/Component.php
```

```
{
    "message": "yii\\base\\UnknownPropertyException: Setting unknown property: craft\\commerce\\records\\Order::dateAuthorized in /app/vendor/composer/yiisoft/yii2/base/Component.php:209\nStack trace:\n#0 /app/vendor/composer/yiisoft/yii2/db/BaseActiveRecord.php(324): yii\\base\\Component->__set('dateAuthorized', NULL)\n#1 /app/vendor/composer/craftcms/cms/src/db/ActiveRecord.php(41): yii\\db\\BaseActiveRecord->__set('dateAuthorized', NULL)\n#2 /app/vendor/composer/craftcms/commerce/src/elements/Order.php(1600): craft\\db\\ActiveRecord->__set('dateAuthorized', NULL)\n#3 /app/vendor/composer/craftcms/cms/src/services/Elements.php(2123): craft\\commerce\\elements\\Order->afterSave(true)\n#4 /app/vendor/composer/craftcms/cms/src/services/Elements.php(530): craft\\services\\Elements->_saveElementInternal(Object(craft\\commerce\\elements\\Order), false, false, true)\n#5 /app/vendor/composer/craftcms/commerce/src/services/Carts.php(110): craft\\services\\Elements->saveElement(Object(craft\\commerce\\elements\\Order), false)\n#6 /app/vendor/composer/craftcms/commerce/src/controllers/CartController.php(324): craft\\commerce\\services\\Carts->getCart(true)\n#7 /app/vendor/composer/craftcms/commerce/src/controllers/CartController.php(76): craft\\commerce\\controllers\\CartController->_getCart(true)\n#8 [internal function]: craft\\commerce\\controllers\\CartController->actionUpdateCart()\n#9 /app/vendor/composer/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)\n#10 /app/vendor/composer/yiisoft/yii2/base/Controller.php(157): yii\\base\\InlineAction->runWithParams(Array)\n#11 /app/vendor/composer/craftcms/cms/src/web/Controller.php(178): yii\\base\\Controller->runAction('update-cart', Array)\n#12 /app/vendor/composer/yiisoft/yii2/base/Module.php(528): craft\\web\\Controller->runAction('update-cart', Array)\n#13 /app/vendor/composer/craftcms/cms/src/web/Application.php(291): yii\\base\\Module->runAction('commerce/cart/u...', Array)\n#14 /app/vendor/composer/craftcms/cms/src/web/Application.php(559): craft\\web\\Application->runAction('commerce/cart/u...', Array)\n#15 /app/vendor/composer/craftcms/cms/src/web/Application.php(270): craft\\web\\Application->_processActionRequest(Object(craft\\web\\Request))\n#16 /app/vendor/composer/yiisoft/yii2/base/Application.php(386): craft\\web\\Application->handleRequest(Object(craft\\web\\Request))\n#17 /app/public/index.php(5): yii\\base\\Application->run()\n#18 {main}",
    "context": {
        "trace": [],
        "memory": 11933752,
        "category": "yii\\base\\UnknownPropertyException",
        "exception": {
            "class": "yii\\base\\UnknownPropertyException",
            "message": "Setting unknown property: craft\\commerce\\records\\Order::dateAuthorized",
            "code": 0,
            "file": "/app/vendor/composer/yiisoft/yii2/base/Component.php:209"
        }
    },
    "level": 400,
    "level_name": "ERROR",
    "channel": "craftcms",
    "datetime": {
        "date": "2020-03-16 15:20:16.364139",
        "timezone_type": 3,
        "timezone": "America/Detroit"
    },
    "extra": []
}
```

**Comment by timkelty** [comment]
UPDATE: this appeared to be fixed by clearing cache (I ran both so not sure which):

```
craft cache/flush-all
craft clear-caches/all
```

If this is expected, this should should be in the migration guide, or triggered by the migration itself
