### ISSUE TITLE
Upgrade from Craft 2 > 3, "Setting unknown property" error

### ISSUE THREAD

**Issue by davist11** [craftcms/commerce#134]
I'm in the process of upgrading a Craft 2 site (that had Commerce) to Craft 3, and I received an error after installing Commerce and running the migrations. I tried to back out hoping that it would try and re-run the migrations, but now I receive an error

```
yii\base\UnknownPropertyException: Setting unknown property: craft\commerce\fields\Products::targetLocale in /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\Component->__set('targetLocale', 'en_us_lab')
#1 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\commerce\fields\Products), Array)
#2 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/fields/BaseRelationField.php(170): yii\base\BaseObject->__construct(Array)
#3 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/helpers/Component.php(80): craft\fields\BaseRelationField->__construct(Array)
#4 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/services/Fields.php(479): craft\helpers\Component::createComponent(Array, 'craft\\base\\Fiel...')
#5 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/services/Fields.php(522): craft\services\Fields->createField(Array)
#6 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1321): craft\services\Fields->getAllFields()
#7 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/elements/db/ElementQuery.php(897): craft\elements\db\ElementQuery->customFields()
#8 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#9 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Query.php(146): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#10 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Query->createCommand(Object(craft\db\Connection))
#11 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/db/Query.php(152): yii\db\Query->one(NULL)
#12 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1022): craft\db\Query->one(NULL)
#13 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/elements/User.php(337): craft\elements\db\ElementQuery->one()
#14 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/web/User.php(690): craft\elements\User::findIdentity('1')
#15 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/User.php(366): yii\web\User->renewAuthStatus()
#16 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/web/User.php(192): craft\web\User->renewAuthStatus()
#17 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/web/User.php(370): yii\web\User->getIdentity()
#18 /Users/tdavis/sites/hamilton/vendor/solspace/craft3-calendar/src/Calendar.php(153): yii\web\User->getId()
#19 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/BaseObject.php(109): Solspace\Calendar\Calendar->init()
#20 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#21 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/base/Plugin.php(87): yii\base\Module->__construct('calendar', Object(craft\web\Application), Array)
#22 [internal function]: craft\base\Plugin->__construct('calendar', Object(craft\web\Application), Array)
#23 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#24 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('Solspace\\Calend...', Array, Array)
#25 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('Solspace\\Calend...', Array, Array)
#26 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/services/Plugins.php(757): yii\BaseYii::createObject(Array, Array)
#27 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/services/Plugins.php(193): craft\services\Plugins->createPlugin('calendar', Array)
#28 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/base/ApplicationTrait.php(1135): craft\services\Plugins->loadPlugins()
#29 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(92): craft\web\Application->_init()
#30 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#31 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#32 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(82): yii\base\Application->__construct(Array)
#33 [internal function]: craft\web\Application->__construct(Array)
#34 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#35 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#36 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#37 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/bootstrap/bootstrap.php(249): yii\BaseYii::createObject(Array)
#38 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/bootstrap/web.php(42): require('/Users/tdavis/s...')
#39 /Users/tdavis/sites/hamilton/public/index.php(20): require('/Users/tdavis/s...')
#40 {main}
```

**Comment by angrybrad** [comment]
Looks like this starts with something that the Calendar plugin is doing on init()?

```
#18 /Users/tdavis/sites/hamilton/vendor/solspace/craft3-calendar/src/Calendar.php(153): yii\web\User->getId()
#19 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/BaseObject.php(109): Solspace\Calendar\Calendar->init()
#20 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#21 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/base/Plugin.php(87): yii\base\Module->__construct('calendar', Object(craft\web\Application), Array)
#22 [internal function]: craft\base\Plugin->__construct('calendar', Object(craft\web\Application), Array)
#23 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#24 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('Solspace\\Calend...', Array, Array)
#25 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('Solspace\\Calend...', Array, Array)
#26 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/services/Plugins.php(757): yii\BaseYii::createObject(Array, Array)
#27 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/services/Plugins.php(193): craft\services\Plugins->createPlugin('calendar', Array)
```

If you disable it, does Commerce update successfully?

**Comment by davist11** [comment]
After disabling Calendar and re-enabling Commerce, I now see this output:

```
yii\base\UnknownPropertyException: Setting unknown property: craft\commerce\fields\Products::targetLocale in /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\Component->__set('targetLocale', 'en_us_lab')
#1 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\commerce\fields\Products), Array)
#2 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/fields/BaseRelationField.php(170): yii\base\BaseObject->__construct(Array)
#3 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/helpers/Component.php(80): craft\fields\BaseRelationField->__construct(Array)
#4 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/services/Fields.php(479): craft\helpers\Component::createComponent(Array, 'craft\\base\\Fiel...')
#5 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/services/Fields.php(522): craft\services\Fields->createField(Array)
#6 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1321): craft\services\Fields->getAllFields()
#7 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/elements/db/ElementQuery.php(897): craft\elements\db\ElementQuery->customFields()
#8 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#9 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Query.php(146): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#10 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Query->createCommand(Object(craft\db\Connection))
#11 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/db/Query.php(152): yii\db\Query->one(NULL)
#12 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1022): craft\db\Query->one(NULL)
#13 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/elements/User.php(337): craft\elements\db\ElementQuery->one()
#14 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/web/User.php(690): craft\elements\User::findIdentity('1')
#15 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/User.php(366): yii\web\User->renewAuthStatus()
#16 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/web/User.php(192): craft\web\User->renewAuthStatus()
#17 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/web/User.php(360): yii\web\User->getIdentity()
#18 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Component.php(139): yii\web\User->getIsGuest()
#19 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2-debug/panels/UserPanel.php(81): yii\base\Component->__get('isGuest')
#20 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\debug\panels\UserPanel->init()
#21 [internal function]: yii\base\BaseObject->__construct(Array)
#22 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#23 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\debug\\Use...', Array, Array)
#24 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\debug\\Use...', Array, Array)
#25 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2-debug/Module.php(177): yii\BaseYii::createObject(Array)
#26 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2-debug/Module.php(149): yii\debug\Module->initPanels()
#27 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\debug\Module->init()
#28 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#29 [internal function]: yii\base\Module->__construct('debug', Object(craft\web\Application), Array)
#30 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#31 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('yii\\debug\\Modul...', Array, Array)
#32 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('yii\\debug\\Modul...', Array, Array)
#33 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Module.php(427): yii\BaseYii::createObject(Array, Array)
#34 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(361): yii\base\Module->getModule('debug')
#35 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(94): craft\web\Application->debugBootstrap()
#36 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#37 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#38 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(82): yii\base\Application->__construct(Array)
#39 [internal function]: craft\web\Application->__construct(Array)
#40 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#41 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#42 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#43 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/bootstrap/bootstrap.php(249): yii\BaseYii::createObject(Array)
#44 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/bootstrap/web.php(42): require('/Users/tdavis/s...')
#45 /Users/tdavis/sites/hamilton/public/index.php(20): require('/Users/tdavis/s...')
#46 {main}
```

**Comment by angrybrad** [comment]
> en_us_lab

Guessing this Craft 2 site has some custom locales setup?  Can you send a pre-update attempt database dump over to support@craftcms.com as well as your custom locale files?

**Comment by davist11** [comment]
Sent, thanks!

**Comment by lukeholder** [comment]
@davist11 

To fix the error, please follow these steps:

1) Do a `composer update` to pull in the latest commerce changes (our fix)

2) Add this method/function to the Product field class (located at: `vendor/craftcms/commerce/src/fields/Products.php`)

```
    public function __construct(array $config = [])
    {
        unset($config['targetLocale']);
        parent::__construct($config);
    }
```

3) Visit the site's CP and click 'update' to run the new Commerce migration.

4) Remove the whole method/function you added in step 2.

Done.

Let me know how you go. Thanks.

@angrybrad

**Comment by davist11** [comment]
On step 3, got another migration error:

```
Migration Error: An error occurred while executing the "craft\commerce\migrations\m171202_180000_promotions_for_all_purchasables migration.

Migration: craft\commerce\migrations\m171202_180000_promotions_for_all_purchasables
```

**Comment by lukeholder** [comment]
Can you please send me your logs again to support@craftcms.com thanks.

**Comment by lukeholder** [comment]
@davist11 did you restore your database pre-update in order to try the upgrade again?

**Comment by davist11** [comment]
Logs sent. I had not tried to roll all the way back to the pre-upgrade database, but if necessary I supposed I could try that.

**Comment by lukeholder** [comment]
@davist11 

Please 

1) Reset your database to the original before starting any updates
2) Do another `composer update` and
3) Vist the control panel to start the update process again.

I was able to update the database you supplied over support successfully. Thanks.

**Comment by davist11** [comment]
Ok, I think that worked successfully this time. Thanks!
