### ISSUE TITLE
m171202_180000_promotions_for_all_purchasables migration fails

### ISSUE THREAD

**Issue by brianjhanson** [craftcms/commerce#1392]
### Description
I'm in the process of migrating a site all the way from commerce 1 to commerce 3. When running `./craft migrate/up --plugin=commerce` the migration fails at `m171202_180000_promotions_for_all_purchasables` with the error
```
Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'productTypes.variantTitleLabel' in 'field list'
The SQL being executed was: SELECT `productTypes`.`id`, `productTypes`.`fieldLayoutId`, `productTypes`.`variantFieldLayoutId`, `productTypes`.`name`, `productTypes`.`handle`, `productTypes`.`hasDimensions`, `productTypes`.`hasVariants`, `productTypes`.`hasVariantTitleField`, `productTypes`.`variantTitleLabel`, `productTypes`.`titleFormat`, `productTypes`.`titleLabel`, `productTypes`.`skuFormat`, `productTypes`.`descriptionFormat`, `productTypes`.`uid`
FROM `craft_commerce_producttypes` `productTypes`
WHERE `id`=2
LIMIT 1 (/home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/db/Schema.php:674)
```

<details><summary><strong>Full Stack Trace</strong></summary>

```
*** applying m171202_180000_promotions_for_all_purchasables
Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'productTypes.variantTitleLabel' in 'field list'
The SQL being executed was: SELECT `productTypes`.`id`, `productTypes`.`fieldLayoutId`, `productTypes`.`variantFieldLayoutId`, `productTypes`.`name`, `productTypes`.`handle`, `productTypes`.`hasDimensions`, `productTypes`.`hasVariants`, `productTypes`.`hasVariantTitleField`, `productTypes`.`variantTitleLabel`, `productTypes`.`titleFormat`, `productTypes`.`titleLabel`, `productTypes`.`skuFormat`, `productTypes`.`descriptionFormat`, `productTypes`.`uid`
FROM `craft_commerce_producttypes` `productTypes`
WHERE `id`=2
LIMIT 1 (/home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException()
#1 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/db/Command.php(1159): yii\db\Command->internalExecute()
#2 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/db/Command.php(415): yii\db\Command->queryInternal()
#3 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Command->queryOne()
#4 /home/vagrant/code/fn-migrate/vendor/craftcms/cms/src/db/Query.php(168): yii\db\Query->one()
#5 /home/vagrant/code/fn-migrate/vendor/craftcms/commerce/src/services/ProductTypes.php(789): craft\db\Query->one()
#6 /home/vagrant/code/fn-migrate/vendor/craftcms/commerce/src/migrations/m171202_180000_promotions_for_all_purchasables.php(377): craft\commerce\services\ProductTypes->getProductTypeById()
#7 /home/vagrant/code/fn-migrate/vendor/craftcms/commerce/src/migrations/m171202_180000_promotions_for_all_purchasables.php(104): craft\commerce\migrations\m171202_180000_promotions_for_all_purchasables->_createCategoryFieldsOnProducts()
#8 /home/vagrant/code/fn-migrate/vendor/craftcms/cms/src/db/Migration.php(52): craft\commerce\migrations\m171202_180000_promotions_for_all_purchasables->safeUp()
#9 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(725): craft\db\Migration->up()
#10 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(200): yii\console\controllers\BaseMigrateController->migrateUp()
#11 /home/vagrant/code/fn-migrate/vendor/craftcms/cms/src/console/controllers/MigrateController.php(314): yii\console\controllers\BaseMigrateController->actionUp()
#12 [internal function]: craft\console\controllers\MigrateController->actionUp()
#13 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#14 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#15 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction()
#16 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction()
#17 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#18 /home/vagrant/code/fn-migrate/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction()
#19 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#20 /home/vagrant/code/fn-migrate/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest()
#21 /home/vagrant/code/fn-migrate/craft(22): yii\base\Application->run()
#22 {main}
*** failed to apply m171202_180000_promotions_for_all_purchasables (time: 0.940s)
```

</details>

After a bit of digging, it seems that the `variantTitleLabel` field is in the query for [`getProductTypes`](https://github.com/craftcms/commerce/blob/21722ec37f53721e509e4c38b427c597e54dd11d/src/services/ProductTypes.php#L883) called in [`_createCategoryFieldsOnProducts`](https://github.com/craftcms/commerce/blob/develop/src/migrations/m171202_180000_promotions_for_all_purchasables.php#L377) but isn't created until a [later migration](https://github.com/craftcms/commerce/blob/develop/src/migrations/m200102_141910_add_variantTitleLabel_attribute.php). 

I was able to work around this for now by moving the `m200102_141910_add_variantTitleLabel_attribute` (and `m191203_163242_add_titleLabel_to_product_type`) migration ahead of the `m171202_180000_promotions_for_all_purchasables` migration manually, but that may not be  a feasible option for everyone.

### Steps to reproduce

1. Load up Commerce 1 DB
2. run `craft migrate/up --plugin=commerce`

### Additional info

- Craft version: 3.5
- PHP version: 7.4.4
- Database driver & version: 5.7.29-0ubuntu0.18.04.1
- Plugins & versions: Commerce 3.1.x-dev (d327b12bb76012e8d153380588890afb327e2b0f)

**Comment by brianjhanson** [comment]
Just one other note, I had a similar issue with `m190131_000858_add_donation_purchasable` and `m190528_161915_description_on_purchasable` which I got around by renaming `m190528_161915_description_on_purchasable` to `m190130_161915_description_on_purchasable`

**Comment by nfourtythree** [comment]
Hi @brianjhanson 

Before upgrading to Commerce 3 you must be on the latest version of Commerce 2. This is likely where you encountered errors.

In your case upgrading `commerce 1 -> commerce 2` and running all the migrations. Followed by upgrading `commerce 2 -> commerce 3` and then running migrations should have seen a smooth upgrade path.

We have information on this in the [upgrading documentation for Commerce 3](https://docs.craftcms.com/commerce/v3/upgrading.html).

Thanks.

**Comment by brianjhanson** [comment]
Thanks @nfourtythree! I'm giving that a try now. Sorry for missing that large alert text at the top of the documentation 🤦
