### ISSUE TITLE
Commerce 3.2 Migration Error: Null Product Title Formats

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/commerce#1611]
**Description**
The upgrade migration fails when there are existing Product Types (presumably because of the [`notNull` without a `defaultValue`](https://github.com/craftcms/commerce/blob/6ea4526d6601a339ac03ebc1204d88d95da3a620/src/migrations/m200722_172699_product_title_format.php#L22) column type).

**To Reproduce**
How, and what happened?
1. Coming from Commerce 3.1.12, update via `./craft update commerce`
2. Observe Migration error

**Expected behavior**
😉

**Additional info**
- Craft version: 3.5.0
- Commerce version: 3.1.12 -> 3.2.0
- PHP version: 7.4.8
- Database driver & version: Postgres
- Other Plugins & versions: …

**Additional context**
Full stack trace!

```
Yii Migration Tool (based on Yii v2.0.36)

    > add column hasProductTitleField boolean to table {{%commerce_producttypes}} ... done (time: 0.001s)
    > add column productTitleFormat string NOT NULL to table {{%commerce_producttypes}} ...Exception: SQLSTATE[23502]: Not null violation: 7 ERROR:  column "productTitleFormat" contains null values
The SQL being executed was: ALTER TABLE "commerce_producttypes" ADD "productTitleFormat" varchar(255) NOT NULL (/Users/august/Sites/vandenberg/vendor/yiisoft/yii2/db/Schema.php:677)
#0 /Users/august/Sites/vandenberg/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE "co...')
#1 /Users/august/Sites/vandenberg/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('ALTER TABLE "co...')
#2 /Users/august/Sites/vandenberg/vendor/yiisoft/yii2/db/Migration.php(377): yii\db\Command->execute()
#3 /Users/august/Sites/vandenberg/vendor/craftcms/commerce/src/migrations/m200722_172699_product_title_format.php(22): yii\db\Migration->addColumn('{{%commerce_pro...', 'productTitleFor...', Object(yii\db\ColumnSchemaBuilder))
#4 /Users/august/Sites/vandenberg/vendor/craftcms/cms/src/db/Migration.php(52): craft\commerce\migrations\m200722_172699_product_title_format->safeUp()
#5 /Users/august/Sites/vandenberg/vendor/craftcms/cms/src/db/MigrationManager.php(228): craft\db\Migration->up(true)
#6 /Users/august/Sites/vandenberg/vendor/craftcms/cms/src/db/MigrationManager.php(148): craft\db\MigrationManager->migrateUp(Object(craft\commerce\migrations\m200722_172699_product_title_format))
#7 /Users/august/Sites/vandenberg/vendor/craftcms/cms/src/services/Updates.php(227): craft\db\MigrationManager->up()
#8 /Users/august/Sites/vandenberg/vendor/craftcms/cms/src/console/controllers/MigrateController.php(328): craft\services\Updates->runMigrations(Array)
#9 [internal function]: craft\console\controllers\MigrateController->actionAll()
#10 /Users/august/Sites/vandenberg/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /Users/august/Sites/vandenberg/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#12 /Users/august/Sites/vandenberg/vendor/yiisoft/yii2/console/Controller.php(181): yii\base\Controller->runAction('all', Array)
#13 /Users/august/Sites/vandenberg/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#14 /Users/august/Sites/vandenberg/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#15 /Users/august/Sites/vandenberg/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('migrate/all', Array)
#16 /Users/august/Sites/vandenberg/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#17 /Users/august/Sites/vandenberg/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#18 /Users/august/Sites/vandenberg/craft(23): yii\base\Application->run()
#19 {main}
```

**Comment by AugustMiller** [comment]
Oops, I see this is fixed in 3.2.0.1! Thanks! <3
