### ISSUE TITLE
Unable to rebuild project config on Craft 3.5.0 with Commerce 3.2

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/commerce#1618]
**Description**
When trying to rebuild the project config on Craft 3.5 with Commerce 3.2 I get the following error:

```
Rebuilding the project config from the current state ... error: Unexpected data encountered in config data
2020-08-05 16:04:02 [-][-][-][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: Unexpected data encountered in config data in /app/user/vendor/craftcms/cms/src/helpers/ProjectConfig.php:178
Stack trace:
#0 /app/user/vendor/craftcms/cms/src/helpers/ProjectConfig.php(182): craft\helpers\ProjectConfig::cleanupConfig(Array)
#1 /app/user/vendor/craftcms/cms/src/helpers/ProjectConfig.php(182): craft\helpers\ProjectConfig::cleanupConfig(Array)
#2 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(434): craft\helpers\ProjectConfig::cleanupConfig(Array)
#3 /app/user/vendor/craftcms/cms/src/services/ProjectConfig.php(1156): craft\services\ProjectConfig->set('commerce', Array, 'Project config ...')
#4 /app/user/vendor/craftcms/cms/src/console/controllers/ProjectConfigController.php(140): craft\services\ProjectConfig->rebuild()
#5 [internal function]: craft\console\controllers\ProjectConfigController->actionRebuild()
#6 /app/user/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /app/user/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#8 /app/user/vendor/yiisoft/yii2/console/Controller.php(181): yii\base\Controller->runAction('rebuild', Array)
#9 /app/user/vendor/craftcms/cms/src/console/Controller.php(188): yii\console\Controller->runAction('rebuild', Array)
#10 /app/user/vendor/yiisoft/yii2/base/Module.php(528): craft\console\Controller->runAction('rebuild', Array)
#11 /app/user/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('project-config/...', Array)
#12 /app/user/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('project-config/...', Array)
#13 /app/user/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('project-config/...', Array)
#14 /app/user/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#15 /app/user/craft(24): yii\base\Application->run()
#16 {main}
2020-08-05 16:04:01 [-][-][-][info][application] $_GET = []

$_POST = []
```

As you can see in the stacktrace this happens when setting "commerce"

**To Reproduce**
How, and what happened?
1. Rebuild project config with Craft 3.5 and Commerce 3.2

**Expected behavior**
No error

**Additional info**
- Craft version: 3.5
- Commerce version: 3.2
- PHP version: 7.4.8
- Database driver & version: PostgreSQL 11.8
- Other Plugins & versions: -

**Comment by brandonkelly** [comment]
@boboldehampsink can you please send a database backup and your Composer files into support@craftcms.com?

**Comment by boboldehampsink** [comment]
Done

**Comment by lukeholder** [comment]
@boboldehampsink 

Thanks for reporting that! I’ve just fixed it for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#230baf088323fe1387e0bc9a6e6a5a4c6db7e131 as 3.2.0.2",
  "...": "..."a
}
```

Then run `composer update`.
