### ISSUE TITLE
Updating Commerce 2 to Commerce 3

### ISSUE THREAD

**Issue by bhashkar007** [craftcms/commerce#1726]
**Description**
I am trying to update Commerce 2 to Commerce 3 but getting lot of error while migration. I tried with command `php craft migrate/up --plugin=commerce` and also update console in web. 
```
*** applying m160531_154500_craft3_upgrade
    > update in {{%elements}} ... done (time: 0.082s)
    > update in {{%elements}} ... done (time: 0.001s)
    > update in {{%elements}} ... done (time: 0.000s)
    > update in {{%fields}} ... done (time: 0.034s)
    > update in {{%fields}} ... done (time: 0.001s)
    > update in {{%widgets}} ... done (time: 0.075s)
    > update in {{%widgets}} ... done (time: 0.001s)
Exception: Trying to get property of non-object (/Users/bhashkar/Sites/craft-cms/wiper/vendor/craftcms/cms/src/helpers/MigrationHelper.php:498)
#0 /Users/bhashkar/Sites/craft-cms/project-name/vendor/craftcms/cms/src/helpers/MigrationHelper.php(498): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/Users/bhashkar...', 498, Array)
#1 /Users/bhashkar/Sites/craft-cms/project-name/vendor/craftcms/commerce/src/migrations/m160531_154500_craft3_upgrade.php(45): craft\helpers\MigrationHelper::dropAllForeignKeysOnTable('{{%commerce_pro...')
#2 /Users/bhashkar/Sites/craft-cms/project-name/vendor/craftcms/cms/src/db/Migration.php(52): craft\commerce\migrations\m160531_154500_craft3_upgrade->safeUp()
#3 /Users/bhashkar/Sites/craft-cms/project-name/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(727): craft\db\Migration->up()
#4 /Users/bhashkar/Sites/craft-cms/project-name/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(202): yii\console\controllers\BaseMigrateController->migrateUp('m160531_154500_...')
#5 /Users/bhashkar/Sites/craft-cms/project-name/vendor/craftcms/cms/src/console/controllers/MigrateController.php(383): yii\console\controllers\BaseMigrateController->actionUp(0)
#6 [internal function]: craft\console\controllers\MigrateController->actionUp(0)
#7 /Users/bhashkar/Sites/craft-cms/project-name/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /Users/bhashkar/Sites/craft-cms/project-name/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#9 /Users/bhashkar/Sites/craft-cms/project-name/vendor/yiisoft/yii2/console/Controller.php(181): yii\base\Controller->runAction('up', Array)
#10 /Users/bhashkar/Sites/craft-cms/project-name/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('up', Array)
#11 /Users/bhashkar/Sites/craft-cms/project-name/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/up', Array)
#12 /Users/bhashkar/Sites/craft-cms/project-name/vendor/craftcms/cms/src/console/Application.php(101): yii\console\Application->runAction('migrate/up', Array)
#13 /Users/bhashkar/Sites/craft-cms/project-name/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/up', Array)
#14 /Users/bhashkar/Sites/craft-cms/project-name/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#15 /Users/bhashkar/Sites/craft-cms/project-name/craft(23): yii\base\Application->run()
#16 {main}
```
I tried by deleted `m160531_154500_craft3_upgrade.php` to skip this migration step but started getting another migration error:
```
*** applying m170616_154500_productTypeSites_upgrade
    > add column template string(500) to table {{%commerce_producttypes_i18n}} ...Exception: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'template'
The SQL being executed was: ALTER TABLE `commerce_producttypes_i18n` ADD `template` varchar(500) (/Users/bhashkar/Sites/craft-cms/project-name/vendor/yiisoft/yii2/db/Schema.php:677)
#0 /Users/bhashkar/Sites/craft-cms/project-name/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `co...')
#1 /Users/bhashkar/Sites/craft-cms/project-name/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('ALTER TABLE `co...')
#2 /Users/bhashkar/Sites/craft-cms/project-name/vendor/yiisoft/yii2/db/Migration.php(377): yii\db\Command->execute()
#3 /Users/bhashkar/Sites/craft-cms/project-name/vendor/craftcms/commerce/src/migrations/m170616_154500_productTypeSites_upgrade.php(23): yii\db\Migration->addColumn('{{%commerce_pro...', 'template', Object(craft\db\mysql\ColumnSchemaBuilder))
#4 /Users/bhashkar/Sites/craft-cms/project-name/vendor/craftcms/cms/src/db/Migration.php(52): craft\commerce\migrations\m170616_154500_productTypeSites_upgrade->safeUp()
#5 /Users/bhashkar/Sites/craft-cms/project-name/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(727): craft\db\Migration->up()
#6 /Users/bhashkar/Sites/craft-cms/project-name/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(202): yii\console\controllers\BaseMigrateController->migrateUp('m170616_154500_...')
#7 /Users/bhashkar/Sites/craft-cms/project-name/vendor/craftcms/cms/src/console/controllers/MigrateController.php(383): yii\console\controllers\BaseMigrateController->actionUp(0)
#8 [internal function]: craft\console\controllers\MigrateController->actionUp(0)
#9 /Users/bhashkar/Sites/craft-cms/project-name/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /Users/bhashkar/Sites/craft-cms/project-name/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#11 /Users/bhashkar/Sites/craft-cms/project-name/vendor/yiisoft/yii2/console/Controller.php(181): yii\base\Controller->runAction('up', Array)
#12 /Users/bhashkar/Sites/craft-cms/project-name/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('up', Array)
#13 /Users/bhashkar/Sites/craft-cms/project-name/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/up', Array)
#14 /Users/bhashkar/Sites/craft-cms/project-name/vendor/craftcms/cms/src/console/Application.php(101): yii\console\Application->runAction('migrate/up', Array)
#15 /Users/bhashkar/Sites/craft-cms/project-name/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/up', Array)
#16 /Users/bhashkar/Sites/craft-cms/project-name/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#17 /Users/bhashkar/Sites/craft-cms/project-name/craft(23): yii\base\Application->run()
#18 {main}
```
I kept getting further errors when tried to skip any migration step and doing database changes manually.

**To Reproduce**
How, and what happened?
1. Updated Craft CMS v3.4.0 to v3.5.9
2. Updated other plugins like "Element API", "Feed Me", "Mailchimp Subscribe", "PayPal Checkout for Craft Commerce" etc to latest version successfully.
3. Updated Craft Commerce v2.2.19 to v3.2.6 with composer.
4. Run `php craft migrate/up --plugin=commerce`. Even tried with web update after accessing dashboard

**Expected behavior**
What did you expect to happen?
Migration from Craft Commerce 2 to Craft Commerce 3

**Additional info**
- Craft version: 3.5.9
- Commerce version: v3.2.6
- PHP version: 7.0.33
- Database driver & version: 5.5.69
- Other Plugins & versions:
-- Mailchimp Subscribe: 3.0.2
-- Sprout Seo: 4.6.3
-- Commerce Paypal Checkout: 1.1.1
-- Commerce Stripe: 2.3.1.1
-- Element API: 2.6.0
-- Feed Me: 4.2.3
-- SEOmatic: 3.3.13
-- Sendgrid: 1.2.2
-- Wordsmith: 3.3.0.1
-- Navigation: 1.3.23
-- Super Table: 2.5.2

**Comment by lukeholder** [comment]
Thanks, this should be fixed in the next release.

Once that is out (will be 3.2.7), upgrade to that and let us know how you go.
