### ISSUE TITLE
Cannot access user profile

### ISSUE THREAD

**Issue by MemphisNguyen** [craftcms/commerce#2045]
**Description**
invalid reference for array key. The error cause exception when accessing a profile of a user who made a purchase before.

**To Reproduce**
1. In the CP, go to Users
2. Select a user who made a purchase.

**Additional info**
- Craft version: 3.6.9
- Commerce version: 3.2.17.1

**Additional context**
```
yii\base\ErrorException: craft\commerce\models\Address::craft\commerce\models\{closure}(): Argument #2 ($key) must be passed by reference, value given in /craft/vendor/craftcms/commerce/src/models/Address.php:544
Stack trace:
#0 /craft/vendor/craftcms/cms/src/web/ErrorHandler.php(77): yii\base\ErrorHandler->handleError(2, 'craft\\commerce\\...', '/craft/vendor/c...', 544)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'craft\\commerce\\...', '/craft/vendor/c...', 544)
#2 /craft/vendor/craftcms/commerce/src/models/Address.php(544): array_walk(Array, Object(Closure))
#3 /craft/vendor/twig/twig/src/Extension/CoreExtension.php(1507): craft\commerce\models\Address->getAddressLines(true)
#4 /craft/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\commerce\models\Address), 'getAddressLines', Array, 'method', false, false)
```

**Comment by nfourtythree** [comment]
Hi @MemphisNguyen 

This is a duplicate issue (#1987) related to PHP 8 compatibility which has been fixed in the upcoming `3.3` release.

Thanks!
