### ISSUE TITLE
Unpaid subscription page in CP throws error

### ISSUE THREAD

**Issue by jameslindeman** [craftcms/commerce#2046]
**Description**
Trying to access an unpaid subscription in the control panel throws an error, ‘Trying to access array offset on value of type null’.

This happens on a server running PHP 7.4.x but works without error on another running PHP 7.2.x

```
yii\base\ErrorException: Trying to access array offset on value of type null in .../vendor/craftcms/commerce-stripe/src/gateways/PaymentIntents.php:366
Stack trace:
#0 .../vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(8, 'Trying to acces...', '/Users/...', 366)
#1 .../vendor/craftcms/commerce-stripe/src/gateways/PaymentIntents.php(366): craft\web\ErrorHandler->handleError(8, 'Trying to acces...', '/Users/...', 366, Array)
#2 .../vendor/craftcms/commerce/src/elements/Subscription.php(646): craft\commerce\stripe\gateways\PaymentIntents->getBillingIssueDescription(Object(craft\commerce\elements\Subscription))
#3 .../vendor/twig/twig/src/Extension/CoreExtension.php(1499): craft\commerce\elements\Subscription->getBillingIssueDescription()
#4 .../vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\commerce\elements\Subscription), 'getBillingIssue...', Array, 'method', false, false)
#5 /Users/.../storage/runtime/compiled_templates/a9/a92917bd6c842c23ae2583ae01ad8240dc6d5fafbb011b2916e98b05214fdbae.php(615): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\commerce\elements\Subscription), 'getBillingIssue...', Array, 'method')
#6 .../vendor/twig/twig/src/Template.php(182): __TwigTemplate_0341153b62246e26c52f5c39c612c06431c2223fe03d9acc80f358a5240ead0b->block_details(Array, Array)
#7 .../vendor/twig/twig/src/Template.php(254): Twig\Template->displayBlock('details', Array, Array, true)
#8 /Users/.../storage/runtime/compiled_templates/65/658583d5103c65a8f7d37fa8dc9c496229d84d7b5927c56dc6076874b5843d64.php(101): Twig\Template->renderBlock('details', Array, Array)
#9 .../vendor/twig/twig/src/Template.php(405): __TwigTemplate_d88f06f1ddfbb2e97a4c7c535898c6aa9a0fa8f9c67e36769d537d9fb97f145f->doDisplay(Array, Array)
#10 .../vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /Users/.../storage/runtime/compiled_templates/a9/a92917bd6c842c23ae2583ae01ad8240dc6d5fafbb011b2916e98b05214fdbae.php(79): Twig\Template->display(Array, Array)
#12 .../vendor/twig/twig/src/Template.php(405): __TwigTemplate_0341153b62246e26c52f5c39c612c06431c2223fe03d9acc80f358a5240ead0b->doDisplay(Array, Array)
#13 .../vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#14 .../vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#15 .../vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#16 .../vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#17 .../vendor/craftcms/cms/src/web/View.php(389): Twig\Environment->render('commerce/subscr...', Array)
#18 .../vendor/craftcms/cms/src/web/View.php(450): craft\web\View->renderTemplate('commerce/subscr...', Array)
#19 .../vendor/craftcms/cms/src/web/Controller.php(241): craft\web\View->renderPageTemplate('commerce/subscr...', Array, 'cp')
#20 .../vendor/craftcms/commerce/src/controllers/SubscriptionsController.php(98): craft\web\Controller->renderTemplate('commerce/subscr...', Array)
#21 [internal function]: craft\commerce\controllers\SubscriptionsController->actionEdit(15201, Object(craft\commerce\elements\Subscription))
#22 .../vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#23 .../vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#24 .../vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('edit', Array)
#25 .../vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit', Array)
#26 .../vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('commerce/subscr...', Array)
#27 .../vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('commerce/subscr...', Array)
#28 .../vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#29 .../vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#30 .../web/index.php(21): yii\base\Application->run()
#31 .../.composer/vendor/weprovide/valet-plus/server.php(131): require('/Users/...')
#32 {main}
```

**To Reproduce**
1. Have an unpaid subscription
2. Try to manage that subscription in the control panel. The URL would be something like this: `https://example.test/admin/commerce/subscriptions/12345`

**Additional info**
- Craft version: ~~3.5.16~~ 3.6.10
- Commerce version: ~~3.2.13~~ 3.2.17.2
- PHP version: 7.4.11

**Comment by lukeholder** [comment]
@jameslindeman please confirm this is still an issue on the latest Commerce and Stripe release and raise the issue on the https://github.com/craftcms/commerce-stripe repo. Thanks.
