### ISSUE TITLE
[3.6.14] Address argument #2 must be passed by reference

### ISSUE THREAD

**Issue by richardhedges** [craftcms/commerce#2212]
### Description

When viewing a customer using Pro on PHP 8.0 the following error is returned:
`craft\commerce\models\Address::craft\commerce\models\{closure}(): Argument #2 ($key) must be passed by reference, value given`

The error disappears when reverting to PHP 7.4.

I also raised this in the [cms repository](https://github.com/craftcms/cms/issues/8084).

### Steps to reproduce

1. Create a customer
2. View the customer in the admin panel

### Additional info

- Craft version: 3.6.14
- PHP version: 8
- Database driver & version: MySQL 5.7.23
- Plugins & versions: Commerce 3.2.17.4

**Comment by brandonkelly** [comment]
Please look for the error in your logs and post the stack trace that follows it.

**Comment by richardhedges** [comment]
```yii\base\ErrorException: craft\commerce\models\Address::craft\commerce\models\{closure}(): Argument #2 ($key) must be passed by reference, value given in /Users/richardhedges/Sites/craftsite/vendor/craftcms/commerce/src/models/Address.php:544
Stack trace:
#0 /Users/richardhedges/Sites/craftsite/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(2, 'craft\\commerce\\...', '/Users/richardh...', 544)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'craft\\commerce\\...', '/Users/richardh...', 544)
#2 /Users/richardhedges/Sites/craftsite/vendor/craftcms/commerce/src/models/Address.php(544): array_walk(Array, Object(Closure))
#3 /Users/richardhedges/Sites/craftsite/vendor/twig/twig/src/Extension/CoreExtension.php(1511): craft\commerce\models\Address->getAddressLines(true)
#4 /Users/richardhedges/Sites/craftsite/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\commerce\models\Address), 'getAddressLines', Array, 'method', false, false)
#5 /Users/richardhedges/Sites/craftsite/storage/runtime/compiled_templates/fc/fce8a292790332075eef6a077adbf5993ddd2ae173864e0c78285271a08cd13d.php(61): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\commerce\models\Address), 'getAddressLines', Array, 'method')
#6 /Users/richardhedges/Sites/craftsite/vendor/twig/twig/src/Template.php(405): __TwigTemplate_d49da0b244034cb2c34d613a95f0e8df356c2712f2e4b161899921ad02da96fb->doDisplay(Array, Array)
#7 /Users/richardhedges/Sites/craftsite/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#8 /Users/richardhedges/Sites/craftsite/storage/runtime/compiled_templates/a9/a98f108d997045a2d94781b24a1fed1071b7665de52b288df68823dff382cf75.php(209): Twig\Template->display(Array)
#9 /Users/richardhedges/Sites/craftsite/vendor/twig/twig/src/Template.php(182): __TwigTemplate_c62cf17e5098e6142708e2ec1be41a6b75ba82d99ff52553e6253af33045e9c0->block_content(Array, Array)
#10 /Users/richardhedges/Sites/craftsite/storage/runtime/compiled_templates/e8/e82f8aaa5dc28b966c9d081c457c310d68390f73a5c35492cc6d35ae382e2e6d.php(505): Twig\Template->displayBlock('content', Array, Array)
#11 /Users/richardhedges/Sites/craftsite/vendor/twig/twig/src/Template.php(182): __TwigTemplate_af28942a306c637ed1746ace0951ec1149cdf463238d3d2658000a79de654c23->block_main(Array, Array)
#12 /Users/richardhedges/Sites/craftsite/storage/runtime/compiled_templates/e8/e82f8aaa5dc28b966c9d081c457c310d68390f73a5c35492cc6d35ae382e2e6d.php(324): Twig\Template->displayBlock('main', Array, Array)
#13 /Users/richardhedges/Sites/craftsite/vendor/twig/twig/src/Template.php(182): __TwigTemplate_af28942a306c637ed1746ace0951ec1149cdf463238d3d2658000a79de654c23->block_body(Array, Array)
#14 /Users/richardhedges/Sites/craftsite/storage/runtime/compiled_templates/da/da68632bd2ab8ad58c7da3b7b41b18e3e1667687219a0fefbc561c7b6ad1f4b7.php(90): Twig\Template->displayBlock('body', Array, Array)
#15 /Users/richardhedges/Sites/craftsite/vendor/twig/twig/src/Template.php(405): __TwigTemplate_001faa10039060672cdfaeb0cda9c6144c23fbd9cbaee1fd7ef6613148858fc9->doDisplay(Array, Array)
#16 /Users/richardhedges/Sites/craftsite/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#17 /Users/richardhedges/Sites/craftsite/storage/runtime/compiled_templates/50/508844601291b065c0c64f55e7954ac72e287e5c9434b9d8194f93de4f7a5273.php(56): Twig\Template->display(Array, Array)
#18 /Users/richardhedges/Sites/craftsite/vendor/twig/twig/src/Template.php(405): __TwigTemplate_889ab13faacea2970d15adb80711d7272bd5ed5586ca84fe525e300938cd4e67->doDisplay(Array, Array)
#19 /Users/richardhedges/Sites/craftsite/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#20 /Users/richardhedges/Sites/craftsite/storage/runtime/compiled_templates/e8/e82f8aaa5dc28b966c9d081c457c310d68390f73a5c35492cc6d35ae382e2e6d.php(166): Twig\Template->display(Array, Array)
#21 /Users/richardhedges/Sites/craftsite/vendor/twig/twig/src/Template.php(405): __TwigTemplate_af28942a306c637ed1746ace0951ec1149cdf463238d3d2658000a79de654c23->doDisplay(Array, Array)
#22 /Users/richardhedges/Sites/craftsite/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#23 /Users/richardhedges/Sites/craftsite/storage/runtime/compiled_templates/8a/8aaae84a75dbc883f56664e810f8ac666c18e969069418e3e7005fa752bc7597.php(45): Twig\Template->display(Array, Array)
#24 /Users/richardhedges/Sites/craftsite/vendor/twig/twig/src/Template.php(405): __TwigTemplate_2763656d41934b30a3cc4c5a486f1aae5280c0eaf015a73af9c3f9b306b5d408->doDisplay(Array, Array)
#25 /Users/richardhedges/Sites/craftsite/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#26 /Users/richardhedges/Sites/craftsite/storage/runtime/compiled_templates/a9/a98f108d997045a2d94781b24a1fed1071b7665de52b288df68823dff382cf75.php(57): Twig\Template->display(Array, Array)
#27 /Users/richardhedges/Sites/craftsite/vendor/twig/twig/src/Template.php(405): __TwigTemplate_c62cf17e5098e6142708e2ec1be41a6b75ba82d99ff52553e6253af33045e9c0->doDisplay(Array, Array)
#28 /Users/richardhedges/Sites/craftsite/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#29 /Users/richardhedges/Sites/craftsite/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#30 /Users/richardhedges/Sites/craftsite/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#31 /Users/richardhedges/Sites/craftsite/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#32 /Users/richardhedges/Sites/craftsite/vendor/craftcms/cms/src/web/View.php(389): Twig\Environment->render('commerce/custom...', Array)
#33 /Users/richardhedges/Sites/craftsite/vendor/craftcms/cms/src/web/View.php(450): craft\web\View->renderTemplate('commerce/custom...', Array)
#34 /Users/richardhedges/Sites/craftsite/vendor/craftcms/cms/src/web/Controller.php(257): craft\web\View->renderPageTemplate('commerce/custom...', Array, 'cp')
#35 /Users/richardhedges/Sites/craftsite/vendor/craftcms/commerce/src/controllers/CustomersController.php(70): craft\web\Controller->renderTemplate('commerce/custom...', Array)
#36 [internal function]: craft\commerce\controllers\CustomersController->actionEdit(27, NULL)
#37 /Users/richardhedges/Sites/craftsite/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#38 /Users/richardhedges/Sites/craftsite/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#39 /Users/richardhedges/Sites/craftsite/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('edit', Array)
#40 /Users/richardhedges/Sites/craftsite/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('edit', Array)
#41 /Users/richardhedges/Sites/craftsite/vendor/craftcms/cms/src/web/Application.php(278): yii\base\Module->runAction('commerce/custom...', Array)
#42 /Users/richardhedges/Sites/craftsite/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('commerce/custom...', Array)
#43 /Users/richardhedges/Sites/craftsite/vendor/craftcms/cms/src/web/Application.php(263): yii\web\Application->handleRequest(Object(craft\web\Request))
#44 /Users/richardhedges/Sites/craftsite/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#45 /Users/richardhedges/Sites/craftsite/web/index.php(22): yii\base\Application->run()
#46 /Users/richardhedges/.composer/vendor/laravel/valet/server.php(219): require('/Users/richardh...')
#47 {main}

**Comment by richardhedges** [comment]
The specific piece of code causing the problem is here:

```php
if ($sanitize) {
    array_walk($event->addressLines, function(&$value, &$key) {
        $value = Craft::$app->getFormatter()->asText($value);
    });
}
```

`$key` looks to be unused, so removing it fixes the issue. Or you could just remove the `&`.

**Comment by richardhedges** [comment]
Sorry, can see this was fixed in an update.

**Comment by nfourtythree** [comment]
Hi @richardhedges 

Glad this is sorted 👍 

Thanks!
