### ISSUE TITLE
getOrderById method throws an error if order id greater than 999

### ISSUE THREAD

**Issue by rstix** [craftcms/commerce#2525]
### Description
I created an order and the payment was successfully but when trying to render the confirmation page of that order I got an error "A non well formed numeric value encountered"

```
yii\base\ErrorException: A non well formed numeric value encountered in /app/vendor/craftcms/commerce/src/services/Orders.php:102
Stack trace:
#0 /app/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(8, 'A non well form...', '/app/vendor/cra...', 102)
#1 /app/vendor/craftcms/commerce/src/services/Orders.php(102): craft\web\ErrorHandler->handleError(8, 'A non well form...', '/app/vendor/cra...', 102, Array)
#2 /app/vendor/twig/twig/src/Extension/CoreExtension.php(1511): craft\commerce\services\Orders->getOrderById('1,845')
#3 /app/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\commerce\services\Orders), 'getOrderById', Array, 'method', false, false)
#4 /app/storage/runtime/compiled_templates/4b/4b093c322e0bd963a06cd8c68cbc26c9da66353a07d1f0e77dd67c94dc7bc16a.php(55): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\commerce\services\Orders), 'getOrderById', Array, 'method')
#5 /app/vendor/twig/twig/src/Template.php(182): __TwigTemplate_3c78f0e0cd6ded83e0a25d66b0b97e724d1f5ca3674f2e09c84d203467ba72ca->block_body(Array, Array)
#6 /app/storage/runtime/compiled_templates/60/606984e68bd3edcfa4b62958b9df190ee7eed25ec1534e36ed2830840f23e227.php(203): Twig\Template->displayBlock('body', Array, Array)
#7 /app/vendor/twig/twig/src/Template.php(405): __TwigTemplate_978d3012dee5a89932eb039946443047f3c51a537c80af68d4203bab53378f0a->doDisplay(Array, Array)
#8 /app/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#9 /app/storage/runtime/compiled_templates/4b/4b093c322e0bd963a06cd8c68cbc26c9da66353a07d1f0e77dd67c94dc7bc16a.php(43): Twig\Template->display(Array, Array)
#10 /app/vendor/twig/twig/src/Template.php(405): __TwigTemplate_3c78f0e0cd6ded83e0a25d66b0b97e724d1f5ca3674f2e09c84d203467ba72ca->doDisplay(Array, Array)
#11 /app/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#12 /app/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#13 /app/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#14 /app/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#15 /app/vendor/craftcms/cms/src/web/View.php(401): Twig\Environment->render('shop/confirmati...', Array)
#16 /app/vendor/craftcms/cms/src/web/View.php(462): craft\web\View->renderTemplate('shop/confirmati...', Array)
#17 /app/vendor/craftcms/cms/src/web/Controller.php(257): craft\web\View->renderPageTemplate('shop/confirmati...', Array, 'site')
#18 /app/vendor/craftcms/cms/src/controllers/TemplatesController.php(100): craft\web\Controller->renderTemplate('shop/confirmati...', Array)
#19 [internal function]: craft\controllers\TemplatesController->actionRender('shop/confirmati...', Array)
#20 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#21 /app/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#22 /app/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('render', Array)
#23 /app/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('render', Array)
#24 /app/vendor/craftcms/cms/src/web/Application.php(271): yii\base\Module->runAction('templates/rende...', Array)
#25 /app/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('templates/rende...', Array)
#26 /app/vendor/craftcms/cms/src/web/Application.php(256): yii\web\Application->handleRequest(Object(craft\web\Request))
#27 /app/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#28 /app/web/index.php(24): yii\base\Application->run()
#29 {main}
```

### Additional info

- Craft CMS version: 3.7.0
- Craft Commerce version: 3.4.2
- PHP version: 7.4.21
- Database driver & version: MySQL 5.5.5
- Plugins & versions:  Element API 2.7.0, Migration Assistant 3.2.6, Neo 2.10.8, Redactor 2.8.7, Stripe for Craft Commerce 2.3.2.1

**Comment by lukeholder** [comment]
Please share your template code and the URL used to access the template.

**Comment by rstix** [comment]
@lukeholder I checked the template again and I saw it,it was on my side, sorry for that.
