### ISSUE TITLE
"Save as a new product" doesn't catch an exception

### ISSUE THREAD

**Issue by dhahn** [craftcms/commerce#2549]
### Description
This one should be pretty easy to replicate, but we had a bug in some custom code that was breaking the "save as a new product" functionality. That was all on us, but line 285 isn't catching the exception so it throws a 500 with the error:

```
TypeError: Argument 3 passed to yii\web\ServerErrorHttpException::__construct() must be an instance of Exception or null, instance of Error given, called in /var/www/html/vendor/craftcms/commerce/src/controllers/ProductsController.php on line 285 and defined in /var/www/html/vendor/yiisoft/yii2/web/ServerErrorHttpException.php:25
Stack trace:
#0 /var/www/html/vendor/craftcms/commerce/src/controllers/ProductsController.php(285): yii\web\ServerErrorHttpException->__construct('An error occurr...', 0, Object(Error))
#1 [internal function]: craft\commerce\controllers\ProductsController->actionSaveProduct(true)
#2 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#4 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('save-product', Array)
#5 /var/www/html/vendor/craftcms/commerce/src/controllers/ProductsController.php(362): craft\web\Controller->runAction('save-product', Array)
#6 [internal function]: craft\commerce\controllers\ProductsController->actionDuplicateProduct()
#7 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#9 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('duplicate-produ...', Array)
#10 /var/www/html/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('duplicate-produ...', Array)
#11 /var/www/html/vendor/craftcms/cms/src/web/Application.php(278): yii\base\Module->runAction('commerce/produc...', Array)
#12 /var/www/html/vendor/craftcms/cms/src/web/Application.php(581): craft\web\Application->runAction('commerce/produc...', Array)
#13 /var/www/html/vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#14 /var/www/html/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#15 /var/www/html/public/index.php(26): yii\base\Application->run()
#16 {main}
```

### Steps to reproduce

1. Add a on save product handler that is broken:
```
        Event::on(
            Product::class,
            Product::EVENT_AFTER_SAVE,
            function ($event) {
                $event->sender->defaultVariant->getSomething();
            }
        );
```

2. Go to any product page in the admin
3. Click "save as a new product"
3. You should see an exception thrown unrelated to the actual broken code

### Additional info

- Craft CMS version: Craft Pro 3.6.16
- Craft Commerce version: 3.3.4
- PHP version: 7.3.19 (swear we're updating soon) :D 
- Database driver & version: MySQL 5.7
- Plugins & versions:
![Screen Shot 2021-09-13 at 10 37 09 AM](https://user-images.githubusercontent.com/2165506/133113652-5fee8670-9a58-4ef9-a887-a3ccd781e94e.png)

**Comment by lukeholder** [comment]
This is a tricky one. We don't usually try catch everywhere just in case an exception that a plugin adds to a core service event. What would you expect to happen if we catch it on save?

**Comment by dhahn** [comment]
Sorry missed this response last month and that makes a lot of sense to me.

I think mostly what doesn't feel right is that an admin gets the 500 internal server error page. I think I would expect it to:

1. catch the exception
2. prevent the product from saving
3. return an error to the admin
4. Log a stack trace to the logger

I could also see 1-3 not happening when dev mode is on
----

But all things considered maybe it does make sense to just keep it working as is because these errors should be dealt with.
