### ISSUE TITLE
Server error when searching in products in CP

### ISSUE THREAD

**Issue by hiasl** [craftcms/commerce#2649]
### Description
Our client just got a server error on the AJAX request happening when you enter a search termin in /admin/commerce/products

Interestingly we (agency) could not reproduce it, so we asked the client to try again in an anonymous window. 
Then they also did NOT get the error. 

For the failing request we found the following in the log:

```

2021-12-22 10:35:55 [-][1532][kiuuhto7g9kt43ltu2fo9lraok][error][yii\db\Exception] PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'score' in 'order clause' in /data/www/XXX/web/XXX/vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /data/www/XXX/web/XXX/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /data/www/XXX/web/XXX/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute()
#2 /data/www/XXX/web/XXX/vendor/yiisoft/yii2/db/Command.php(410): yii\db\Command->queryInternal()
#3 /data/www/XXX/web/XXX/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Command->queryAll()
#4 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/db/Query.php(152): yii\db\Query->all()
#5 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/services/Search.php(328): craft\db\Query->all()
#6 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/services/Search.php(238): craft\services\Search->_searchElements()
#7 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2822): craft\services\Search->searchElements()
#8 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1541): craft\elements\db\ElementQuery->_applySearchParam()
#9 /data/www/XXX/web/XXX/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare()
#10 /data/www/XXX/web/XXX/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build()
#11 /data/www/XXX/web/XXX/vendor/yiisoft/yii2/db/Query.php(249): yii\db\Query->createCommand()
#12 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/db/Query.php(152): yii\db\Query->all()
#13 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1619): craft\db\Query->all()
#14 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/base/Element.php(867): craft\elements\db\ElementQuery->all()
#15 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(534): craft\base\Element::indexHtml()
#16 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(135): craft\controllers\ElementIndexesController->elementResponseData()
#17 [internal function]: craft\controllers\ElementIndexesController->actionGetElements()
#18 /data/www/XXX/web/XXX/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#19 /data/www/XXX/web/XXX/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#20 /data/www/XXX/web/XXX/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction()
#21 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction()
#22 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/web/Application.php(596): craft\web\Application->runAction()
#23 /data/www/XXX/web/XXX/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest()
#24 /data/www/XXX/web/XXX/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#25 /data/www/XXX/web/XXX/web/index.php(19): yii\base\Application->run()
#26 {main}

Next yii\db\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'score' in 'order clause'
The SQL being executed was: SELECT *
FROM `searchindex`
WHERE (MATCH(`keywords`) AGAINST('+mozar*' IN BOOLEAN MODE)) AND (`siteId`=1) AND (`elementId` IN (SELECT `elements`.`id`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`
FROM `elements` `elements`
INNER JOIN `commerce_products` `commerce_products` ON `commerce_products`.`id` = `elements`.`id`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `content` `content` ON (`content`.`elementId` = `elements`.`id`) AND (`content`.`siteId` = `elements_sites`.`siteId`)
WHERE (`commerce_products`.`typeId` IN ('2', '3')) AND (`commerce_products`.`typeId` IN ('2', '3')) AND (`elements_sites`.`siteId`=1) AND (`elements`.`archived`=FALSE) AND (`elements`.`dateDeleted` IS NULL) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL)
ORDER BY `score` DESC, `postDate` DESC) `subquery`
INNER JOIN `commerce_products` `commerce_products` ON `commerce_products`.`id` = `subquery`.`elementsId`
INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `content` `content` ON `content`.`id` = `subquery`.`contentId`
ORDER BY `score` DESC, `postDate` DESC)) in /data/www/XXX/web/XXX/vendor/yiisoft/yii2/db/Schema.php:678
Stack trace:

```

### Steps to reproduce

1. open /admin/commerce/products
2. enter a searchterm in the search field and wait for the AJAX call
3. the AJAX call fails with a short JSON response "an error occured" (or something similar)
### Additional info

- Craft CMS version: 3.7.25.1 Pro
- Craft Commerce version: 3.4.9.2
- PHP version: 7.4

**Comment by angrybrad** [comment]
Sounds like a Craft bug that was fixed way back in [3.4.4.1](https://github.com/craftcms/cms/issues/5599).

Am I correct that neither you nor your client is able to reproduce it now?

**Comment by hiasl** [comment]
Sorry @angrybrad, I do not understand what you mean.

- The client was able to reproduce the error, this was the reason why we wrote the ticket. We ourselves were never able to reproduce it, but we found the exception in the log.
- We have Craft 3.7.25.1 installed, so this fix from 3.4.4.1 should be still in the code and the error should NOT occur, right?
- So there must be some condition where it still happens...

**Comment by angrybrad** [comment]
Sorry, should have been more clear. Do you or your client have a consistent way to reproduce it now at all? It sounds like the answer is no, but just checking.

If not, any chance you could send a database dump and your compsoer.json/lock files over to support@craftcms.com and reference this issue and we'll see if we're able to find anything there based on the stack trace above.

**Comment by hiasl** [comment]
Here's an update on this issue:
- NEW: The client now had the same problem with normal entries (not only products)
- Yes, the client could reproduce it (I watched via Screensharing), both with FF and Chrome
- When I tried it from my browsers, it worked. It also worked for the client in incognito mode of their FF and Chrome.
- So we assume it must be somehow session dependent
- Together with the client I started to remove all cookies except PHP Session ID, always trying the search again after clearing a single cookie. Did not change a thing, we always received the error, and also saw them in the log (see initial post)
- We also removed Local Storage Entries, to make sure this was not the reason (which it wasn't)
- We then logged out and in again and now it started working. So it must be session and/or cookie dependent AND needs a fresh login to be reset.
- The client told me that they need to login a couple of times per day, so the pure login process did not fix the problem before, but they might not have explicitly logged out before.
- What was interesting: After deleting cookies / local storage and logging in again in Chrome it also worked in FF. So either the explicit logout "click" solved the problem, because we also did that in FF, or my cookies/local storage cleanup causes some session corrections (although this does not explain why it worked cross-browser).

FYI: We also deactivated our own modules to make sure this error is not caused by something we added.

I could provide the DB dump and composer files, but I think it will not help at the moment because you won't be able to reproduce it, as we were also not able to reproduce from our computers.

I agreed with the client to contact me again when the problem happens again and then we will try to narrow it down.

My guess: there is some very special condition, in which the "score" column is still not SELECTed in the DB query, so the previous fix from craft 3.4 did not completely solve it.

**Comment by lukeholder** [comment]
Confirmed happening for entries also, so moving to `craftcms/cms` repo
