### ISSUE TITLE
Calling unknown method: craft\commerce\Plugin::countries()

### ISSUE THREAD

**Issue by Nellyaa** [craftcms/commerce#2763]
### Description

When attempting to use craft.commerce.countries, as suggested in the docs for 4.x (https://craftcms.com/docs/commerce/4.x/countries-states.html#fetching-countries), a twig error gets thrown suggesting this method doesn't exist in Commerce 4.

### Steps to reproduce

1. Use any twig in a template file that uses craft.commerce.countries e.g. {% set countries = craft.commerce.countries.allEnabledCountries %} with Commerce installed
2. load the template
3. Get error

### Expected behavior

You can use craft.commerce.countries and do anything mentioned in the docs in Twig, or have a suitable alternative that covers these uses. 

### Actual behavior

I get this Twig error:

```
An Error occurred while handling another error:
Twig\Error\RuntimeError: Calling unknown method: craft\commerce\Plugin::countries() in /var/www/templates/_views/account/order.twig:173
Stack trace:
#0 /var/www/storage/runtime/compiled_templates/2a/2ae16ac6a49343e421dce18f94ce1c77.php(355): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\commerce\Plugin), 'countries', Array)
#1 /var/www/vendor/twig/twig/src/Template.php(171): __TwigTemplate_09644bf9ea05f6710df85d085e7236f2->block_content(Array, Array)
#2 /var/www/storage/runtime/compiled_templates/4a/4af115b824a3ff3d52173a20fde84173.php(213): Twig\Template->displayBlock('content', Array, Array)
#3 /var/www/vendor/twig/twig/src/Template.php(171): __TwigTemplate_cc9daf8df567d4ae67bf2135d285d5eb->block_main(Array, Array)
#4 /var/www/storage/runtime/compiled_templates/e9/e9618d221a0ada493abd3d6aeb76787e.php(53): Twig\Template->displayBlock('main', Array, Array)
#5 /var/www/vendor/twig/twig/src/Template.php(394): __TwigTemplate_2b12db9ce6c801c1e31f4a9e788a54d6->doDisplay(Array, Array)
#6 /var/www/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#7 /var/www/storage/runtime/compiled_templates/4a/4af115b824a3ff3d52173a20fde84173.php(54): Twig\Template->display(Array, Array)
#8 /var/www/vendor/twig/twig/src/Template.php(394): __TwigTemplate_cc9daf8df567d4ae67bf2135d285d5eb->doDisplay(Array, Array)
#9 /var/www/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#10 /var/www/storage/runtime/compiled_templates/2a/2ae16ac6a49343e421dce18f94ce1c77.php(106): Twig\Template->display(Array, Array)
#11 /var/www/vendor/twig/twig/src/Template.php(394): __TwigTemplate_09644bf9ea05f6710df85d085e7236f2->doDisplay(Array, Array)
#12 /var/www/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#13 /var/www/storage/runtime/compiled_templates/17/1729f9474d8ca2f134bb8a3117581972.php(57): Twig\Template->display(Array)
#14 /var/www/vendor/twig/twig/src/Template.php(394): __TwigTemplate_96f60553bdd2d98fe7d10045d36bf750->doDisplay(Array, Array)
#15 /var/www/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#16 /var/www/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#17 /var/www/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#18 /var/www/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#19 /var/www/vendor/craftcms/cms/src/web/View.php(388): Twig\Environment->render('_views/account/...', Array)
#20 /var/www/vendor/craftcms/cms/src/web/View.php(441): craft\web\View->renderTemplate('_views/account/...', Array)
#21 /var/www/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(52): craft\web\View->renderPageTemplate('_views/account/...', Array, 'site')
#22 /var/www/vendor/yiisoft/yii2/web/Response.php(1095): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#23 /var/www/vendor/craftcms/cms/src/web/Response.php(274): yii\web\Response->prepare()
#24 /var/www/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#25 /var/www/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#26 /var/www/vendor/craftcms/cms/src/web/ErrorHandler.php(184): yii\web\ErrorHandler->renderException(Object(Twig\Error\RuntimeError))
#27 /var/www/vendor/yiisoft/yii2/base/ErrorHandler.php(135): craft\web\ErrorHandler->renderException(Object(Twig\Error\RuntimeError))
#28 /var/www/vendor/craftcms/cms/src/web/ErrorHandler.php(63): yii\base\ErrorHandler->handleException(Object(Twig\Error\RuntimeError))
#29 [internal function]: craft\web\ErrorHandler->handleException(Object(Twig\Error\RuntimeError))
#30 {main}
Previous exception:
Twig\Error\RuntimeError: Calling unknown method: craft\commerce\Plugin::countries() in /var/www/templates/_views/account/order.twig:173
Stack trace:
#0 /var/www/storage/runtime/compiled_templates/2a/2ae16ac6a49343e421dce18f94ce1c77.php(355): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\commerce\Plugin), 'countries', Array)
#1 /var/www/vendor/twig/twig/src/Template.php(171): __TwigTemplate_09644bf9ea05f6710df85d085e7236f2->block_content(Array, Array)
#2 /var/www/storage/runtime/compiled_templates/4a/4af115b824a3ff3d52173a20fde84173.php(213): Twig\Template->displayBlock('content', Array, Array)
#3 /var/www/vendor/twig/twig/src/Template.php(171): __TwigTemplate_cc9daf8df567d4ae67bf2135d285d5eb->block_main(Array, Array)
#4 /var/www/storage/runtime/compiled_templates/e9/e9618d221a0ada493abd3d6aeb76787e.php(53): Twig\Template->displayBlock('main', Array, Array)
#5 /var/www/vendor/twig/twig/src/Template.php(394): __TwigTemplate_2b12db9ce6c801c1e31f4a9e788a54d6->doDisplay(Array, Array)
#6 /var/www/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#7 /var/www/storage/runtime/compiled_templates/4a/4af115b824a3ff3d52173a20fde84173.php(54): Twig\Template->display(Array, Array)
#8 /var/www/vendor/twig/twig/src/Template.php(394): __TwigTemplate_cc9daf8df567d4ae67bf2135d285d5eb->doDisplay(Array, Array)
#9 /var/www/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#10 /var/www/storage/runtime/compiled_templates/2a/2ae16ac6a49343e421dce18f94ce1c77.php(106): Twig\Template->display(Array, Array)
#11 /var/www/vendor/twig/twig/src/Template.php(394): __TwigTemplate_09644bf9ea05f6710df85d085e7236f2->doDisplay(Array, Array)
#12 /var/www/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#13 /var/www/storage/runtime/compiled_templates/17/1729f9474d8ca2f134bb8a3117581972.php(57): Twig\Template->display(Array)
#14 /var/www/vendor/twig/twig/src/Template.php(394): __TwigTemplate_96f60553bdd2d98fe7d10045d36bf750->doDisplay(Array, Array)
#15 /var/www/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#16 /var/www/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#17 /var/www/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#18 /var/www/vendor/twig/twig/src/Environment.php(277): Twig\TemplateWrapper->render(Array)
#19 /var/www/vendor/craftcms/cms/src/web/View.php(388): Twig\Environment->render('_views/account/...', Array)
#20 /var/www/vendor/craftcms/cms/src/web/View.php(441): craft\web\View->renderTemplate('_views/account/...', Array)
#21 /var/www/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(52): craft\web\View->renderPageTemplate('_views/account/...', Array, 'site')
#22 /var/www/vendor/yiisoft/yii2/web/Response.php(1095): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#23 /var/www/vendor/craftcms/cms/src/web/Response.php(274): yii\web\Response->prepare()
#24 /var/www/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#25 /var/www/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#26 /var/www/web/index.php(12): yii\base\Application->run()
#27 {main}

### Craft CMS version

4.0.0-beta.3

### Craft Commerce version

4.0.0-beta.1

### PHP version

8.1.3

### Operating system and version

Linux 5.10.16.3-microsoft-standard-WSL2

### Database type and version

MySQL 10.7.3

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Redactor
- Icon Picker
- Navigation
- SEOmatic

**Comment by lukeholder** [comment]
The Countries and States service has been removed in Commerce 4, and we are yet to update that docs page.

We do explain this in the upgrade guide though: https://craftcms.com/docs/commerce/4.x/upgrading.html#countries-and-states

```twig
{% set countries = craft.commerce.countries.allEnabledCountries %}
```

is now

```twig
{% set countries = craft.commerce.getStore().store.getCountriesList() %}
```

We are still working on the detailed updates to the 4.x docs, and will ping you here once we update the Country/States pages (or give you the alternative page).

Also check out https://craftcms.com/docs/4.x/addresses.html#address-repository in the CMS docs.

Thanks
