### ISSUE TITLE
[3.x]: Email Template Not Found

### ISSUE THREAD

**Issue by mightyfineyall** [craftcms/commerce#2775]
### Description

When Craft tries to send an order confirmation or shipping confirmation, getting an error that the email isn't found. I use a custom template directory. On serverpilot, it would be srv/users/USER/apps/APP/craft/src instead of srv/users/USER/apps/APP/craft/templates. I first thought it was an issue with the queueing system (I'd installed the Craft Async Queue plugin) but it still sometimes won't send with that plugin disabled.

### Steps to reproduce

Not sure, but using Commerce with a custom template folder might be a good start?

### Expected behavior

The email templates are in the folder and linked correctly in Commerce's settings - it even finds the template when selected.

### Actual behavior

```csharp
2022-04-14 15:44:00 [-][-][-][info][craft\queue\QueueLogBehavior::beforeExec]  [10608] Sending email for order #3657 (attempt: 1, pid: 305941) - Started
2022-04-14 15:44:00 [-][-][-][error][craft\commerce\services\Emails::sendEmail] Email template does not exist at “email/admin_order.html” which resulted in “email/admin_order.html” for email “Admin Order Notification”. Order: “f57631a”.
2022-04-14 15:44:00 [-][-][-][error][craft\queue\QueueLogBehavior::afterError]  [10608] Sending email for order #3657 (attempt: 1, pid: 305941) - Error (time: 0.062s): Email template does not exist at “email/admin_order.html” which resulted in “email/admin_order.html” for email “Admin Order Notification”. Order: “f57631a”.
2022-04-14 15:44:00 [-][-][-][error][craft\commerce\errors\EmailException] craft\commerce\errors\EmailException: Email template does not exist at “email/admin_order.html” which resulted in “email/admin_order.html” for email “Admin Order Notification”. Order: “f57631a”. in /srv/users/SITE_X/apps/SITE_X/craft/vendor/craftcms/commerce/src/queue/jobs/SendEmail.php:54
Stack trace:
#0 /srv/users/SITE_X/apps/SITE_X/craft/vendor/yiisoft/yii2-queue/src/Queue.php(246): craft\commerce\queue\jobs\SendEmail->execute(Object(craft\queue\Queue))
#1 /srv/users/SITE_X/apps/SITE_X/craft/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\Queue->handleMessage('10608', 'O:35:"craft\\com...', '300', '1')
#2 /srv/users/SITE_X/apps/SITE_X/craft/vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\queue\cli\Queue->execute('10608', 'O:35:"craft\\com...', '300', '1', '305941')
#3 [internal function]: yii\queue\cli\Command->actionExec('10608', '300', '1', '305941')
#4 /srv/users/SITE_X/apps/SITE_X/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /srv/users/SITE_X/apps/SITE_X/craft/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#6 /srv/users/SITE_X/apps/SITE_X/craft/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('exec', Array)
#7 /srv/users/SITE_X/apps/SITE_X/craft/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('exec', Array)
#8 /srv/users/SITE_X/apps/SITE_X/craft/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/exec', Array)
#9 /srv/users/SITE_X/apps/SITE_X/craft/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('queue/exec', Array)
#10 /srv/users/SITE_X/apps/SITE_X/craft/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('queue/exec', Array)
#11 /srv/users/SITE_X/apps/SITE_X/craft/vendor/yiisoft/yii2/base/Application.php(384): yii\console\Application->handleRequest(Object(craft\console\Request))
#12 /srv/users/SITE_X/apps/SITE_X/craft/craft(27): yii\base\Application->run()
#13 {main}
```

### Craft CMS version

3.7.38

### Craft Commerce version

3.4.14

### PHP version

7.4.28

### Operating system and version

Linux 5.4.0-107-generic

### Database type and version

MySQL 8.0.28

### Image driver and version

GD 7.4.28

### Installed plugins and versions

```csharp
    "adigital/cookie-consent-banner": "1.2.9",
    "codemonauts/craft-instagram-feed": "1.1.7",
    "craftcms/cms": "3.7.38",
    "craftcms/commerce": "3.4.14",
    "craftcms/commerce-stripe": "2.4.3",
    "craftcms/contact-form": "2.5.0",
    "craftcms/feed-me": "4.4.3",
    "craftcms/redactor": "2.10.6",
    "craftcms/webhooks": "2.4.1",
    "hybridinteractive/craft-contact-form-extensions": "1.3.0",
    "marknotton/agent": "1.2.0",
    "nystudio107/craft-seomatic": "3.4.30",
    "nystudio107/craft-units": "1.0.4",
    "owldesign/qarr": "1.3.2",
    "sebastianlenz/linkfield": "1.0.25",
    "vaersaagod/matrixmate": "1.4.1",
    "venveo/craft-bulkedit": "2.0.6",
    "verbb/expanded-singles": "1.2.0",
    "verbb/field-manager": "2.2.4",
    "verbb/navigation": "1.4.25",
    "verbb/super-table": "2.7.1",
    "vlucas/phpdotenv": "^3.4.0",
    "whoisjuan/craft-color-mixer": "1.0.9"
```

**Comment by pdaleramirez** [comment]
@mightyfineyall This is not a bug, the email is expected templates from the site templates path. Have you set the constant config [CRAFT_TEMPLATES_PATH ](https://craftcms.com/docs/3.x/config/#craft-templates-path)? By setting that it will change the templates path on the path you specified.

**Comment by mightyfineyall** [comment]
Yes, it's set in index.php - none of my other templates would work if it wasn't. Does Commerce ignore that for some reason and still look in the templates folder?

```// Define path constants
define('CRAFT_BASE_PATH', dirname(__DIR__));
define('CRAFT_VENDOR_PATH', CRAFT_BASE_PATH . '/vendor');
define('CRAFT_TEMPLATES_PATH', '../src');```

**Comment by pdaleramirez** [comment]
@mightyfineyall The instruction is stated here https://craftcms.com/docs/3.x/config/#php-constants. We'll re-open the issue if template still can't be found.
