### ISSUE TITLE
Call to a member function getProductTypes() on null

### ISSUE THREAD

**Issue by davidhellmann** [craftcms/commerce#278]
When I open a product detail site comes this error. 

![image](https://user-images.githubusercontent.com/764292/38158198-46e6d864-3490-11e8-99d6-3fd7cfbf8abe.png)

I'm on the newest versions.

**Comment by internetztube** [comment]
```
2018-03-31 03:27:15 [90.146.206.216][271][liln068njo9pb0prb63ai6l132][error][Error] Error: Call to a member function getProductTypes() on null in /path/to/craft/vendor/craftcms/commerce/src/elements/Product.php:256
Stack trace:
#0 /path/to/craft/vendor/craftcms/commerce/src/elements/Product.php(978): craft\commerce\elements\Product->getType()
#1 /path/to/craft/vendor/craftcms/cms/src/base/Element.php(1165): craft\commerce\elements\Product->route()
#2 /path/to/craft/vendor/craftcms/cms/src/web/UrlManager.php(339): craft\base\Element->getRoute()
#3 /path/to/craft/vendor/craftcms/cms/src/web/UrlManager.php(196): craft\web\UrlManager->_getMatchedElementRoute('optical/erwin-1')
#4 /path/to/craft/vendor/charliedev/fallback-site/src/FallbackSite.php(39): craft\web\UrlManager->getMatchedElement()
#5 /path/to/craft/vendor/yiisoft/yii2/base/BaseObject.php(109): charliedev\fallbacksite\FallbackSite->init()
#6 /path/to/craft/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#7 /path/to/craft/vendor/craftcms/cms/src/base/Plugin.php(87): yii\base\Module->__construct('fallback-site', Object(craft\web\Application), Array)
#8 [internal function]: craft\base\Plugin->__construct('fallback-site', Object(craft\web\Application), Array)
#9 /path/to/craft/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#10 /path/to/craft/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('charliedev\\fall...', Array, Array)
#11 /path/to/craft/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('charliedev\\fall...', Array, Array)
#12 /path/to/craft/vendor/craftcms/cms/src/services/Plugins.php(772): yii\BaseYii::createObject(Array, Array)
#13 /path/to/craft/vendor/craftcms/cms/src/services/Plugins.php(194): craft\services\Plugins->createPlugin('fallback-site', Array)
#14 /path/to/craft/vendor/craftcms/cms/src/base/ApplicationTrait.php(1136): craft\services\Plugins->loadPlugins()
#15 /path/to/craft/vendor/craftcms/cms/src/web/Application.php(92): craft\web\Application->_init()
#16 /path/to/craft/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#17 /path/to/craft/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#18 /path/to/craft/vendor/craftcms/cms/src/web/Application.php(82): yii\base\Application->__construct(Array)
#19 [internal function]: craft\web\Application->__construct(Array)
#20 /path/to/craft/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#21 /path/to/craft/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#22 /path/to/craft/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#23 /path/to/craft/vendor/craftcms/cms/bootstrap/bootstrap.php(249): yii\BaseYii::createObject(Array)
#24 /path/to/craft/vendor/craftcms/cms/bootstrap/web.php(42): require('/home/forge/sta...')
#25 /path/to/craft/web/index.php(40): require('/home/forge/sta...')
#26 {main}
```

**Comment by lukeholder** [comment]
@davidhellmann not sure what you mean by `When I open a product detail`

On the front end? or a product edit page in the control panel?

Can you both please gives steps to reproduce. I have clicked on all product screens on both front and backend and can't seem to trigger the error.

@internetztube

**Comment by davidhellmann** [comment]
@lukeholder sorry, what a bit late yesterday. here are more Details:

It's when we try to open a Product Detail Page on the frontend side.

Here my Settings:
![image](https://user-images.githubusercontent.com/764292/38162099-b4774ddc-34db-11e8-90df-83ad89b70f3c.png)


`_product.html`:
```
{# @var craft \craft\web\twig\variables\CraftVariable #}
{# @var entry \craft\elements\Entry #}
{# -- Entry Router -- #}
{# ---------------------------------------------------------------------- #}

{% include [
  'product/' ~ productType.handle,
  'product/' ~ '/default',
  '404'
] %}
```

`product/typeHandle.html`: (in this case: `product/optical.html`:
```
{# @var craft \craft\web\twig\variables\CraftVariable #}
{# @var entry \craft\elements\Entry #}
{# -- News Entry Template -- #}
{# ---------------------------------------------------------------------- #}

{% extends "_layouts/_master.html" %}
{% set bodyClass = "p-opticalSingle" %}

{# -- App Content -- #}
{% block appContent %}
  {# -- Cache -- #}
  {% cache globally using key craft.app.request.pathInfo %}
    PRODUCT
  {% endcache %}
{% endblock %}

```

It's nothing inside the template at the moment but the error comes.

my url that I open is: `xxx.com/optical/slug-goes-here`

**Comment by davidhellmann** [comment]
My Master Layout… maybe it's also interesting. (thanks robin).

```
{# @var craft \craft\web\twig\variables\CraftVariable #}
{# @var entry \craft\elements\Entry #}
{#
  Master Layout
  ------------------------------------------------------------

  This i the basic layout. Feel free to modify
#}

<!DOCTYPE html>
<html class="" lang="{{ craft.app.locale }}">
<head>

  {# -- CHECK JS -- #}
  {% include '_partials/global/_checkJS.html' %}

  {# -- CRITICAL CSS -- #}
  {% set cacheVal = getCookie('critical-css') %}
  {% if not cacheVal or craft.app.config.general.devMode %}
    {{ setCookie('critical-css', now | date_modify("+7 days").timestamp ) }}
    {% block appInlineCSS %}
    {% endblock %}
  {% endif %}

  {# -- CSS Part -- #}
  {% include '_partials/header/_css-part.html' %}

  {# -- META -- #}
  {% include '_partials/header/_meta.html' %}

  {# -- SCRIPTS -- #}
  {% include '_partials/header/_scripts.html' %}


  {# -- Share Image -- #}
  {% if entry ?? null and entry.entryImage.one() ?? null and watermark.globalWatermark.one() ?? null %}
    {% set watermarkField = watermark.globalWatermark.one() %}

    {# -- Check if Watermark Using active -- #}
    {% if watermarkField.useWatermark %}

      {# -- Watermark Image -- #}
      {% if watermarkField.image.one() ?? null %}
        {% set watermarkImage = watermarkField.image.one() %}
        {% set watermarkWidth = watermarkField.width %}
        {% set watermarkHeight = watermarkField.height %}
        {% set watermarkOpacity = watermarkField.opacity + 0 %}
        {% set watermarkOffsetX = watermarkField.offsetXAxis %}
        {% set watermarkOffsetY = watermarkField.offsetYAxis %}

        {# -- Imager: Watermark Image -- #}
        {% set watermarkImage = craft.imager.transformImage(watermarkImage, [
          { width: watermarkWidth, height: watermarkHeight }
        ], {
          jpegQuality: 100
        }) %}

        {# -- Watermark Image URL -- #}
        {% set watermarkImageUrl = watermarkImage[0].url %}
      {% endif %}

      {# -- Image Settings -- #}
      {% set entryImage = entry.entryImage.one() %}
      {% set focalpoint = entryImage.getFocalpoint('asCss') | default('50% 50%') %}

      {# -- Facebook -- #}
      {% set entryImageFacebook = craft.imager.transformImage(entryImage, [
        { width: 1200, height: 630 }
      ], {
        jpegQuality: 100,
        mode: 'crop',
        position: focalpoint
      }) %}

      {% set entryImageFacebookUrl = entryImageFacebook[0].url %}

      {# -- Imager: Share Image -- #}
      {% set shareIamgeFacebook = craft.imager.transformImage(entryImageFacebookUrl, [
        {
          width: 1200,
          height: 630
        }], {
        jpegQuality: 100,
        mode: 'crop',
        ratio: '',
        watermark: {
          image: watermarkImageUrl,
          width: watermarkWidth,
          height: watermarkHeight,
          position: {
            right: watermarkOffsetX,
            bottom: watermarkOffsetY
          },
          opacity: watermarkOpacity
        }
      }) %}

      {% set shareIamgeFacebookUrl = shareIamgeFacebook[0].url %}

      {# -- Twitter -- #}
      {% set entryImageTwitter = craft.imager.transformImage(entryImage, [
        { width: 1120, height: 600 }
      ], {
        jpegQuality: 100,
        mode: 'crop',
        position: focalpoint
      }) %}

      {% set entryImageTwitterUrl = entryImageTwitter[0].url %}

      {# -- Imager: Share Image -- #}
      {% set shareIamgeTwitter = craft.imager.transformImage(entryImageTwitterUrl, [
        {
          width: 1120,
          height: 600
        }], {
        jpegQuality: 100,
        mode: 'crop',
        ratio: '',
        watermark: {
          image: watermarkImageUrl,
          width: watermarkWidth,
          height: watermarkHeight,
          position: {
            right: watermarkOffsetX,
            bottom: watermarkOffsetY
          },
          opacity: watermarkOpacity
        }
      }) %}

      {% set shareIamgeTwitterUrl = shareIamgeTwitter[0].url %}

      <meta property="og:image" content="{{ shareIamgeFacebookUrl }}"/>
      <meta property="og:image:type" content="image/jpeg"/>
      <meta property="og:image:width" content="1200"/>
      <meta property="og:image:height" content="630"/>

      <meta name="twitter:card" content="summary_large_image"/>
      <meta name="twitter:image" content="{{ shareIamgeTwitterUrl }}"/>
    {% elseif entry.entryImage.one() ?? null %}
      <meta property="og:image" content="{{ entry.entryImage.one().url }}"/>
      <meta property="og:image:type" content="image/jpeg"/>
      <meta property="og:image:width" content="1200"/>
      <meta property="og:image:height" content="630"/>

      <meta name="twitter:card" content="summary_large_image"/>
      <meta name="twitter:image" content="{{ entry.entryImage.one().url }}"/>
    {% endif %}
  {% endif %}

  {# -- SEO & TITLE TAG -- #}
  {% include '_partials/header/_seo.html' %}

  {# -- FAV ICON -- #}
  {% include '_partials/header/_favicons.html' %}

  {% block siteHeader %}{% endblock %}
</head>
{% minify html %}
<body id="home"
      class="{{ bodyClass is defined ? bodyClass }}  {{ craft.app.request.isLivePreview ? 'is-livePreview' }}  {{ craft.app.config.general.devMode ? 't-devMode' }}">

{# -- Preloader#}
{% include '_atoms/preloader/_template.html' only %}

<div class="o-appWrapper">
  {# -- App Header -- #}
  {% include '_organisms/appHeader/_template.html' only %}

  <div class="o-appContent">

    {% block appContent %}
      Content
    {% endblock %}
  </div>

  {# -- App Footer -- #}
  {% include '_organisms/appFooter/_template.html' with { object: entry ?? category ?? null } only %}

  {# -- fibonacci -- #}
  {% include '_molecules/fibonacci/_template.html' only %}
</div>


{# -- Grid Overlay -- #}
{% if craft.app.config.general.devMode %}
  <div class="js-toggleGrid">G</div>
  <div class="o-section  o-gridOverlay">
    <div class="o-row">
      {% for i in 1..84 %}
        <div class="o-col"></div>
      {% endfor %}
    </div>
  </div>
{% endif %}

{# -- SCRIPTS -- #}
{% include '_partials/footer/_scripts.html' only %}

</body>
{% endminify %}
<!-- Läuft, weitermachen! -->
</html>
```

**Comment by lukeholder** [comment]
```twig
{# @var craft \craft\web\twig\variables\CraftVariable #}
{# @var entry \craft\elements\Entry #}
{# -- Entry Router -- #}
{# ---------------------------------------------------------------------- #}

{% include [
  'product/' ~ productType.handle,
  'product/' ~ '/default',
  '404'
] %}
```

Where are you getting `productType` from?

**Comment by davidhellmann** [comment]
Is that not the normal behaviour like with entries and categories? 
Can u give me hint how it must look like?

But the error above exits every time also if nothing is in the template. For me it looks more like he never go into this template. `{{ dump('…') }}` does also nothing.

**Comment by lukeholder** [comment]
if you are viewing a product template it would be `product.productType.handle`

**Comment by davidhellmann** [comment]
@lukeholder ok but I think thats not the problem here.
I have tried out just this in the template:

```
{{ dd(product) }}
```

but the error is the same. Any way to find out if he goes into the right template?

**Comment by Anubarak** [comment]
We were able to "fix" the issue or at least we tracked it. 
There was another active plugin `fallback-site` that activated the `craft\web\UrlManager->getMatchedElement()` function in it's `init` function. 

`fallback-site` was the first installed plugin -> it was initialized first -> the request was routed to Craft Commerce and it's [route](https://github.com/craftcms/commerce/blob/develop/src/elements/Product.php#L978) function before the plugin was even initialized. 

```
    protected function route()
    {
        // Make sure the product type is set to have URLs for this site
        $siteId = Craft::$app->getSites()->currentSite->id;
        $productTypeSiteSettings = $this->getType()->getSiteSettings();
        if (!isset($productTypeSiteSettings[$siteId]) || !$productTypeSiteSettings[$siteId]->hasUrls) {
            return null;
        }
        return [
            'templates/render', [
                'template' => $productTypeSiteSettings[$siteId]->template,
                'variables' => [
                    'product' => $this,
                ]
            ]
        ];
    }
```

Because of that `Plugin::getInstance()` in line [256](https://github.com/craftcms/commerce/blob/develop/src/elements/Product.php#L256) returned null. The issue can be closed since the problem was another plugin
