### ISSUE TITLE
Calling unknown method: yii\console\Response::getHeaders()

### ISSUE THREAD

**Issue by internetztube** [craftcms/commerce#279]
### Steps to reproduce

1. `php craft`

### Additional info

- Craft Pro 3.0.0-RC17.1
- Newest Craft Commerce (275d59c5f11785b7cbd1ef6d718795ea41e6e2c1)

- PHP version: 7.1.15
- Database driver & version: MySQL 5.7.21

When I'm trying to execute the commandline utility I get following error.

```
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: yii\console\Response::getHeaders()'

in /path/to/craft/vendor/yiisoft/yii2/base/Component.php:300

Stack trace:
#0 /path/to/craft/vendor/craftcms/commerce/src/Plugin.php(324): yii\base\Component->__call('getHeaders', Array)
#1 /path/to/craft/vendor/craftcms/commerce/src/Plugin.php(95): craft\commerce\Plugin->_registerPoweredByHeader()
#2 /path/to/craft/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\commerce\Plugin->init()
#3 /path/to/craft/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#4 /path/to/craft/vendor/craftcms/cms/src/base/Plugin.php(87): yii\base\Module->__construct('commerce', Object(craft\console\Application), Array)
#5 [internal function]: craft\base\Plugin->__construct('commerce', Object(craft\console\Application), Array)
#6 /path/to/craft/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#7 /path/to/craft/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\commerce\\...', Array, Array)
#8 /path/to/craft/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\commerce\\...', Array, Array)
#9 /path/to/craft/vendor/craftcms/cms/src/services/Plugins.php(772): yii\BaseYii::createObject(Array, Array)
#10 /path/to/craft/vendor/craftcms/cms/src/services/Plugins.php(194): craft\services\Plugins->createPlugin('commerce', Array)
#11 /path/to/craft/vendor/craftcms/cms/src/base/ApplicationTrait.php(1136): craft\services\Plugins->loadPlugins()
#12 /path/to/craft/vendor/craftcms/cms/src/console/Application.php(59): craft\console\Application->_init()
#13 /path/to/craft/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#14 /path/to/craft/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#15 /path/to/craft/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#16 /path/to/craft/vendor/craftcms/cms/src/console/Application.php(46): yii\console\Application->__construct(Array)
#17 [internal function]: craft\console\Application->__construct(Array)
#18 /path/to/craft/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#19 /path/to/craft/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\console\\A...', Array, Array)
#20 /path/to/craft/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\console\\A...', Array, Array)
#21 /path/to/craft/vendor/craftcms/cms/bootstrap/bootstrap.php(249): yii\BaseYii::createObject(Array)
#22 /path/to/craft/vendor/craftcms/cms/bootstrap/console.php(31): require('/home/forge/sta...')
#23 /path/to/craft/craft(22): require('/home/forge/sta...')
#24 {main}
```

**Comment by lukeholder** [comment]
Thanks for reporting. `composer update` to pull in the fix.
