### ISSUE TITLE
[3.x]: Setting loadCartRedirectUrl in general config has no desired effect

### ISSUE THREAD

**Issue by terryupton** [craftcms/commerce#2810]
### Description
I am trying to redirect the customer to the cart screen after loading a cart from a link they will be sent.
However, after setting this on general.php settings, this has no desired effect and still redirects to the homepage.

### Steps to reproduce

1. Add the setting into `general.php` - `  'loadCartRedirectUrl'              => 'cart',`

### Expected behavior
Once the cart is loaded, it should go to the cart page.

### Actual behavior
It still loads the homepage (siteUrl) as per the default (null) settings.

### Craft CMS version

Craft Pro 3.7.41

### Craft Commerce version

3.4.14

### PHP version

7.4.13

### Installed plugins and versions

-

**Comment by nfourtythree** [comment]
Hi @terryupton 

Thank you for the question.

Are you using the load cart feature using links or posting via a form?

Thanks!

**Comment by terryupton** [comment]
No from the share cart (cog option) in the backend system.

**Comment by nfourtythree** [comment]
Hi @terryupton 

Could you try changing you setting to `'loadCartRedirectUrl' => \craft\helpers\UrlHelper::siteUrl('cart'),` and let me know if that works?

Feels like there could be a bug here in that the Commerce code currently expects a full URL, but that doesn't seem particularly helpful especially if you are running multiple sites.

Thanks

**Comment by terryupton** [comment]
Hey @nfourtythree - sorry I get this error;

```
Fatal error: Uncaught Error: Class 'Craft' not found in /Users/terryupton/Amasci/Websites/pcdparts.co.uk/vendor/craftcms/cms/src/helpers/UrlHelper.php:318 Stack trace: #0 /Users/terryupton/Amasci/Websites/pcdparts.co.uk/config/general.php(95): craft\helpers\UrlHelper::siteUrl('cart') #1 /Users/terryupton/Amasci/Websites/pcdparts.co.uk/vendor/craftcms/cms/src/services/Config.php(206): include('/Users/terryupt...') #2 /Users/terryupton/Amasci/Websites/pcdparts.co.uk/vendor/craftcms/cms/bootstrap/bootstrap.php(174): craft\services\Config->getConfigFromFile('general') #3 /Users/terryupton/Amasci/Websites/pcdparts.co.uk/vendor/craftcms/cms/bootstrap/web.php(51): require('/Users/terryupt...') #4 /Users/terryupton/Amasci/Websites/pcdparts.co.uk/web/index.php(11): require('/Users/terryupt...') #5 /Users/terryupton/.composer/vendor/laravel/valet/server.php(234): require('/Users/terryupt...') #6 {main} thrown in /Users/terryupton/Amasci/Websites/pcdparts.co.uk/vendor/craftcms/cms/src/helpers/UrlHelper.php on line 318
```

Do I need something additional in my config file to use the `\craft\helpers\UrlHelper`

**Comment by terryupton** [comment]
as a test over requiring a full Url as you thought could be a bug. Even if i set this:
` 'loadCartRedirectUrl'              => 'https://pcdparts.loc/cart',` - still results in the homepage loading.

**Comment by terryupton** [comment]
> Looking at the stack trace it mentions the `general` config file. Can I just check that you are putting this setting in the `commerce.php` file?

Yep! that would be it 🤦🏻‍♂️. Sorry. Thanks for picking up on that @nfourtythree
