### ISSUE TITLE
[4.x]: Discount conditions not maintainable

### ISSUE THREAD

**Issue by vandres** [craftcms/commerce#3059]
### Description

When trying to add a new discount condition, nothing happens because of a 500. I've attached the log error message.

```
2023-01-10 10:03:43 [web.ERROR] [yii\base\ErrorException:2] yii\base\ErrorException: Trying to access array offset on value of type null in /var/www/vendor/craftcms/cms/src/controllers/ConditionsController.php:38
Stack trace:
#0 /var/www/vendor/craftcms/cms/src/web/ErrorHandler.php(79): yii\base\ErrorHandler->handleError(2, 'Trying to acces...', '/var/www/vendor...', 38)
#1 /var/www/vendor/craftcms/cms/src/controllers/ConditionsController.php(38): craft\web\ErrorHandler->handleError(2, 'Trying to acces...', '/var/www/vendor...', 38)
#2 /var/www/vendor/yiisoft/yii2/base/Controller.php(176): craft\controllers\ConditionsController->beforeAction(Object(yii\base\InlineAction))
#3 /var/www/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('render', Array)
#4 /var/www/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('conditions/rend...', Array)
#5 /var/www/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('conditions/rend...', Array)
#6 /var/www/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#7 /var/www/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#8 /var/www/web/index.php(12): yii\base\Application->run()
#9 {main} {"memory":29976376,"exception":"[object] (yii\\base\\ErrorException(code: 2): Trying to access array offset on value of type null at /var/www/vendor/craftcms/cms/src/controllers/ConditionsController.php:38)"} 
2023-01-10 10:03:43 [web.INFO] [application] Request context:
$_GET = [
    'p' => 'zs/actions/conditions/render'
    'site' => 'shopDeEur'
]

$_POST = [
    'action' => 'commerce/discounts/save'
    'redirect' => '37383da4ad09da21f85bc03ba5eecc0ecea6402006e461985bd301ceb59014abcommerce/promotions/discounts'
    'name' => ''
    'description' => ''
    'allPurchasables' => '1'
    'purchasables' => [
        'craft\\commerce\\elements\\Variant' => ''
    ]
    'allCategories' => '1'
    'categories' => ''
    'categoryRelationshipType' => 'element'
    'coupons' => ''
    'couponFormat' => '######'
    'orderCondition' => [
        'class' => 'craft\\commerce\\elements\\conditions\\orders\\DiscountOrderCondition'
        'config' => '{\"elementType\":null,\"fieldContext\":\"global\"}'
        'new-rule-type' => 'craft\\commerce\\elements\\conditions\\orders\\CustomerConditionRule'
    ]
    'customerCondition' => [
        'class' => 'craft\\commerce\\elements\\conditions\\customers\\DiscountCustomerCondition'
        'config' => '{\"elementType\":null,\"fieldContext\":\"global\"}'
        'new-rule-type' => ''
    ]
    'shippingAddressCondition' => [
        'class' => 'craft\\commerce\\elements\\conditions\\addresses\\DiscountAddressCondition'
        'config' => '{\"elementType\":null,\"fieldContext\":\"global\"}'
        'new-rule-type' => ''
    ]
    'billingAddressCondition' => [
        'class' => 'craft\\commerce\\elements\\conditions\\addresses\\DiscountAddressCondition'
        'config' => '{\"elementType\":null,\"fieldContext\":\"global\"}'
        'new-rule-type' => ''
    ]
    'dateFrom' => [
        'date' => ''
        'timezone' => 'Europe/Zurich'
        'time' => ''
    ]
    'dateTo' => [
        'date' => ''
        'timezone' => 'Europe/Zurich'
        'time' => ''
    ]
    'orderConditionFormula' => ''
    'purchaseTotal' => '0'
    'purchaseQty' => '0'
    'maxPurchaseQty' => '0'
    'perUserLimit' => '0'
    'perEmailLimit' => '0'
    'totalDiscountUseLimit' => '0'
    'excludeOnSale' => ''
    'appliedTo' => 'matchingLineItems'
    'perItemDiscount' => '0'
    'percentDiscount' => '0'
    'percentageOffSubject' => 'discounted'
    'ignoreSales' => '1'
    'baseDiscount' => '0'
    'hasFreeShippingForOrder' => ''
    'hasFreeShippingForMatchingItems' => ''
    'stopProcessing' => ''
    'enabled' => '1'
]
```

### Steps to reproduce

1. open example.com/admin/commerce/promotions/discounts/new
2. try to add a condition

### Expected behavior

Conditions can be added.

### Actual behavior

Conditions cannot be added

### Craft CMS version

4.3.6.1

### Craft Commerce version

4.2.4

### PHP version

8.1

### Operating system and version

MacOS, Debian Docker

### Database type and version

MariaDB 10.5

### Image driver and version

-

### Installed plugins and versions

```
  "require": {
    "craftcms/cms": "^4.2.0.2",
    "craftcms/commerce": "^4.1.0",
    "craftcms/commerce-paypal-checkout": "dev-develop",
    "craftcms/redactor": "^3.0",
    "mmikkel/cp-field-inspect": "^1.4",
    "nystudio107/craft-retour": "^4.1",
    "nystudio107/craft-vite": "^4.0",
    "php-http/curl-client": "^2.2",
    "putyourlightson/craft-elements-panel": "^2.0",
    "putyourlightson/craft-sprig": "^2.1",
    "sebastianlenz/linkfield": "^2.1",
    "spatie/craft-ray": "^2.0",
    "spicyweb/craft-neo": "^3.2",
    "ttempleton/craft-nocache": "^3.0",
    "typesense/typesense-php": "^4.8",
    "vaersaagod/geomate": "^2.0",
    "verbb/expanded-singles": "^2.0",
    "verbb/field-manager": "^3.0",
    "verbb/tablemaker": "^4.0",
    "verbb/wishlist": "^2.0",
    "vlucas/phpdotenv": "^5.4.0"
  },
  "require-dev": {
    "deployer/deployer": "^7.0",
    "yiisoft/yii2-shell": "^2.0.3",
    "roave/security-advisories": "dev-master"
  },
```

**Comment by pdaleramirez** [comment]
@vandres The reason why it is not saving the discount, it's because the `name` value is missing. It should not throw a 500 error but redirect you back to the page with an error notice. Can you provide a screencast video on how this happened?

**Comment by vandres** [comment]
@pdaleramirez Now with name and description. Attached the video. Is this working for you like I do?

https://user-images.githubusercontent.com/1436383/213415707-67624374-b440-4276-9134-9ae74a86c0fb.mov


```
2023-01-19 10:08:55 [web.INFO] [yii\db\Connection::open] Opening DB connection: mysql:host=db2;dbname=craft;port=3306 {"memory":11251608} 
2023-01-19 10:08:55 [web.INFO] [yii\web\Session::open] Session started {"memory":15226112} 
2023-01-19 10:08:55 [web.INFO] [nystudio107\codeeditor\CodeEditor::bootstrap] CodeEditor module bootstrapped {"memory":16179168} 
2023-01-19 10:08:55 [web.WARNING] [craft\elements\db\ElementQuery::prepare] Element query executed before Craft is fully initialized. {"memory":21346808} 
2023-01-19 10:08:55 [web.INFO] [wbrowar\adminbar\AdminBar::init] Admin Bar plugin loaded {"memory":22337176} 
2023-01-19 10:08:55 [web.INFO] [mmikkel\cpfieldinspect\CpFieldInspect::init] CP Field Inspect plugin loaded {"memory":24986488} 
2023-01-19 10:08:55 [web.INFO] [nystudio107\retour\Retour::init] Retour plugin loaded {"memory":25982400} 
2023-01-19 10:08:55 [web.INFO] [nystudio107\vite\Vite::init] Vite plugin loaded {"memory":26285192} 
2023-01-19 10:08:55 [web.ERROR] [yii\base\ErrorException:2] yii\base\ErrorException: Trying to access array offset on value of type null in /var/www/vendor/craftcms/cms/src/controllers/ConditionsController.php:38
Stack trace:
#0 /var/www/vendor/craftcms/cms/src/web/ErrorHandler.php(79): yii\base\ErrorHandler->handleError(2, 'Trying to acces...', '/var/www/vendor...', 38)
#1 /var/www/vendor/craftcms/cms/src/controllers/ConditionsController.php(38): craft\web\ErrorHandler->handleError(2, 'Trying to acces...', '/var/www/vendor...', 38)
#2 /var/www/vendor/yiisoft/yii2/base/Controller.php(176): craft\controllers\ConditionsController->beforeAction(Object(yii\base\InlineAction))
#3 /var/www/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('render', Array)
#4 /var/www/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('conditions/rend...', Array)
#5 /var/www/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('conditions/rend...', Array)
#6 /var/www/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#7 /var/www/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#8 /var/www/web/index.php(12): yii\base\Application->run()
#9 {main} {"memory":29377872,"exception":"[object] (yii\\base\\ErrorException(code: 2): Trying to access array offset on value of type null at /var/www/vendor/craftcms/cms/src/controllers/ConditionsController.php:38)"} 
2023-01-19 10:08:55 [web.INFO] [application] Request context:
$_GET = [
    'p' => 'zs/actions/conditions/render'
    'site' => 'shopDeChf'
]

$_POST = [
    'action' => 'commerce/discounts/save'
    'redirect' => '37383da4ad09da21f85bc03ba5eecc0ecea6402006e461985bd301ceb59014abcommerce/promotions/discounts'
    'name' => 'Test'
    'description' => 'Test'
    'allPurchasables' => '1'
    'purchasables' => [
        'craft\\commerce\\elements\\Variant' => ''
    ]
    'allCategories' => '1'
    'categories' => ''
    'categoryRelationshipType' => 'element'
    'coupons' => ''
    'couponFormat' => '######'
    'orderCondition' => [
        'class' => 'craft\\commerce\\elements\\conditions\\orders\\DiscountOrderCondition'
        'config' => '{\"elementType\":null,\"fieldContext\":\"global\"}'
        'new-rule-type' => 'craft\\commerce\\elements\\conditions\\orders\\PaidConditionRule'
    ]
    'customerCondition' => [
        'class' => 'craft\\commerce\\elements\\conditions\\customers\\DiscountCustomerCondition'
        'config' => '{\"elementType\":null,\"fieldContext\":\"global\"}'
        'new-rule-type' => ''
    ]
    'shippingAddressCondition' => [
        'class' => 'craft\\commerce\\elements\\conditions\\addresses\\DiscountAddressCondition'
        'config' => '{\"elementType\":null,\"fieldContext\":\"global\"}'
        'new-rule-type' => ''
    ]
    'billingAddressCondition' => [
        'class' => 'craft\\commerce\\elements\\conditions\\addresses\\DiscountAddressCondition'
        'config' => '{\"elementType\":null,\"fieldContext\":\"global\"}'
        'new-rule-type' => 'craft\\elements\\conditions\\SiteConditionRule'
    ]
    'dateFrom' => [
        'date' => ''
        'timezone' => 'Europe/Zurich'
        'time' => ''
    ]
    'dateTo' => [
        'date' => ''
        'timezone' => 'Europe/Zurich'
        'time' => ''
    ]
    'orderConditionFormula' => ''
    'purchaseTotal' => '0'
    'purchaseQty' => '0'
    'maxPurchaseQty' => '0'
    'perUserLimit' => '0'
    'perEmailLimit' => '0'
    'totalDiscountUseLimit' => '0'
    'excludeOnSale' => ''
    'appliedTo' => 'matchingLineItems'
    'perItemDiscount' => '0'
    'percentDiscount' => '0'
    'percentageOffSubject' => 'discounted'
    'ignoreSales' => '1'
    'baseDiscount' => '0'
    'hasFreeShippingForOrder' => ''
    'hasFreeShippingForMatchingItems' => ''
    'stopProcessing' => ''
    'enabled' => '1'
]
```

**Comment by pdaleramirez** [comment]
@vandres I am not able to replicate this issue. Could you send your database and composer.json along with composer.lock files in support@craftcms.com? We'll debug further.

**Comment by vandres** [comment]
> @vandres I am not able to replicate this issue. Could you send your database and composer.json along with composer.lock files in [support@craftcms.com](mailto:support@craftcms.com)? We'll debug further.

With that reply I tested again with all plugins and custom code disabled. Now it works. So I will investigate here first. Thanks for your time!

**Comment by vandres** [comment]
@pdaleramirez After some digging around, I was able to pinpoint the problem. In our AssetBundle we load "htmx.min.js". If I remove that line, the discounts are working again. We need HTMX in the CP, but I created a workaround to include the file only in the templates we need it in.

```
class AssetBundle extends BaseAssetBundle
{
    public function init() {
        $this->sourcePath = '@webroot/static';

        $this->depends = [
            CpAsset::class,
        ];

        $this->js = [
            'js/htmx.min.js',
            'js/admin.js',
        ];

        $this->css = [
            'css/admin.css',
        ];

        parent::init();
    }
}
```

**Comment by pdaleramirez** [comment]
@vandres Glad that you resolved it.
