### ISSUE TITLE
[2.x/3.x]: m181206_120000_remaining_project_config_support fails if order field layout has tabs

### ISSUE THREAD

**Issue by msbit** [craftcms/commerce#3154]
### What happened?

I'm attempting to upgrade my Craft + Commerce install to 3.8.8 + 3.4.20.1, but I can't go directly there due to:

```
Exception 'yii\web\HttpException' with message 'You need to be on at least Craft Commerce 2.2.18 before you can update to Craft Commerce 3.4.20.1.'
```

So, I'm attempting an intermediate upgrade to 2.2.27, and have found that `m181206_120000_remaining_project_config_support` fails with:

```
*** applying m181206_120000_remaining_project_config_support
Exception: Invalid layout ID: 15 (/private/var/folders/3m/ghr2lt194vxbc0nhsm6357200000gn/T/tmp.3itpJO8R/vendor/craftcms/cms/src/models/FieldLayoutTab.php:215)
#0 /private/var/folders/3m/ghr2lt194vxbc0nhsm6357200000gn/T/tmp.3itpJO8R/vendor/craftcms/cms/src/models/FieldLayoutTab.php(244): craft\models\FieldLayoutTab->getLayout()
#1 /private/var/folders/3m/ghr2lt194vxbc0nhsm6357200000gn/T/tmp.3itpJO8R/vendor/craftcms/cms/src/models/FieldLayoutTab.php(125): craft\models\FieldLayoutTab->getFields()
#2 /private/var/folders/3m/ghr2lt194vxbc0nhsm6357200000gn/T/tmp.3itpJO8R/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\models\FieldLayoutTab->init()
#3 /private/var/folders/3m/ghr2lt194vxbc0nhsm6357200000gn/T/tmp.3itpJO8R/vendor/craftcms/cms/src/services/Fields.php(1247): yii\base\BaseObject->__construct(Array)
#4 /private/var/folders/3m/ghr2lt194vxbc0nhsm6357200000gn/T/tmp.3itpJO8R/vendor/craftcms/cms/src/services/Fields.php(1230): craft\services\Fields->_createLayoutTabFromRow(Array, true)
#5 [internal function]: craft\services\Fields->craft\services\{closure}(Array)
#6 /private/var/folders/3m/ghr2lt194vxbc0nhsm6357200000gn/T/tmp.3itpJO8R/vendor/craftcms/cms/src/services/Fields.php(1229): array_map(Object(Closure), Array)
#7 /private/var/folders/3m/ghr2lt194vxbc0nhsm6357200000gn/T/tmp.3itpJO8R/vendor/craftcms/cms/src/models/FieldLayout.php(252): craft\services\Fields->getLayoutTabsById(15)
#8 /private/var/folders/3m/ghr2lt194vxbc0nhsm6357200000gn/T/tmp.3itpJO8R/vendor/craftcms/cms/src/models/FieldLayout.php(442): craft\models\FieldLayout->getTabs()
#9 /private/var/folders/3m/ghr2lt194vxbc0nhsm6357200000gn/T/tmp.3itpJO8R/vendor/craftcms/commerce/src/migrations/m181206_120000_remaining_project_config_support.php(43): craft\models\FieldLayout->getConfig()
#10 /private/var/folders/3m/ghr2lt194vxbc0nhsm6357200000gn/T/tmp.3itpJO8R/vendor/craftcms/cms/src/db/Migration.php(53): craft\commerce\migrations\m181206_120000_remaining_project_config_support->safeUp()
#11 /private/var/folders/3m/ghr2lt194vxbc0nhsm6357200000gn/T/tmp.3itpJO8R/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#12 /private/var/folders/3m/ghr2lt194vxbc0nhsm6357200000gn/T/tmp.3itpJO8R/vendor/craftcms/cms/src/console/controllers/MigrateController.php(386): yii\console\controllers\BaseMigrateController->migrateUp('m181206_120000_...')
#13 [internal function]: craft\console\controllers\MigrateController->actionAll()
#14 /private/var/folders/3m/ghr2lt194vxbc0nhsm6357200000gn/T/tmp.3itpJO8R/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /private/var/folders/3m/ghr2lt194vxbc0nhsm6357200000gn/T/tmp.3itpJO8R/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#16 /private/var/folders/3m/ghr2lt194vxbc0nhsm6357200000gn/T/tmp.3itpJO8R/vendor/yiisoft/yii2/console/Controller.php(182): yii\base\Controller->runAction('all', Array)
#17 /private/var/folders/3m/ghr2lt194vxbc0nhsm6357200000gn/T/tmp.3itpJO8R/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('all', Array)
#18 /private/var/folders/3m/ghr2lt194vxbc0nhsm6357200000gn/T/tmp.3itpJO8R/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#19 /private/var/folders/3m/ghr2lt194vxbc0nhsm6357200000gn/T/tmp.3itpJO8R/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('migrate/all', Array)
#20 /private/var/folders/3m/ghr2lt194vxbc0nhsm6357200000gn/T/tmp.3itpJO8R/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#21 /private/var/folders/3m/ghr2lt194vxbc0nhsm6357200000gn/T/tmp.3itpJO8R/vendor/craftcms/cms/src/console/Application.php(118): yii\console\Application->handleRequest(Object(craft\console\Request))
#22 /private/var/folders/3m/ghr2lt194vxbc0nhsm6357200000gn/T/tmp.3itpJO8R/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#23 /private/var/folders/3m/ghr2lt194vxbc0nhsm6357200000gn/T/tmp.3itpJO8R/craft(13): yii\base\Application->run()
#24 {main}
*** failed to apply m181206_120000_remaining_project_config_support (time: 0.020s)
```

I've determined that this is due to our order field layout having tabs, attached is a reproduction with a database dump and a script.

Next steps?

EDIT:

You'll need to set the appropriate variables at the start of the `run.sh` script to match a database to overwrite as part of the setup process.

[reproduction.zip](https://github.com/craftcms/commerce/files/11344785/reproduction.zip)

### Craft CMS version

3.8.8

### Craft Commerce version

2.2.27

### Installed plugins and versions

-

**Comment by pdaleramirez** [comment]
@msbit This may be a bug, but we no longer provide bug fixes for Commerce 2, https://craftcms.com/knowledge-base/supported-versions.  I suggest removing the order field layout before upgrading to fix the migration issue.

**Comment by msbit** [comment]
Hey @pdaleramirez, thanks for checking it out. Not surprising that it's fallen out of support, but oh well.

For anyone else experiencing the same issue (`Exception: Invalid layout ID: xxx`), you can do the following:

* Start with Craft 3.7.39
  * `wget --quiet https://download.craftcms.com/craft/3.7/Craft-3.7.39.zip`
  * `unzip -oq Craft-3.7.39.zip`
  * Configure `.env`
  * `php craft migrate/all --interactive 0 --no-backup 1`
* Install Commerce 2 max (currently 2.2.27)
  * `composer require craftcms/commerce:2.2.27`
  * `php craft plugin/install commerce`
  * `php craft migrate/all --interactive 0 --no-backup 1`
* Update Craft to 3 max (currently 3.8.8)
  * `composer require --with-all-dependencies craftcms/cms:3.8.8`
  * `php craft migrate/all --interactive 0 --no-backup 1`
* Update Commerce to 3 max (currently 3.4.20.1)
  * `composer require --with-all-dependencies craftcms/commerce:3.4.20.1`
  * `php craft migrate/all --interactive 0 --no-backup 1`

The issue is migration rot in `m181206_120000_remaining_project_config_support` due to the a change in 3.7.40 (probably https://github.com/craftcms/cms/commit/6360d81ff0bef0c8e2ecb013764097c571d4a222 given the cause of the error) ✌️

**Comment by vacoo** [comment]
@msbit It works. Thanks!
