### ISSUE TITLE
[4.x]: User group conditions - should migrate to the new condition builder, no obvious warnings shown

### ISSUE THREAD

**Issue by bossanova808** [craftcms/commerce#3176]
### What happened?

I think user group conditions on discounts should not just be silently dropped during a Commerce 3 -> 4 migration, but a condition should be created in the condition builder:

![image](https://github.com/craftcms/commerce/assets/731309/5ef302dd-897d-4be6-b73c-eb16fb119114)

To:

![image](https://github.com/craftcms/commerce/assets/731309/607a3e73-e754-42be-a51d-2206ce0210bb)

If this is too difficult to implement then at the very least there should be clear warnings raised during the migration, and this should be noted in the upgrade documentation.

This is very important and should be solved as a priority - discounts very quickly have significant financial implications and with the current migration, the conditions are stripped with no warning, meaning these discounts then apply to all users, which is of course very much not correct...

### Craft CMS version

4

### Craft Commerce version

4

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
If it's not being migrated to the conditioner, then that's a bug as it should be migrated to condition builder. I will look into it. We wouldn't drop it silently on purpose.

**Comment by bossanova808** [comment]
Thanks Luke.

They weren't for me on my last test migration.  Am planning on doing a new test migration early next week, so can report back then again.

**Comment by pdaleramirez** [comment]
I have managed to fix this bug. You can track the PR #3177

**Comment by bossanova808** [comment]
Great & many thanks - will hopefully have time tomorrow for the next test migration, so good timing.

**Comment by nfourtythree** [comment]
Version `4.2.10` of Commerce is now out with this fix.

Thanks!

**Comment by bossanova808** [comment]
Unfortunately, this does not work & breaks my migration

```
*** applying m220304_094835_discount_conditions
    > update in {{%commerce_discounts}} ... done (time: 0.007s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.001s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.001s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.001s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
    > update in {{%commerce_discounts}} ... done (time: 0.000s)
Exception: craft\services\UserGroups::getGroupById(): Argument #1 ($groupId) must be of type int, null given, called in /var/www/html/vendor/craftcms/commerce/src/migrations/m220304_094835_discount_conditions.php on line 121 (/var/www/html/vendor/craftcms/cms/src/services/UserGroups.php:120)
#0 /var/www/html/vendor/craftcms/commerce/src/migrations/m220304_094835_discount_conditions.php(121): craft\services\UserGroups->getGroupById(NULL)
#1 [internal function]: craft\commerce\migrations\m220304_094835_discount_conditions->craft\commerce\migrations\{closure}(NULL)
#2 /var/www/html/vendor/craftcms/commerce/src/migrations/m220304_094835_discount_conditions.php(120): array_map(Object(Closure), Array)
#3 /var/www/html/vendor/craftcms/commerce/src/migrations/m220304_094835_discount_conditions.php(55): craft\commerce\migrations\m220304_094835_discount_conditions->_getGroupUids(Array)
#4 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(49): craft\commerce\migrations\m220304_094835_discount_conditions->safeUp()
#5 /var/www/html/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#6 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(358): yii\console\controllers\BaseMigrateController->migrateUp('m220304_094835_...')
#7 [internal function]: craft\console\controllers\MigrateController->actionAll()
#8 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#11 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(87): yii\console\Controller->runAction('all', Array)
#12 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
#13 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#14 /var/www/html/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('migrate/all', Array)
#15 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction('migrate/all', Array)
#16 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(208): yii\base\Controller->run('migrate/all', Array)
#17 /var/www/html/vendor/craftcms/cms/src/console/controllers/UpController.php(57): craft\console\Controller->run('migrate/all', Array)
#18 [internal function]: craft\console\controllers\UpController->actionIndex()
#19 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#21 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('', Array)
#22 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(87): yii\console\Controller->runAction('', Array)
#23 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(217): craft\console\Controller->traitRunAction('', Array)
#24 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('', Array)
#25 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('up', Array)
#26 /var/www/html/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('up', Array)
#27 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('up', Array)
#28 /var/www/html/vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest(Object(craft\console\Request))
#29 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#30 /var/www/html/craft(13): yii\base\Application->run()
#31 {main}
*** failed to apply m220304_094835_discount_conditions (time: 0.050s)


50 from 65 migrations were applied.

Migration failed. The rest of the migrations are canceled.

Aborting remaining tasks.
Failed to run craft up: exit status 1
```

**Comment by bossanova808** [comment]
I'll shoot you folks the DB via email.

**Comment by lukeholder** [comment]
@bossanova808 

Thanks for reporting. This is fixed now for the next release. I have upgraded your database successfully and see the "user groups" rule containing the correct groups previously specified in the discount condition.

The fix will be in the next release, but to get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "dev-develop#836eff8e6fc302d2f624465cda3232402a4b13ac as 4.2.10",
  "...": "..."
}
```

Thanks,

**Comment by bossanova808** [comment]
Just confirming this has worked perfectly now in my latest test migration - many thanks!
