### ISSUE TITLE
On payment submission: Trying to get property of non-object

### ISSUE THREAD

**Issue by bryantAXS** [craftcms/commerce#318]
### Description

On payment submission of a logged in user: Trying to get property of non-object

```
yii\base\ErrorException: Trying to get property of non-object in /home/vagrant/Code/clients/safebonesco/website-craft3/vendor/craftcms/commerce/src/services/Payments.php:209
Stack trace:
#0 /home/vagrant/Code/clients/safebonesco/website-craft3/vendor/craftcms/commerce/src/controllers/PaymentsController.php(288): craft\commerce\services\Payments->processPayment()
#1 /home/vagrant/Code/clients/safebonesco/website-craft3/vendor/yiisoft/yii2/base/InlineAction.php(57): craft\commerce\controllers\PaymentsController->actionPay()
...
```

### Steps to reproduce

1. Logged in user
2. savePaymentType = true
3. gatewayId set inside payment form

### Additional info

- Craft version: 3
- PHP version: 7.1 
- Database driver & version: MariaDB
- Plugins & versions:

**Comment by andris-sevcenko** [comment]
Should be fixed with 5800805
