### ISSUE TITLE
[4.x]: Issue saving variant products

### ISSUE THREAD

**Issue by bossanova808** [craftcms/commerce#3383]
### Description

Save a particular product type, with variants, changing e.g. the price, I am seeing:

```
TypeError: strtolower(): Argument #1 ($string) must be of type string, array given in /var/www/html/vendor/craftcms/cms/src/fields/BaseOptionsField.php:326
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/fields/BaseOptionsField.php(326): strtolower(Array)
#1 /var/www/html/vendor/craftcms/cms/src/base/Field.php(500): craft\fields\BaseOptionsField->normalizeValue(Array, Object(craft\commerce\elements\Product))
#2 /var/www/html/vendor/craftcms/cms/src/base/Element.php(4215): craft\base\Field->normalizeValueFromRequest(Array, Object(craft\commerce\elements\Product))
#3 /var/www/html/vendor/craftcms/cms/src/base/Element.php(4418): craft\base\Element->setFieldValueFromRequest('compatibleInks', Array)
#4 /var/www/html/vendor/craftcms/commerce/src/helpers/Product.php(141): craft\base\Element->setFieldValuesFromRequest('fields')
#5 /var/www/html/vendor/craftcms/commerce/src/controllers/ProductsController.php(296): craft\commerce\helpers\Product::populateProductFromPost(Object(craft\commerce\elements\Product), Object(craft\web\Request))
#6 [internal function]: craft\commerce\controllers\ProductsController->actionSaveProduct(false)
#7 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('save-product', Array)
#10 /var/www/html/vendor/craftcms/cms/src/web/Application.php(305): yii\base\Module->runAction('commerce/produc...', Array)
#11 /var/www/html/vendor/craftcms/cms/src/web/Application.php(606): craft\web\Application->runAction('commerce/produc...', Array)
#12 /var/www/html/vendor/craftcms/cms/src/web/Application.php(284): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#13 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#14 /var/www/html/web/index.php(12): yii\base\Application->run()
#15 {main}
```

Post data example:

```
$_POST = [
    'action' => 'commerce/products/save-product',
    'typeId' => '5',
    'productId' => '5255',
    'redirect' => 'cd6007348f6b0b44d4827014b9dce1ce83a75466b7816a49bbf74cba33430286commerce/products/inkjetPaper/{id}-{slug}',
    'title' => 'Epson Archival Matte 189gsm',
    'fields' => [
        'availability' => 'base64:YXZhaWxhYmxl',
        'eta' => '__blank__',
        'etaMonth' => '__blank__',
        'dateDiscontinued' => [
            'date' => '',
            'locale' => 'en-AU',
            'timezone' => 'Australia/Melbourne',
        ],
        'recommendInstead' => '',
        'productNote' => '',
        'categories' => [
            '174',
            '602',
            '1340',
        ],
        'brand' => [
            '684',
        ],
        'oneLineDescription' => 'An excellent matte paper for proofing purposes.',
        'fullDescription' => '<p>Fine Art Papers are beautiful, but expensive. Sometimes during the image development process, it is very handy to have a cheaper paper for proofing purposes.</p>
<p>The best we have found of these is Epson Archival Matte. This paper is in no way archival, despite its name, but it is an excellent proofing paper with a very good colour gamut, and very strong blacks.</p>
<p>This paper is completely matte, has a very smooth bright white surface (contains optical brighteners) and is 192gsm. Unusually, the rear side of the paper is a rather unattractive greyish white tone (but who cares - it\'s just a cheap proofing paper!).</p>
<p>We suggest printing your proofs with a custom profile made at 720 PPI, and still doing at least one final proof on your final output media before you make your final prints. When you are custom profiled for both papers, it\'s a very good match for better matte rag papers like Photo Rag overall, although it does contain significant optical brighteners making the whites more blue.</p>',
        'warranty' => '',
        'customerFeedback' => '',
        'specificationsUrl' => [
            'type' => 'url',
            'value' => '',
        ],
        'availableInSamplePack' => '',
        'compatibleInks' => [
            'base64:UGlnbWVudCBJbmtzICh1c2UgbWF0dGUgYmxhY2sp',
            'base64:RHllIEJhc2VkIElua3M=',
        ],
        'surfaceTexture' => [
            '174',
            '602',
        ],
        'construction' => 'base64:RmlicmUgQmFzZWQ=',
        'paperSubstrate' => 'base64:V29vZCBQdWxw',
        'coating' => 'base64:TWljcm9wb3JvdXM=',
        'paperWeight' => [
            'locale' => 'en-AU',
            'value' => '189',
        ],
        'thickness' => '',
        'acidFree' => '',
        'opticalBrightenerContent' => 'base64:WWVz',
        'paperWhiteTone' => 'base64:QnJpZ2h0IFdoaXRl',
        'whiteLevel' => '',
        'allowZoom' => '1',
        'masterImage' => [
            '5246',
        ],
        'productImages' => [
            '5245',
        ],
        'familyMembers' => [
            '5249',
        ],
        'accessories' => '',
        'productVideosV2' => '',
        'relatedArticles' => '',
        'relatedLinksV2' => [
            [
                'type' => 'verbb\\hyper\\links\\Url',
                'handle' => 'default-verbb-hyper-links-url',
                'newWindow' => 'true',
                'linkValue' => 'http://tech.epson.com.au/downloads/icc.asp?downloadtype=icc',
                'linkText' => 'Epson ICC Profiles',
                'fields' => [
                    'linkDescription' => 'Epson\'s ICC profile download page',
                ],
                'id' => 'sthhiujlvg',
            ],
        ],
        'relatedFiles' => '',
        'autoResponder' => '',
        'promotionCategories' => '',
    ],
    'variants' => [
        5257 => [
            'enabled' => '1',
            'isDefault' => '1',
            'sku' => 'PEAM_C13S041342',
            'price' => '36',
            'hasUnlimitedStock' => '1',
            'minQty' => '',
            'maxQty' => '',
            'length' => '0',
            'width' => '0',
            'height' => '0',
            'weight' => '0',
            'fields' => [
                'paperSize' => [
                    '777',
                ],
                'mpn' => 'S041342',
                'variantStatus' => '1',
                'availability' => 'base64:YXZhaWxhYmxl',
                'eta' => '__blank__',
                'etaMonth' => '__blank__',
                'productNote' => '',
                'showDiscount' => 'base64:Tm8=',
                'imageScienceStandardPrice' => [
                    'locale' => 'en-AU',
                    'value' => '0.00',
                ],
                'rrp' => [
                    'locale' => 'en-AU',
                    'value' => '0.00',
                ],
                'specificAccessories' => '',
            ],
        ],
        5258 => [
            'enabled' => '1',
            'isDefault' => '',
            'sku' => 'PEAM_C13S041344',
            'price' => '80',
            'hasUnlimitedStock' => '1',
            'minQty' => '',
            'maxQty' => '',
            'length' => '0',
            'width' => '0',
            'height' => '0',
            'weight' => '0',
            'fields' => [
                'paperSize' => [
                    '782',
                ],
                'mpn' => 'S041344',
                'variantStatus' => '1',
                'availability' => 'base64:YXZhaWxhYmxl',
                'eta' => '__blank__',
                'etaMonth' => '__blank__',
                'productNote' => '',
                'showDiscount' => 'base64:Tm8=',
                'imageScienceStandardPrice' => [
                    'locale' => 'en-AU',
                    'value' => '0.00',
                ],
                'rrp' => [
                    'locale' => 'en-AU',
                    'value' => '0.00',
                ],
                'specificAccessories' => '',
            ],
        ],
        5259 => [
            'enabled' => '1',
            'isDefault' => '',
            'sku' => 'PEAM_S041340',
            'price' => '102',
            'hasUnlimitedStock' => '1',
            'minQty' => '',
            'maxQty' => '',
            'length' => '0',
            'width' => '0',
            'height' => '0',
            'weight' => '0',
            'fields' => [
                'paperSize' => [
                    '786',
                ],
                'mpn' => 'S041340',
                'variantStatus' => '1',
                'availability' => 'base64:YXZhaWxhYmxl',
                'eta' => '__blank__',
                'etaMonth' => '__blank__',
                'productNote' => '',
                'showDiscount' => 'base64:Tm8=',
                'imageScienceStandardPrice' => [
                    'locale' => 'en-AU',
                    'value' => '0.00',
                ],
                'rrp' => [
                    'locale' => 'en-AU',
                    'value' => '0.00',
                ],
                'specificAccessories' => '',
            ],
        ],
    ],
    'slug' => 'epson-archival-matte-189gsm',
    'postDate' => [
        'date' => '7/12/2015',
        'locale' => 'en-AU',
        'timezone' => 'Australia/Melbourne',
        'time' => '12:00 pm',
    ],
    'expiryDate' => [
        'date' => '',
        'locale' => 'en-AU',
        'timezone' => 'Australia/Melbourne',
        'time' => '',
    ],
    'enabled' => '1',
    'freeShipping' => '',
    'promotable' => '1',
    'availableForPurchase' => '1',
    'taxCategoryId' => '1',
    'shippingCategoryId' => '1',
];


```

### Expected behavior

No crashy

### Actual behavior

Crashy

### Craft CMS version

4.7.2

### Craft Commerce version

4.4.1.1

### PHP version

8.2.15

### Operating system and version

Ubuntu 22.04 (Forge)

### Database type and version

MySQL 8.0.35

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-
![image](https://github.com/craftcms/commerce/assets/731309/69eaf23f-2c3f-4e3b-b9ef-c935ed8c7613)

**Comment by bossanova808** [comment]
The field it is apparently having trouble with has data:

![image](https://github.com/craftcms/commerce/assets/731309/9872388e-9723-4d2f-bff7-5e62c3d3fe7e)

And certainly not long ago these were saving just fine...but at a quick glance can't immediately see anything on the Craft/Commerce changelogs of relevance to this

**Comment by bossanova808** [comment]
Just to add if it wasn't obvious - not being able to save products (i.e. change prices) is of course a major issue for a store, so it would be great and much appreciated to get some quick attention here.

**Comment by bossanova808** [comment]
This is fixed by https://github.com/craftcms/cms/issues/14326 - thanks!

(But...pretty surprised that you folks, at this stage, don't have basic functional regression testing in place - e.g. checking all basic fields & entries with such can be saved - as part of your pre-deployment practices...)
