### ISSUE TITLE
Can't upload files during commerce/payments/pay action

### ISSUE THREAD

**Issue by davist11** [craftcms/commerce#355]
### Description
We have an assets field on orders named `purchaseOrder`. When you include a file in that input field and submit the payment form, you get the following error: `filesize(): stat failed for /path/to/temp/file`

Here is what the template looks like:

```
<form method="post" enctype="multipart/form-data">
	<input type="hidden" name="action" value="commerce/payments/pay">
	{{ redirectInput('/account/orders/{number}') }}
	{{ csrfInput() }}
	<input type="hidden" name="cancelUrl" value="{{ '/checkout/payment' | hash }}">
	<input type="hidden" name="orderEmail" value="{{ cart.email }}">
	<input type="hidden" name="gatewayId" value="2">

	<fieldset>
		<div class="file-upload mb--small" data-module="FileUpload">
			<input type="file" name="fields[purchaseOrder]" id="purchase-order-pdf" required>
			<label for="purchase-order-pdf">
				{{ macros.icon('upload') }}
				<span>Purchase Order PDF</span>
			</label>
		</div>

		<button class="button" type="submit" hidden>Pay {{ cart.totalPrice | commerceCurrency(cart.paymentCurrency,convert=true) }} Now</button>
	</fieldset>
</form>
```

Note: `gatewayId == 2` is a manual gateway

### Steps to reproduce

1. Add an asset field to orders
2. Upload a file to that field and submit the payment form

### Additional info

- Craft version: Craft Pro 3.0.9
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38
- Plugins & versions:

<table class="data fullwidth fixed-layout">
        <tbody>
                            <tr>
                    <th class="light">Algolia</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Amazon S3</th>
                    <td>1.0.8</td>
                </tr>
                            <tr>
                    <th class="light">Asset Rev</th>
                    <td>6.0.0</td>
                </tr>
                            <tr>
                    <th class="light">AsyncQueue</th>
                    <td>1.3.2</td>
                </tr>
                            <tr>
                    <th class="light">Automatic Site Switch</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Calendar</th>
                    <td>2.0.1</td>
                </tr>
                            <tr>
                    <th class="light">Certificates</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Converge</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Craft Commerce</th>
                    <td>dev-master</td>
                </tr>
                            <tr>
                    <th class="light">Environment Label</th>
                    <td>3.1.3</td>
                </tr>
                            <tr>
                    <th class="light">Field Manager</th>
                    <td>2.0.2</td>
                </tr>
                            <tr>
                    <th class="light">Flat Categories</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Forms</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Freeform Pro</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Geo Cookie</th>
                    <td>1.1.2</td>
                </tr>
                            <tr>
                    <th class="light">Hamilton Utility</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Importer</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Inlin</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Inventory</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Redactor</th>
                    <td>2.1.0</td>
                </tr>
                            <tr>
                    <th class="light">Sidebar Toggle</th>
                    <td>2.0.0</td>
                </tr>
                            <tr>
                    <th class="light">SimpleSentry</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Super Table</th>
                    <td>2.0.7</td>
                </tr>
                            <tr>
                    <th class="light">Taxes</th>
                    <td>1.0.0</td>
                </tr>
                            <tr>
                    <th class="light">Twig Perversion</th>
                    <td>2.0.3</td>
                </tr>
                    </tbody>
    </table>

**Comment by lukeholder** [comment]
Can you confirm the file upload works on cart update though?

Error seems related to filename ?

https://stackoverflow.com/questions/34481697/filesize-stat-failed-for-specific-path-php

**Comment by davist11** [comment]
It looks like the file is being uploaded correctly into Craft. I confirmed that the update cart works as well.

Here's a screencast: https://drive.google.com/file/d/1MwZtYhOD1ud2T810W6-f9uLgyGBr9Rud/view?usp=sharing

Let me know what other information I can provide

**Comment by lukeholder** [comment]
Can you test with the *just* released beta.5 thanks. Think it might be fixed with a custom field fix we made.

**Comment by davist11** [comment]
I'm still having the same issue when submitting a file in the `commerce/payments/pay` action

**Comment by efatsi** [comment]
Can resolve this locally by checking the existence of the file before calling `filesize`:
Changing lines https://github.com/craftcms/cms/blob/852829b/src/fields/Assets.php?utf8=%E2%9C%93#L253-L255 to:
```php
if (file_exists($file['location']) && (filesize($file['location']) > $maxSize)) {
    $filenames[] = $file['filename'];
}
```

**Comment by efatsi** [comment]
For reference, here's the full backtrace:
```
ErrorException: filesize(): stat failed for /Applications/MAMP/tmp/php/phpR613C4
#24 /Users/efatsi/Desktop/Projects/hamilton/vendor/craftcms/cms/src/fields/Assets.php(253): handleError
#23 /Users/efatsi/Desktop/Projects/hamilton/plugins/simplesentry/src/vendor/sentry/sentry/lib/Raven/ErrorHandler.php(0): filesize
#22 /Users/efatsi/Desktop/Projects/hamilton/vendor/craftcms/cms/src/fields/Assets.php(253): validateFileSize
#21 /Users/efatsi/Desktop/Projects/hamilton/vendor/craftcms/cms/src/base/Element.php(1030): validateCustomFieldAttribute
#20 /Users/efatsi/Desktop/Projects/hamilton/vendor/craftcms/cms/src/base/Element.php(0): call_user_func
#19 /Users/efatsi/Desktop/Projects/hamilton/vendor/yiisoft/yii2/validators/InlineValidator.php(72): validateAttribute
#18 /Users/efatsi/Desktop/Projects/hamilton/vendor/yiisoft/yii2/validators/Validator.php(267): validateAttributes
#17 /Users/efatsi/Desktop/Projects/hamilton/vendor/yiisoft/yii2/base/Model.php(367): validate
#16 /Users/efatsi/Desktop/Projects/hamilton/vendor/craftcms/cms/src/services/Elements.php(377): saveElement
#15 /Users/efatsi/Desktop/Projects/hamilton/vendor/craftcms/commerce/src/elements/Order.php(481): updateOrderPaidTotal
#14 /Users/efatsi/Desktop/Projects/hamilton/vendor/craftcms/commerce/src/services/Transactions.php(390): saveTransaction
#13 /Users/efatsi/Desktop/Projects/hamilton/vendor/craftcms/commerce/src/services/Payments.php(575): _saveTransaction
#12 /Users/efatsi/Desktop/Projects/hamilton/vendor/craftcms/commerce/src/services/Payments.php(603): _updateTransaction
#11 /Users/efatsi/Desktop/Projects/hamilton/vendor/craftcms/commerce/src/services/Payments.php(234): processPayment
#10 /Users/efatsi/Desktop/Projects/hamilton/vendor/craftcms/commerce/src/controllers/PaymentsController.php(288): actionPay
#9 /Users/efatsi/Desktop/Projects/hamilton/vendor/craftcms/commerce/src/controllers/PaymentsController.php(0): call_user_func_array
#8 /Users/efatsi/Desktop/Projects/hamilton/vendor/yiisoft/yii2/base/InlineAction.php(57): runWithParams
#7 /Users/efatsi/Desktop/Projects/hamilton/vendor/yiisoft/yii2/base/Controller.php(157): runAction
#6 /Users/efatsi/Desktop/Projects/hamilton/vendor/craftcms/cms/src/web/Controller.php(76): runAction
#5 /Users/efatsi/Desktop/Projects/hamilton/vendor/yiisoft/yii2/base/Module.php(528): runAction
#4 /Users/efatsi/Desktop/Projects/hamilton/vendor/craftcms/cms/src/web/Application.php(273): runAction
#3 /Users/efatsi/Desktop/Projects/hamilton/vendor/craftcms/cms/src/web/Application.php(521): _processActionRequest
#2 /Users/efatsi/Desktop/Projects/hamilton/vendor/craftcms/cms/src/web/Application.php(257): handleRequest
#1 /Users/efatsi/Desktop/Projects/hamilton/vendor/yiisoft/yii2/base/Application.php(386): run
#0 index.php(39): null
```

Looks like this boils down to an Asset validation falling down

**Comment by lukeholder** [comment]
@efatsi can you lodge a ticket in the craftcms/cms repo and reference this ticket?
