### ISSUE TITLE
[4.x]: Could not duplicate elements due to validation errors

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/commerce#3753]
### Description

I'm trying to duplicate a complete order, using the element index in the Commernce control panel. When I click duplicate, a toast error notification appears:

> Could not duplicate elements due to validation errors.

I've removed all custom code/modules but the error keeps displaying.

I have many custom fields attached to the order, some of which are set to required.

I wrote a console command hoping to troubleshoot the problem that allowed me to duplicate an order based on ID. 

It returned the following stack trace which seems to point at the address query in CraftCMS;

```
Exception 'yii\base\InvalidConfigException' with message ''

in /var/www/html/craft/vendor/craftcms/cms/src/elements/db/AddressQuery.php:303

Stack trace:
#0 /var/www/html/craft/vendor/craftcms/cms/src/elements/db/AddressQuery.php(238): craft\elements\db\AddressQuery->_normalizeOwnerId()
#1 /var/www/html/craft/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1444): craft\elements\db\AddressQuery->beforePrepare()
#2 /var/www/html/craft/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#3 /var/www/html/craft/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\AddressQuery))
#4 /var/www/html/craft/vendor/yiisoft/yii2/db/Query.php(287): yii\db\Query->createCommand(Object(craft\db\Connection))
#5 /var/www/html/craft/vendor/craftcms/cms/src/db/Query.php(280): yii\db\Query->one(NULL)
#6 /var/www/html/craft/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1672): craft\db\Query->one(NULL)
#7 /var/www/html/craft/vendor/craftcms/commerce/src/elements/Order.php(3003): craft\elements\db\ElementQuery->one()
#8 /var/www/html/craft/vendor/yiisoft/yii2/base/Component.php(139): craft\commerce\elements\Order->getBillingAddress()
#9 /var/www/html/craft/vendor/craftcms/cms/src/base/Element.php(2188): yii\base\Component->__get('billingAddress')
#10 /var/www/html/craft/vendor/yiisoft/yii2/validators/Validator.php(257): craft\base\Element->__get('billingAddress')
#11 /var/www/html/craft/vendor/yiisoft/yii2/base/Model.php(368): yii\validators\Validator->validateAttributes(Object(craft\commerce\elements\Order), Array)
#12 /var/www/html/craft/vendor/craftcms/cms/src/base/Element.php(2458): yii\base\Model->validate(Array, true)
#13 /var/www/html/craft/vendor/craftcms/cms/src/services/Elements.php(1643): craft\base\Element->validate()
#14 /var/www/html/craft/modules/bookingengine/commands/DuplicateOrderController.php(29): craft\services\Elements->duplicateElement(Object(craft\commerce\elements\Order))
#15 [internal function]: modules\bookingengine\commands\DuplicateOrderController->actionIndex(24836)
#16 /var/www/html/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#17 /var/www/html/craft/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#18 /var/www/html/craft/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('index', Array)
#19 /var/www/html/craft/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction('index', Array)
#20 /var/www/html/craft/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction('index', Array)
#21 /var/www/html/craft/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('index', Array)
#22 /var/www/html/craft/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('bookingengine/d...', Array)
#23 /var/www/html/craft/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('bookingengine/d...', Array)
#24 /var/www/html/craft/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('bookingengine/d...', Array)
#25 /var/www/html/craft/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#26 /var/www/html/craft/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#27 /var/www/html/craft/craft(13): yii\base\Application->run()
#28 {main}
```

### Steps to reproduce

1. Complete an order (make sure the order has a mixture of required fields set and complete)
2. Go to the CP and select an order to duplicate
3. Click the cog in the element index and click duplicate

### Expected behavior

For an order to duplicate or to log more verbose debugging information

### Actual behavior

Toast error
> Could not duplicate elements due to validation errors.

### Craft CMS version

Craft Pro 4.12.8

### Craft Commerce version

4.7.0

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
@jonleverrier `Orders` do not support duplication at the moment. The Order element’s `canDuplicate()` method always returns false.

If you want to manually duplicate an order in a module, that is fine, but you would need to make sure that the addresses that are set on the order have their owner set to the new order before the addresses are saved. You cant have an address belong to 2 different orders.

Please make a discussion with a request for us to support duplicating orders in the future.

Thanks.

**Comment by jonleverrier** [comment]
Thanks for getting back to me @lukeholder.

I thought that was the case but I saw the duplicate item in the element index and thought it was possible. Maybe it should be hidden from the UI until officially supported?

![Image](https://github.com/user-attachments/assets/7b088f49-b16f-4c65-88b3-003d20ed0a0d)

**Comment by lukeholder** [comment]
That option show no longer show up on recent version of commerce. Thanks.

**Comment by jonleverrier** [comment]
> That option show no longer show up on recent version of commerce. Thanks.

Still there as of `4.8.3`
