### ISSUE TITLE
Issue Saving Commerce Emails with Enabled set to Off

### ISSUE THREAD

**Issue by bryantAXS** [craftcms/commerce#376]
### Description

```
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'enabled' cannot be null in /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/Command.php:1258
Stack trace:
#0 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/Command.php(1258): PDOStatement->execute()
#1 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('UPDATE `craft_c...')
#2 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/ActiveRecord.php(281): yii\db\Command->execute()
#3 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/BaseActiveRecord.php(802): yii\db\ActiveRecord::updateAll(Array, Array)
#4 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/ActiveRecord.php(625): yii\db\BaseActiveRecord->updateInternal(NULL)
#5 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/BaseActiveRecord.php(673): yii\db\ActiveRecord->update(false, NULL)
#6 /home/forge/safebones3.authenticff.com/vendor/craftcms/commerce/src/services/Emails.php(137): yii\db\BaseActiveRecord->save(false)
#7 /home/forge/safebones3.authenticff.com/vendor/craftcms/commerce/src/controllers/EmailsController.php(91): craft\commerce\services\Emails->saveEmail(Object(craft\commerce\models\Email))
#8 [internal function]: craft\commerce\controllers\EmailsController->actionSave()
#9 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /home/forge/safebones3.authenticff.com/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('save', Array)
#12 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save', Array)
#13 /home/forge/safebones3.authenticff.com/vendor/craftcms/cms/src/web/Application.php(273): yii\base\Module->runAction('commerce/emails...', Array)
#14 /home/forge/safebones3.authenticff.com/vendor/craftcms/cms/src/web/Application.php(521): craft\web\Application->runAction('commerce/emails...', Array)
#15 /home/forge/safebones3.authenticff.com/vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /home/forge/safebones3.authenticff.com/web/index.php(43): yii\base\Application->run()
#18 {main}

Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'enabled' cannot be null
The SQL being executed was: UPDATE `craft_commerce_emails` SET `enabled`=NULL, `dateUpdated`='2018-06-19 11:43:30' WHERE `id`=5 in /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'UPDATE `craft_c...')
#1 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('UPDATE `craft_c...')
#2 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/ActiveRecord.php(281): yii\db\Command->execute()
#3 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/BaseActiveRecord.php(802): yii\db\ActiveRecord::updateAll(Array, Array)
#4 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/ActiveRecord.php(625): yii\db\BaseActiveRecord->updateInternal(NULL)
#5 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/BaseActiveRecord.php(673): yii\db\ActiveRecord->update(false, NULL)
#6 /home/forge/safebones3.authenticff.com/vendor/craftcms/commerce/src/services/Emails.php(137): yii\db\BaseActiveRecord->save(false)
#7 /home/forge/safebones3.authenticff.com/vendor/craftcms/commerce/src/controllers/EmailsController.php(91): craft\commerce\services\Emails->saveEmail(Object(craft\commerce\models\Email))
#8 [internal function]: craft\commerce\controllers\EmailsController->actionSave()
#9 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /home/forge/safebones3.authenticff.com/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('save', Array)
#12 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save', Array)
#13 /home/forge/safebones3.authenticff.com/vendor/craftcms/cms/src/web/Application.php(273): yii\base\Module->runAction('commerce/emails...', Array)
#14 /home/forge/safebones3.authenticff.com/vendor/craftcms/cms/src/web/Application.php(521): craft\web\Application->runAction('commerce/emails...', Array)
#15 /home/forge/safebones3.authenticff.com/vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /home/forge/safebones3.authenticff.com/web/index.php(43): yii\base\Application->run()
#18 {main}
Additional Information:
Array
(
    [0] => 23000
    [1] => 1048
    [2] => Column 'enabled' cannot be null
)
```

### Steps to reproduce

1. Create a new Email and set the Enabled switch to False

### Additional info

- Craft version: 3.0.11
- PHP version: 7.1
- Database driver & version: Marina
- Plugins & versions:

**Comment by lukeholder** [comment]
Should now be fixed. Please let us know if is not.
