### ISSUE TITLE
Issue Creating New Order Status

### ISSUE THREAD

**Issue by bryantAXS** [craftcms/commerce#377]
### Description

```
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'default' cannot be null in /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/Command.php:1258
Stack trace:
#0 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/Command.php(1258): PDOStatement->execute()
#1 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('INSERT INTO `cr...')
#2 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/Schema.php(433): yii\db\Command->execute()
#3 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/ActiveRecord.php(549): yii\db\Schema->insert('{{%commerce_ord...', Array)
#4 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/ActiveRecord.php(515): yii\db\ActiveRecord->insertInternal(NULL)
#5 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/BaseActiveRecord.php(670): yii\db\ActiveRecord->insert(false, NULL)
#6 /home/forge/safebones3.authenticff.com/vendor/craftcms/commerce/src/services/OrderStatuses.php(215): yii\db\BaseActiveRecord->save(false)
#7 /home/forge/safebones3.authenticff.com/vendor/craftcms/commerce/src/controllers/OrderStatusesController.php(98): craft\commerce\services\OrderStatuses->saveOrderStatus(Object(craft\commerce\models\OrderStatus), Array)
#8 [internal function]: craft\commerce\controllers\OrderStatusesController->actionSave()
#9 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /home/forge/safebones3.authenticff.com/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('save', Array)
#12 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save', Array)
#13 /home/forge/safebones3.authenticff.com/vendor/craftcms/cms/src/web/Application.php(273): yii\base\Module->runAction('commerce/order-...', Array)
#14 /home/forge/safebones3.authenticff.com/vendor/craftcms/cms/src/web/Application.php(521): craft\web\Application->runAction('commerce/order-...', Array)
#15 /home/forge/safebones3.authenticff.com/vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /home/forge/safebones3.authenticff.com/web/index.php(43): yii\base\Application->run()
#18 {main}

Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'default' cannot be null
The SQL being executed was: INSERT INTO `craft_commerce_orderstatuses` (`name`, `handle`, `color`, `sortOrder`, `default`, `dateCreated`, `uid`, `dateUpdated`) VALUES ('Processing - Subscription', 'processingSubscription', 'blue', 999, NULL, '2018-06-19 11:45:10', '996f6c7c-14ae-49c5-9c94-5e5f16e532e6', '2018-06-19 11:45:10') in /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `cr...')
#1 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('INSERT INTO `cr...')
#2 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/Schema.php(433): yii\db\Command->execute()
#3 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/ActiveRecord.php(549): yii\db\Schema->insert('{{%commerce_ord...', Array)
#4 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/ActiveRecord.php(515): yii\db\ActiveRecord->insertInternal(NULL)
#5 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/db/BaseActiveRecord.php(670): yii\db\ActiveRecord->insert(false, NULL)
#6 /home/forge/safebones3.authenticff.com/vendor/craftcms/commerce/src/services/OrderStatuses.php(215): yii\db\BaseActiveRecord->save(false)
#7 /home/forge/safebones3.authenticff.com/vendor/craftcms/commerce/src/controllers/OrderStatusesController.php(98): craft\commerce\services\OrderStatuses->saveOrderStatus(Object(craft\commerce\models\OrderStatus), Array)
#8 [internal function]: craft\commerce\controllers\OrderStatusesController->actionSave()
#9 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /home/forge/safebones3.authenticff.com/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('save', Array)
#12 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save', Array)
#13 /home/forge/safebones3.authenticff.com/vendor/craftcms/cms/src/web/Application.php(273): yii\base\Module->runAction('commerce/order-...', Array)
#14 /home/forge/safebones3.authenticff.com/vendor/craftcms/cms/src/web/Application.php(521): craft\web\Application->runAction('commerce/order-...', Array)
#15 /home/forge/safebones3.authenticff.com/vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /home/forge/safebones3.authenticff.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /home/forge/safebones3.authenticff.com/web/index.php(43): yii\base\Application->run()
#18 {main}
Additional Information:
Array
(
    [0] => 23000
    [1] => 1048
    [2] => Column 'default' cannot be null
)
```

### Steps to reproduce

1. Create new order status
2. Hit save

### Additional info

- Craft version: 3.0.11
- PHP version: 7.1
- Database driver & version: mysql
- Plugins & versions:

**Comment by lukeholder** [comment]
I cant reproduce in either MySQL or Postgres, but I coerced the value from POST to a bool so it should be included in the model (not be set to null).

My guess is that it is a MySQL warning level. Try `dev-develop` version of commerce in your comoser.json if you want to test the fix before the next release.
