### ISSUE TITLE
PHP error `defaultViewMode`

### ISSUE THREAD

**Issue by mdresoled** [craftcms/commerce#3774]
### Description

We upgraded our Commerce and CMS versions this morning.

Now whenever we access the the commerce table on a user profile we get the following error log

```txt
2024-11-15 18:28:24 [web.INFO] [yii\db\Connection::open] Opening DB connection: pgsql:host=127.0.0.1;port=3307;dbname=somedb {"memory":820840} 
2024-11-15 18:28:24 [web.INFO] [yii\web\Session::open] Session started {"memory":1585400} 
2024-11-15 18:28:24 [web.INFO] [nystudio107\codeeditor\CodeEditor::bootstrap] CodeEditor module bootstrapped {"memory":1685824} 
2024-11-15 18:28:24 [web.ERROR] [yii\base\ErrorException:2] yii\base\ErrorException: Undefined array key "defaultViewMode" in /app/vendor/craftcms/cms/src/helpers/Cp.php:1286
Stack trace:
#0 /app/vendor/craftcms/cms/src/web/ErrorHandler.php(79): yii\base\ErrorHandler->handleError()
#1 /app/vendor/craftcms/cms/src/helpers/Cp.php(1286): craft\web\ErrorHandler->handleError()
#2 /app/vendor/craftcms/commerce/src/controllers/UsersController.php(68): craft\helpers\Cp::elementIndexHtml()
#3 [internal function]: craft\commerce\controllers\UsersController->actionIndex()
#4 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#5 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#6 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#7 /app/vendor/craftcms/cms/src/web/Application.php(350): yii\base\Module->runAction()
#8 /app/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#9 /app/vendor/craftcms/cms/src/web/Application.php(318): yii\web\Application->handleRequest()
#10 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#11 /app/web/index.php(12): yii\base\Application->run()
#12 {main} {"memory":3566800,"exception":"[object] (yii\\base\\ErrorException(code: 2): Undefined array key \"defaultViewMode\" at /app/vendor/craftcms/cms/src/helpers/Cp.php:1286)"} 
```

### Steps to reproduce

1. Upgrade to CMS 5.5.0.1 and Commerce to 5.2.4
2. Navigati to users
3. Select user
4. Click the Commerce tab on the left

### Expected behavior

Show me the standard Commerce section

### Actual behavior

The commerce section is blank

### Craft CMS version

5.5.0.1

### Craft Commerce version

5.2.4

**Comment by lukeholder** [comment]
Fixed in [craftcms/cms](https://github.com/craftcms/cms/pull/16130) - we will update this ticket once the update is available. Thanks.

**Comment by brandonkelly** [comment]
Craft 5.5.1 is out with that fix. Thanks again!
