### ISSUE TITLE
[5.x]: Fatal Error when adding a partial payment in CP

### ISSUE THREAD

**Issue by Latex88** [craftcms/commerce#3804]
### Description

When adding a payment to an order with the dummy gateway a fatal error accurs.
Probably related to: https://github.com/craftcms/commerce/issues/3789

### Steps to reproduce

1. Create Order
2. Go to the transactions tab
3. Add a payment
4. Fatalerror

```
TypeError: craft\commerce\elements\Order::setPaymentAmount(): Argument #1 ($amount) must be of type float, array given, called in /var/www/html/backend/vendor/craftcms/commerce/src/controllers/PaymentsController.php on line 446 and defined in /var/www/html/backend/vendor/craftcms/commerce/src/elements/Order.php:2569
Stack trace:
#0 /var/www/html/backend/vendor/craftcms/commerce/src/controllers/PaymentsController.php(446): craft\commerce\elements\Order->setPaymentAmount(Array)
#1 [internal function]: craft\commerce\controllers\PaymentsController->actionPay()
#2 /var/www/html/backend/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /var/www/html/backend/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#4 /var/www/html/backend/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('pay', Array)
#5 /var/www/html/backend/vendor/craftcms/cms/src/web/Application.php(350): yii\base\Module->runAction('commerce/paymen...', Array)
#6 /var/www/html/backend/vendor/craftcms/cms/src/web/Application.php(649): craft\web\Application->runAction('commerce/paymen...', Array)
#7 /var/www/html/backend/vendor/craftcms/cms/src/web/Application.php(312): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#8 /var/www/html/backend/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /var/www/html/backend/web/index.php(12): yii\base\Application->run()
#10 {main}
```

It's because the paymentAmount is an Array and not a float:
array(2) { ["locale"]=> string(2) "en" ["value"]=> string(6) "322.00" }

### Craft CMS version

5.5.5

### Craft Commerce version

5.2.8

### PHP version

8.2

### Installed plugins and versions

-

**Comment by lukeholder** [comment]
Thanks for reporting. This is fixed for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/commerce": "5.x-dev#85496aa93c4b71e89617447eccd669739b1de642 as 5.2.8",
  "...": "..."
}
```

Then run `composer update`.

We will update this ticket once the release is out.

**Comment by nfourtythree** [comment]
Commerce `5.2.9` has been released with this fix included.

Thanks!
