### ISSUE TITLE
I'm seeing an "Invalid argument" error in web.log

### ISSUE THREAD

**Issue by 23d1** [craftcms/commerce#519]
### Description
I'm seeing a lot of "Invalid argument" errors in the web.log for a "Multiple Option Variant" module I have running. It seems to be working just fine on the site, but curious as to what the issue might be.

This is the error;
```
[error][yii\base\ErrorException:2] yii\base\ErrorException: Invalid argument supplied for foreach() in /httpd.www/craft/modules/multipleoptionvariantmodule/src/variables/MultipleOptionVariantModuleVariable.php:52
#0 /httpd.www/craft/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(2, 'Invalid argumen...', '/httpd.www/...', 52)
#1 /httpd.www/craft/modules/multipleoptionvariantmodule/src/variables/MultipleOptionVariantModuleVariable.php(52): craft\web\ErrorHandler->handleError(2, 'Invalid argumen...', '/httpd.www/...', 52, Array)
```
The referenced file at looks like this—and it seems to be the foreach function that's the culprit;
```
namespace modules\multipleoptionvariantmodule\variables;

use modules\multipleoptionvariantmodule\MultipleOptionVariantModule;

use Craft;

class MultipleOptionVariantModuleVariable
{
     public function getUniqueVariantAttributeValues($fieldName, $variants, $onlyInStock=false) {
         $addedIds = array();
         $sizes = array();

         foreach($variants as $variant) {
             $outOfStock = (($variant->stock <= 0) && ($variant->hasUnlimitedStock == false));

             if (!$onlyInStock || ($onlyInStock && !$outOfStock)) {
                 if (isset($variant->{$fieldName}[0])) {
                     if (array_search($variant->{$fieldName}[0]->slug, $addedIds, true) === false) {
                         $sizes[] = $variant->{$fieldName}[0];
                         $addedIds[] = $variant->{$fieldName}[0]->slug;
                     }
                 }
             }
         }

         return $sizes;
    }
}
```

I'd take any hints on how to convert that functionality to pure twig too. :)

### Additional info

- Craft version: 3.0.26.1
- PHP version: 7.2.7
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Craft Commerce 2.0.0-beta.11

**Comment by lukeholder** [comment]
You will need to talk to the developer of the module. Look like there might just need to be some guards in the code for variable existing before using them. Or try Stack Exchange.
