### ISSUE TITLE
craft\commerce\models\OrderAdjustment::getSourceSnapshot() must be of the type array, null returned

### ISSUE THREAD

**Issue by N0ps32** [craftcms/commerce#644]
### Description

I updated my system from commerce 2 beta to commerce 2.0.1 and now my custom order adjustment stopped working. As soon as I add the order Adjustment I get this error:

```
TypeError: Return value of craft\commerce\models\OrderAdjustment::getSourceSnapshot() must be of the type array, null returned in /app/vendor/craftcms/commerce/src/models/OrderAdjustment.php:112
Stack trace:
#0 /app/vendor/yiisoft/yii2/base/Component.php(139): craft\commerce\models\OrderAdjustment->getSourceSnapshot()
#1 /app/vendor/craftcms/commerce/src/services/OrderAdjustments.php(144): yii\base\Component->__get('sourceSnapshot')
#2 /app/vendor/craftcms/commerce/src/elements/Order.php(1978): craft\commerce\services\OrderAdjustments->saveOrderAdjustment(Object(craft\commerce\models\OrderAdjustment), false)
#3 /app/vendor/craftcms/commerce/src/elements/Order.php(918): craft\commerce\elements\Order->_saveAdjustments()
#4 /app/vendor/craftcms/cms/src/services/Elements.php(515): craft\commerce\elements\Order->afterSave(false)
#5 /app/vendor/craftcms/commerce/src/controllers/CartController.php(304): craft\services\Elements->saveElement(Object(craft\commerce\elements\Order), false)
#6 /app/vendor/craftcms/commerce/src/controllers/CartController.php(287): craft\commerce\controllers\CartController->_returnCart()
#7 [internal function]: craft\commerce\controllers\CartController->actionUpdateCart()
#8 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /app/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('update-cart', Array)
#11 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('update-cart', Array)
#12 /app/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('commerce/cart/u...', Array)
#13 /app/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('commerce/cart/u...', Array)
#14 /app/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#15 /app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#16 /app/web/index.php(21): yii\base\Application->run()
#17 {main}
```

### Additional info

- Craft version: 3.1.3
- PHP version: 7.2.13
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Custom

**Comment by harnasz** [comment]
Hi @N0ps32, 

We're getting this error too, how did you manage to solve it? 

Cheers,

Tom

**Comment by N0ps32** [comment]
Hey @harnasz when creating your custom order adjuster you have to make sure to set the sourceSnapshot property. I set it to an empty array and that solved the issue.

```
$discountAdjuster = new OrderAdjustment();
$discountAdjuster->sourceSnapshot = [];
```

**Comment by harnasz** [comment]
Hi @N0ps32, 

That's awesome, resolves it for me, thank you very much for that!
