### ISSUE TITLE
InvalidConfigException when deleting a product

### ISSUE THREAD

**Issue by tim-pixeldeluxe** [craftcms/commerce#650]
### Description
I am unable to delete any of my products. Every time I try to delete one I get a InvalidConfigException because my product isn't being found. I've been debugging this myself but haven't found the cause. I did get some results, maybe my test results will help you identify the problem. The results can be found below.

So I added some debug messages to the craft commerce source code and then added some other debug messages in my controller test function. 

**This is the commerce code (Variant element class):**
```php
public function getProduct()
    {
        if ($this->_product !== null) {
            return $this->_product;
        }

        if ($this->productId === null) {
            throw new InvalidConfigException('Variant is missing its product');
        }

        var_dump(Craft::$app->getElements()->getElementById(181, Product::class, 1));
        exit($this->productId . " / " . $this->siteId);

        if (($product = Plugin::getInstance()->getProducts()->getProductById($this->productId, $this->siteId)) === null) {
            throw new InvalidConfigException('Invalid product ID: ' . $this->productId);
        }

        return $this->_product = $product;
    }
```

**This is my controller code:**
```php
public function actionTest() {
        /*$query = new ElementQuery(Product::class);
        $query->id = 181;
        $query->siteId = 1;
        $query->anyStatus();
        $result = $query->all();
        $result = Plugin::getInstance()->getProducts()->getProductById(181, 1);*/
        $result = Craft::$app->getElements()->getElementById(181, Product::class, 1);

        $response = Craft::$app->getResponse();
        $response->content = json_encode($result);
        return $response;
    }
```

Now these are the results I got.
**Result when trying to delete a product from the cp:**
```json
NULL 181 / 1
```

**Result from my controller action:**
```json
{
   "postDate":{
      "date":"2019-01-23 15:54:16.000000",
      "timezone_type":3,
      "timezone":"Europe\/Amsterdam"
   },
   "expiryDate":null,
   "typeId":"1",
   "taxCategoryId":"72",
   "shippingCategoryId":"1",
   "promotable":"1",
   "freeShipping":"0",
   "enabled":"1",
   "availableForPurchase":"1",
   "defaultVariantId":null,
   "defaultSku":"tetergz",
   "defaultPrice":"21.0000",
   "defaultHeight":"0.0000",
   "defaultLength":"0.0000",
   "defaultWidth":"0.0000",
   "defaultWeight":"0.0000",
   "taxCategory":null,
   "name":null,
   "id":"181",
   "tempId":null,
   "uid":"693cfa15-b4cc-4c23-bf1a-da3c69b2d30f",
   "fieldLayoutId":"29",
   "structureId":null,
   "contentId":"260",
   "archived":"0",
   "siteId":1,
   "enabledForSite":"1",
   "title":"test",
   "slug":"test-1",
   "uri":"webwinkel\/producten\/boeken\/test-1",
   "dateCreated":{
      "date":"2019-01-23 15:54:16.000000",
      "timezone_type":3,
      "timezone":"Europe\/Amsterdam"
   },
   "dateUpdated":{
      "date":"2019-01-23 15:54:16.000000",
      "timezone_type":3,
      "timezone":"Europe\/Amsterdam"
   },
   "root":null,
   "lft":null,
   "rgt":null,
   "level":null,
   "searchScore":null,
   "trashed":false,
   "awaitingFieldValues":false,
   "propagating":false,
   "duplicateOf":null
}
```

I tried a few different approaches in my controller class. I tried: element query, product service getProductById and elements service getElementById. They all returned my product data. It looks like the product query always returns null when called from the Variant element class.

### Steps to reproduce

1. Delete a product
2. Error

### Additional info

- Craft version: 3.1.1
- PHP version: 7.1.6
- Database driver & version: MySQL 5.6.35
- Plugins & versions: Craft Commerce 2.0.1

### Stacktrace

```
yii\base\InvalidConfigException: Invalid product ID: 181 in /Applications/MAMP/htdocs/privateprojectname/vendor/craftcms/commerce/src/elements/Variant.php:305
Stack trace:
#0 /Applications/MAMP/htdocs/privateprojectname/vendor/craftcms/commerce/src/elements/Variant.php(282): craft\commerce\elements\Variant->getProduct()
#1 /Applications/MAMP/htdocs/privateprojectname/vendor/craftcms/cms/src/base/Element.php(2072): craft\commerce\elements\Variant->getFieldLayout()
#2 /Applications/MAMP/htdocs/privateprojectname/vendor/craftcms/cms/src/base/Element.php(1893): craft\base\Element->fieldLayoutFields()
#3 /Applications/MAMP/htdocs/privateprojectname/vendor/craftcms/cms/src/services/Elements.php(957): craft\base\Element->beforeDelete()
#4 /Applications/MAMP/htdocs/privateprojectname/vendor/craftcms/cms/src/services/Elements.php(937): craft\services\Elements->deleteElement(Object(craft\commerce\elements\Variant))
#5 /Applications/MAMP/htdocs/privateprojectname/vendor/craftcms/commerce/src/elements/Product.php(766): craft\services\Elements->deleteElementById(182, 'craft\\commerce\\...')
#6 /Applications/MAMP/htdocs/privateprojectname/vendor/craftcms/cms/src/services/Elements.php(1002): craft\commerce\elements\Product->afterDelete()
#7 /Applications/MAMP/htdocs/privateprojectname/vendor/craftcms/commerce/src/controllers/ProductsController.php(175): craft\services\Elements->deleteElement(Object(craft\commerce\elements\Product))
#8 [internal function]: craft\commerce\controllers\ProductsController->actionDeleteProduct()
#9 /Applications/MAMP/htdocs/privateprojectname/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /Applications/MAMP/htdocs/privateprojectname/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /Applications/MAMP/htdocs/privateprojectname/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('delete-product', Array)
#12 /Applications/MAMP/htdocs/privateprojectname/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('delete-product', Array)
#13 /Applications/MAMP/htdocs/privateprojectname/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('commerce/produc...', Array)
#14 /Applications/MAMP/htdocs/privateprojectname/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('commerce/produc...', Array)
#15 /Applications/MAMP/htdocs/privateprojectname/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /Applications/MAMP/htdocs/privateprojectname/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /Applications/MAMP/htdocs/privateprojectname/public_html/index.php(21): yii\base\Application->run()
#18 {main}
```

**Comment by BrandonJamesBorders** [comment]
Having the same problem as well. Can't delete any products. Trying to do some investigation as well.

Craft CMS 3.1.3
Craft Commerce 2.0.2

**Comment by lukeholder** [comment]
Thanks, confirmed bug, I think it's related to soft deletes. Will look to get a fix out soon.
