### ISSUE TITLE
Unable to create record from EVENT_AFTER_ORDER_PAID event

### ISSUE THREAD

**Issue by tim-pixeldeluxe** [craftcms/commerce#679]
### Description
I'm trying to push a Craft job that will send orders to an external API whenever an order is completed. I tried EVENT_AFTER_ORDER_PAID, EVENT_AFTER_COMPLETE_ORDER and EVENT_AFTER_CAPTURE_TRANSACTION but always get the same error.

Error:
```
2019-02-01 14:36:29 [-][33][-][error][craft\queue\QueueLogBehavior::afterError]  [110] Processing order 2248 (attempt: 1) - Error (time: 0.081s): session_start(): Cannot send session cookie - headers already sent by (output started at /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/web/Response.php:185)
2019-02-01 14:36:29 [-][33][-][error][yii\base\ErrorException:2] yii\base\ErrorException: session_start(): Cannot send session cookie - headers already sent by (output started at /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/web/Response.php:185) in /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/web/Session.php:137
#0 /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(2, 'session_start()...', '/Applications/M...', 137)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'session_start()...', '/Applications/M...', 137, Array)
```

I tried pushing the same exact job from a controller function and it worked perfectly fine. This line of code seems to be causing the error (when I place a return before this line I don't get an error):
```php
PrivateNameCore::getInstance()->apiLogger->log(LogType::DEBUG, "Processing product order " . $order->reference . "...", null, $order->email);
```

![schermafbeelding 2019-02-01 om 15 20 16](https://user-images.githubusercontent.com/46448696/52128439-4092de80-2635-11e9-8aa0-1ef4305e167a.png)

which runs this code:
```php
    public function log($logType, $title, $description = null, $extra = null) {
        if($logType == "debug" && !Craft::$app->config->general->enableDebugLogs) return;

        $record = new ApiLogRecord();
        $record->type = $logType;
        $record->title = $title;
        $record->description = $description;
        $record->extra = $extra;

        if(Craft::$app->getDb()->getTransaction()) {
            array_push($this->waiting, $record);
            return;
        }

        $record->save();
    }
```

### Steps to reproduce

1. Push a Craft job that creates a record from one of the events triggered after order completion.
2. Error

### Additional info

- Craft version: 3.1.7
- PHP version: 7.1.6
- Database driver & version: MySQL 5.5.59
- Plugins & versions: Craft Commerce 2.0.2

**Comment by tim-pixeldeluxe** [comment]
@lukeholder Any idea what the problem may be? Thanks in advance!

**Comment by lukeholder** [comment]
If you drop the `$order->email` from the logging call does the error go away?

**Comment by tim-pixeldeluxe** [comment]
Unfortunately no. 

**This is the whole error:**
```
2019-02-13 16:57:03 [-][33][-][error][craft\queue\QueueLogBehavior::afterError]  [42] Processing order 2257 (attempt: 1) - Error (time: 0.719s): session_start(): Cannot send session cookie - headers already sent by (output started at /Applications/MAMP/htdocs/privateproject/vendor/craftcms/cms/src/web/Response.php:185)
2019-02-13 16:57:03 [-][33][-][error][yii\base\ErrorException:2] yii\base\ErrorException: session_start(): Cannot send session cookie - headers already sent by (output started at /Applications/MAMP/htdocs/privateproject/vendor/craftcms/cms/src/web/Response.php:185) in /Applications/MAMP/htdocs/privateproject/vendor/yiisoft/yii2/web/Session.php:137
#0 /Applications/MAMP/htdocs/privateproject/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(2, 'session_start()...', '/Applications/M...', 137)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'session_start()...', '/Applications/M...', 137, Array)
2019-02-13 16:57:03 [-][33][-][info][yii\db\Command::execute] UPDATE `queue` SET `fail`=1, `dateFailed`='2019-02-13 15:57:03', `error`='session_start(): Cannot send session cookie - headers already sent by (output started at /Applications/MAMP/htdocs/privateproject/vendor/craftcms/cms/src/web/Response.php:185)' WHERE `id`='42'
2019-02-13 16:57:03 [-][33][-][profile begin][yii\db\Command::execute] UPDATE `queue` SET `fail`=1, `dateFailed`='2019-02-13 15:57:03', `error`='session_start(): Cannot send session cookie - headers already sent by (output started at /Applications/MAMP/htdocs/privateproject/vendor/craftcms/cms/src/web/Response.php:185)' WHERE `id`='42'
2019-02-13 16:57:03 [-][33][-][profile end][yii\db\Command::execute] UPDATE `queue` SET `fail`=1, `dateFailed`='2019-02-13 15:57:03', `error`='session_start(): Cannot send session cookie - headers already sent by (output started at /Applications/MAMP/htdocs/privateproject/vendor/craftcms/cms/src/web/Response.php:185)' WHERE `id`='42'
```

**This is the whole job class:**
```
<?php
namespace privatename\privatename\jobs;

use Craft;
use craft\commerce\Plugin as CraftCommerce;
use craft\commerce\elements\Order;
use privatename\siteutils\base\ApiCall;
use privatename\privatename\errors\ApiBadResponseException;
use privatename\privatename\PrivateNameCore;
use privatename\privatename\enums\LogType;
use privatename\privatename\helpers\LineItemHelper;

class ProcessOrderTask extends OrderTask {

	private $orderId;

	public function __construct(Order $order) {
		parent::__construct();
		$this->orderId = $order->id;
	}

    public function execute($queue) {
        $order = CraftCommerce::getInstance()->orders->getOrderById($this->orderId);
        if(!$order) {
            throw new ApiBadResponseException("Order with id " . $this->orderId . " does not exist");
        }

        $billingAddress = $order->getBillingAddress();
        $shippingAddress = $order->getShippingAddress();
    	$date = $order->dateOrdered->format("Y-d-m");
    	$time = $order->dateOrdered->format("H:i");
        $gender = "O";

        // Set the gender
        if($billingAddress->attention == "Dhr") $gender = "M";
        if($billingAddress->attention == "Mevr") $gender = "V";

        PrivateNameCore::getInstance()->apiLogger->log(LogType::INFO, "Processing order " . $order->reference . "...", null);

        // Create API call
        $apiCall = new ApiCall('https://private.url');
        $apiCall->setMethod('POST');

        // Provide token
        $apiCall->addHeaders([
            'Authorization: ' . $this->token
        ]);

        // Order data
        $data = [];

        // Basic order info
        $data["privatefieldname"]      = $date;
        $data["privatefieldname"]       = $time;

        // Customer info
        $data["privatefieldname"]   = $gender;
        $data["privatefieldname"]   = $billingAddress->businessName;
        $data["privatefieldname"]      = $billingAddress->firstName;
        $data["privatefieldname"] = $billingAddress->lastName;

        // Address
        /*$data["privatefieldname"]    = $billingAddress->zipCode; straat
        $data["privatefieldname"]        = $billingAddress->zipCode; huisnummer
        $data["privatefieldname"]   = $billingAddress->zipCode; extra */
        $data["privatefieldname"]      = $billingAddress->zipCode;
        $data["privatefieldname"]        = $billingAddress->city;
        $data["privatefieldname"]    = $billingAddress->getCountry()->iso;

        // Contact info
        $data["privatefieldname"]   = $billingAddress->phone;
        $data["privatefieldname"]     = $billingAddress->alternativePhone;
        $data["privatefieldname"]      = $order->email;

        // Include shipping address if using different address
        if(!$order->billingSameAsShipping) {
            $data["privatefieldname "]      = $shippingAddress->getFullName();
            /*$data["privatefieldname"]    = $billingAddress->zipCode; straat
            $data["privatefieldname"]        = $billingAddress->zipCode; huisnummer
            $data["privatefieldname"]   = $billingAddress->zipCode; extra */
            $data["privatefieldname"]      = $shippingAddress->zipCode;
            $data["privatefieldname"]        = $billingAddress->city;
            $data["privatefieldname"]    = $billingAddress->getCountry()->iso;
        }

        // Add data to ApiCall
        $apiCall->addData(["Data" => $data]);

        // Send it and get the response
        $json = $apiCall->send();

        // No response from api
        if(!$json) {
            throw new ApiBadResponseException(ApiTask::ERROR_NO_RESPONSE);
        }

        // Api response recieved but there is an error
        if(!empty($json->Error)) {
        	throw new ApiBadResponseException(ApiTask::ERROR_MESSAGE . $json->Error);
        }

        // Get the order id
        $externalOrder = reset($json);
        if(!$externalOrder) {
            throw new ApiBadResponseException("The response did not provide an order");
        }

        PrivateNameCore::getInstance()->apiLogger->log(LogType::DEBUG, "Product order " . $order->reference . " has been processed, sending lines...", null, $json);

        // We're all good, now lets add some lines to this order
        foreach($order->lineItems as $item) {
            $type = LineItemHelper::getProductType($item);

            // Process LineItem depending on producttype
            if($type == "courses") {
                Craft::$app->queue->push(new ProcessCourseOrderTask($externalOrder->Id, $item));
            } else {
                Craft::$app->queue->push(new ProcessProductOrderTask($externalOrder->Id, $item)); 
            } 
        }
    }

    public function getDescription() {
        return 'Processing order ' . $this->orderId;
    }

}
```

if you need any more info please let me know 😄. Thanks in advance!

**Comment by tim-pixeldeluxe** [comment]
Also I think the problem might be caused by the _handleRedirect function in the Payments service class. At the end of this function Craft::$app->end(); is executed. I can imagine that this could be causing the headers already sent error if the event is fired after this function was called.

**Comment by lukeholder** [comment]
Are you trying to make a payment on an order? can't see that in your code?

**Comment by tim-pixeldeluxe** [comment]
I have been investigating and found out that this doesn't seem to be caused by Craft Commerce. The Craft Commerce events just trigger the actual cause. It seems to be caused by me pushing multiple jobs from inside another job. The code worked when I trigger my controller (pushing the initial job) via an url, but it doesn't when triggered via a form.

I think this issue can be closed as I'm pretty sure this isn't caused by Craft Commerce. Sorry for waisting some of your time. Have a nice day! :)

**Comment by tim-pixeldeluxe** [comment]
Hi again @lukeholder, 
Turns out I was wrong. I removed my job code and still got the same error. The error seems to be caused by $order->lineItems used in my for loop. When I remove this code the job works fine. I tried $order->getLineItems() which obviously didn't make any difference. I then replaced the code of that function with `return [];` and didn't get any errors.

```php
// We're all good, now lets add some lines to this order
foreach($order->lineItems as $item) { // <-- Error caused by calling $order->lineItems here
    $type = LineItemHelper::getProductType($item);

    // Process LineItem depending on producttype
    if($type == "courses") {
        Craft::$app->queue->push(new ProcessCourseOrderTask($externalOrder->Id, $item));
    } else {
        Craft::$app->queue->push(new ProcessProductOrderTask($externalOrder->Id, $item)); 
    } 
}
```

So using the function with the following code gives me the error:
(craft\commerce\elements\Order:1182)
```php
    public function getLineItems(): array
    {
        if (null === $this->_lineItems) {
            $lineItems = $this->id ? Plugin::getInstance()->getLineItems()->getAllLineItemsByOrderId($this->id) : [];
            foreach ($lineItems as $lineItem) {
                $lineItem->setOrder($this);
            }
            $this->_lineItems = $lineItems;
        }

        return $this->_lineItems;
    }
```

But when I change it to this it works:
```php
    public function getLineItems(): array
    {
        return [];
    }
```

After some more debugging I found out the the error is caused by line 103 in the lineItems service:
```php
$lineItems[] = new LineItem($result);
```
Removing this line solves the problem.

If you need any more info please let me know.

**Comment by lukeholder** [comment]
What's the actual error? Are you using the latest code on `dev-develop` in your composer.json?

**Comment by tim-pixeldeluxe** [comment]
Error:
```php
2019-02-18 15:28:51 [-][33][-][error][craft\queue\QueueLogBehavior::afterError]  [52] Processing order 2715 (attempt: 1) - Error (time: 0.669s): session_start(): Cannot send session cookie - headers already sent by (output started at /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/web/Response.php:185)
2019-02-18 15:28:51 [-][33][-][profile begin][craft\web\twig\Environment::compileSource] __string_template__83e1ab0ea61c4114c0a11e82878d36870c03212f1c613eebae1aed910db499d4
2019-02-18 15:28:51 [-][33][-][profile end][craft\web\twig\Environment::compileSource] __string_template__83e1ab0ea61c4114c0a11e82878d36870c03212f1c613eebae1aed910db499d4
2019-02-18 15:28:51 [-][33][-][profile begin][craft\web\twig\Template::display] __string_template__83e1ab0ea61c4114c0a11e82878d36870c03212f1c613eebae1aed910db499d4
2019-02-18 15:28:51 [-][33][-][profile end][craft\web\twig\Template::display] __string_template__83e1ab0ea61c4114c0a11e82878d36870c03212f1c613eebae1aed910db499d4
2019-02-18 15:28:51 [-][33][-][trace][craft\web\View::renderTemplate] Rendering template: privatenamecore/emails/process-order-failure
2019-02-18 15:28:51 [-][33][-][profile begin][craft\web\View::renderTemplate] privatenamecore/emails/process-order-failure
2019-02-18 15:28:51 [-][33][-][profile begin][craft\web\twig\Environment::compileSource] privatenamecore/emails/process-order-failure
2019-02-18 15:28:51 [-][33][-][profile end][craft\web\twig\Environment::compileSource] privatenamecore/emails/process-order-failure
2019-02-18 15:28:51 [-][33][-][profile begin][craft\web\twig\Template::display] privatenamecore/emails/process-order-failure
2019-02-18 15:28:51 [-][33][-][profile end][craft\web\twig\Template::display] privatenamecore/emails/process-order-failure
2019-02-18 15:28:51 [-][33][-][profile end][craft\web\View::renderTemplate] privatenamecore/emails/process-order-failure
2019-02-18 15:28:51 [-][33][-][info][yii\mail\BaseMailer::send] Sending email "CED-Groep website API bestelling verwerk fout" to "tim@pixeldeluxe.nl"
2019-02-18 15:28:51 [-][33][-][info][yii\swiftmailer\Mailer::sendMessage] Sending email "CED-Groep website API bestelling verwerk fout" to "tim@pixeldeluxe.nl"
2019-02-18 15:28:51 [-][33][-][error][yii\base\ErrorException:2] yii\base\ErrorException: session_start(): Cannot send session cookie - headers already sent by (output started at /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/web/Response.php:185) in /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/web/Session.php:137
Stack trace:
#0 /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(2, 'session_start()...', '/Applications/M...', 137)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'session_start()...', '/Applications/M...', 137, Array)
#2 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/web/Session.php(137): session_start()
#3 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/web/Session.php(895): yii\web\Session->open()
#4 /Applications/MAMP/htdocs/privatename/vendor/craftcms/commerce/src/services/Carts.php(187): yii\web\Session->offsetGet('commerce_cart')
#5 /Applications/MAMP/htdocs/privatename/vendor/craftcms/commerce/src/services/Carts.php(56): craft\commerce\services\Carts->getSessionCartNumber()
#6 /Applications/MAMP/htdocs/privatename/plugins/privatenamecore/src/services/CartValidation.php(39): craft\commerce\services\Carts->getCart()
#7 [internal function]: pixeldeluxe\privatenamecore\services\CartValidation->__construct()
#8 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/di/Container.php(375): ReflectionClass->newInstanceArgs(Array)
#9 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('pixeldeluxe\\ced...', Array, Array)
#10 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container->get('pixeldeluxe\\ced...', Array)
#11 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject('pixeldeluxe\\ced...')
#12 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/base/Module.php(745): yii\di\ServiceLocator->get('cartValidation', false)
#13 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/di/ServiceLocator.php(74): yii\base\Module->get('cartValidation')
#14 /Applications/MAMP/htdocs/privatename/plugins/privatenamecore/src/events/listeners/webshop/LineItemInitListener.php(21): yii\di\ServiceLocator->__get('cartValidation')
#15 /Applications/MAMP/htdocs/privatename/vendor/pixeldeluxe/siteutils/src/events/EventListener.php(20): pixeldeluxe\privatenamecore\events\listeners\webshop\LineItemInitListener->onEvent(Object(yii\base\Event))
#16 [internal function]: pixeldeluxe\siteutils\events\EventListener::pixeldeluxe\siteutils\events\{closure}(Object(yii\base\Event))
#17 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Object(Closure), Object(yii\base\Event))
#18 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\commerce\\...', 'init', Object(yii\base\Event))
#19 /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/base/Model.php(68): yii\base\Component->trigger('init')
#20 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\base\Model->init()
#21 /Applications/MAMP/htdocs/privatename/vendor/craftcms/commerce/src/services/LineItems.php(103): yii\base\BaseObject->__construct(Array)
#22 /Applications/MAMP/htdocs/privatename/plugins/privatenamecore/src/jobs/ProcessOrderTask.php(107): craft\commerce\services\LineItems->getAllLineItemsByOrderId(2715)
#23 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2-queue/src/Queue.php(214): pixeldeluxe\privatenamecore\jobs\ProcessOrderTask->execute(Object(craft\queue\Queue))
#24 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage('52', 'O:46:"pixeldelu...', '300', 1)
#25 /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/queue/Queue.php(96): yii\queue\cli\Queue->handleMessage('52', 'O:46:"pixeldelu...', '300', 1)
#26 /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/controllers/QueueController.php(86): craft\queue\Queue->run()
#27 [internal function]: craft\controllers\QueueController->actionRun()
#28 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#29 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#30 /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('run', Array)
#31 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('run', Array)
#32 /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('queue/run', Array)
#33 /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('queue/run', Array)
#34 /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#35 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#36 /Applications/MAMP/htdocs/privatename/public_html/index.php(21): yii\base\Application->run()
#37 {main}
2019-02-18 15:28:51 [-][33][-][info][yii\db\Command::execute] UPDATE `queue` SET `fail`=1, `dateFailed`='2019-02-18 14:28:51', `error`='session_start(): Cannot send session cookie - headers already sent by (output started at /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/web/Response.php:185)' WHERE `id`='52'
2019-02-18 15:28:51 [-][33][-][profile begin][yii\db\Command::execute] UPDATE `queue` SET `fail`=1, `dateFailed`='2019-02-18 14:28:51', `error`='session_start(): Cannot send session cookie - headers already sent by (output started at /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/web/Response.php:185)' WHERE `id`='52'
2019-02-18 15:28:51 [-][33][-][profile end][yii\db\Command::execute] UPDATE `queue` SET `fail`=1, `dateFailed`='2019-02-18 14:28:51', `error`='session_start(): Cannot send session cookie - headers already sent by (output started at /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/web/Response.php:185)' WHERE `id`='52'
2019-02-18 15:28:51 [-][33][-][info][yii\db\Command::execute] UPDATE `queue` SET `dateReserved`=NULL, `timeUpdated`=NULL, `progress`=0 WHERE `timeUpdated` < 1550500131 - `ttr`
2019-02-18 15:28:51 [-][33][-][profile begin][yii\db\Command::execute] UPDATE `queue` SET `dateReserved`=NULL, `timeUpdated`=NULL, `progress`=0 WHERE `timeUpdated` < 1550500131 - `ttr`
2019-02-18 15:28:51 [-][33][-][profile end][yii\db\Command::execute] UPDATE `queue` SET `dateReserved`=NULL, `timeUpdated`=NULL, `progress`=0 WHERE `timeUpdated` < 1550500131 - `ttr`
2019-02-18 15:28:51 [-][33][-][info][yii\db\Command::query] SELECT *
FROM `queue`
WHERE ((`fail`=FALSE) AND (`timeUpdated` IS NULL)) AND (`timePushed` <= 1550500131 - `delay`)
ORDER BY `priority`, `id`
LIMIT 1
2019-02-18 15:28:51 [-][33][-][profile begin][yii\db\Command::query] SELECT *
FROM `queue`
WHERE ((`fail`=FALSE) AND (`timeUpdated` IS NULL)) AND (`timePushed` <= 1550500131 - `delay`)
ORDER BY `priority`, `id`
LIMIT 1
2019-02-18 15:28:51 [-][33][-][profile end][yii\db\Command::query] SELECT *
FROM `queue`
WHERE ((`fail`=FALSE) AND (`timeUpdated` IS NULL)) AND (`timePushed` <= 1550500131 - `delay`)
ORDER BY `priority`, `id`
LIMIT 1
```

Changing my version to dev-develop right now...

**Comment by tim-pixeldeluxe** [comment]
I just found the actual problem. My plugin was listening to the ListItem init event to validate it.
