### ISSUE TITLE
hasSales() is always giving me an Invalid product ID error message

### ISSUE THREAD

**Issue by echantigny** [craftcms/commerce#732]
### Description

I'm trying to create a product on sale listing and I'm facing an error all the time.

For now, I only have 1 product on sale.

This call works and gives me all the variants, no errors
`{% set saleVariants = craft.variants.all() %}`

These call gives me an Invalid product ID error message
`{% set saleVariants = craft.variants.hasSales(true).all() %}`
`{% set products = craft.products.hasVariant({hasSales: true}).all() %}`

I am also using the onSale property on the full product listings and product details page and that works fine.

### Additional info

- Craft version: Craft Pro 3.1.12
- PHP version: 7.2.8
- Database driver & version: MySQL 5.7.22
- Plugins & versions:
Craft Commerce 2.0.4

**Comment by Sam-Black-0013** [comment]
Me too. I am getting the same issue.

**Comment by echantigny** [comment]
Here is the stack trace:

```
yii\base\InvalidConfigException: Invalid product ID: 7263 in /usr/home/germangames/greatboardgames.ca/vendor/craftcms/commerce/src/elements/Variant.php:314
Stack trace:
#0 /usr/home/germangames/greatboardgames.ca/vendor/craftcms/commerce/src/elements/Variant.php(723): craft\commerce\elements\Variant->getProduct()
#1 /usr/home/germangames/greatboardgames.ca/vendor/craftcms/commerce/src/services/Sales.php(322): craft\commerce\elements\Variant->getIsPromotable()
#2 /usr/home/germangames/greatboardgames.ca/vendor/craftcms/commerce/src/services/Sales.php(212): craft\commerce\services\Sales->matchPurchasableAndSale(Object(craft\commerce\elements\Variant), Object(craft\commerce\models\Sale), NULL)
#3 /usr/home/germangames/greatboardgames.ca/vendor/craftcms/commerce/src/elements/db/VariantQuery.php(425): craft\commerce\services\Sales->getSalesForPurchasable(Object(craft\commerce\elements\Variant))
#4 /usr/home/germangames/greatboardgames.ca/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1050): craft\commerce\elements\db\VariantQuery->beforePrepare()
#5 /usr/home/germangames/greatboardgames.ca/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#6 /usr/home/germangames/greatboardgames.ca/vendor/yiisoft/yii2/db/Query.php(146): yii\db\QueryBuilder->build(Object(craft\commerce\elements\db\VariantQuery))
#7 /usr/home/germangames/greatboardgames.ca/vendor/yiisoft/yii2/db/Query.php(307): yii\db\Query->createCommand(Object(craft\db\Connection))
#8 /usr/home/germangames/greatboardgames.ca/vendor/craftcms/cms/src/db/Query.php(211): yii\db\Query->column(NULL)
#9 /usr/home/germangames/greatboardgames.ca/vendor/craftcms/commerce/src/elements/db/ProductQuery.php(673): craft\db\Query->column()
#10 /usr/home/germangames/greatboardgames.ca/vendor/craftcms/commerce/src/elements/db/ProductQuery.php(579): craft\commerce\elements\db\ProductQuery->_applyHasVariantParam()
#11 /usr/home/germangames/greatboardgames.ca/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1050): craft\commerce\elements\db\ProductQuery->beforePrepare()
#12 /usr/home/germangames/greatboardgames.ca/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#13 /usr/home/germangames/greatboardgames.ca/vendor/yiisoft/yii2/db/Query.php(146): yii\db\QueryBuilder->build(Object(craft\commerce\elements\db\ProductQuery))
#14 /usr/home/germangames/greatboardgames.ca/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Query->createCommand(Object(craft\db\Connection))
#15 /usr/home/germangames/greatboardgames.ca/vendor/craftcms/cms/src/db/Query.php(161): yii\db\Query->all(NULL)
#16 /usr/home/germangames/greatboardgames.ca/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1200): craft\db\Query->all(NULL)
#17 /usr/home/germangames/greatboardgames.ca/vendor/twig/twig/lib/Twig/Extension/Core.php(1626): craft\elements\db\ElementQuery->all()
#18 /usr/home/germangames/greatboardgames.ca/vendor/craftcms/cms/src/helpers/Template.php(73): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\commerce\elements\db\ProductQuery), 'all', Array, 'method', false, false)
#19 /usr/home/germangames/greatboardgames.ca/storage/runtime/compiled_templates/48/48ebb9ebb13dd0d05660d12187f929aee731d6868c8a4c5c6e37f4929cbfb08c.php(28): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\commerce\elements\db\ProductQuery), 'all', Array, 'method')
#20 /usr/home/germangames/greatboardgames.ca/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_3a453b24afd60d606ce7176d38e00f34fa990dd0e98291c57708c5e9631afafa->doDisplay(Array, Array)
#21 /usr/home/germangames/greatboardgames.ca/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#22 /usr/home/germangames/greatboardgames.ca/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#23 /usr/home/germangames/greatboardgames.ca/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#24 /usr/home/germangames/greatboardgames.ca/vendor/twig/twig/lib/Twig/Template.php(371): craft\web\twig\Template->display(Array)
#25 /usr/home/germangames/greatboardgames.ca/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#26 /usr/home/germangames/greatboardgames.ca/vendor/craftcms/cms/src/web/View.php(337): Twig_Environment->render('games/on-sale', Array)
#27 /usr/home/germangames/greatboardgames.ca/vendor/craftcms/cms/src/web/View.php(384): craft\web\View->renderTemplate('games/on-sale', Array)
#28 /usr/home/germangames/greatboardgames.ca/vendor/craftcms/cms/src/web/Controller.php(161): craft\web\View->renderPageTemplate('games/on-sale', Array)
#29 /usr/home/germangames/greatboardgames.ca/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('games/on-sale', Array)
#30 [internal function]: craft\controllers\TemplatesController->actionRender('games/on-sale', Array)
#31 /usr/home/germangames/greatboardgames.ca/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#32 /usr/home/germangames/greatboardgames.ca/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#33 /usr/home/germangames/greatboardgames.ca/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('render', Array)
#34 /usr/home/germangames/greatboardgames.ca/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#35 /usr/home/germangames/greatboardgames.ca/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('templates/rende...', Array)
#36 /usr/home/germangames/greatboardgames.ca/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#37 /usr/home/germangames/greatboardgames.ca/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#38 /usr/home/germangames/greatboardgames.ca/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#39 /usr/home/germangames/greatboardgames.ca/public_html/index.php(21): yii\base\Application->run()
#40 {main}
```

**Comment by lukeholder** [comment]
This should be fixed on the develop branch. If you update commerce in your composer.json to `dev-develop` as the version, and do a `composer update` on your project, you will get the latest develop branch code.

Let me know if that fixes error, if not, I will reopen the issue and look into it.

Thanks.

**Comment by echantigny** [comment]
@lukeholder I'm trying to test this locally, but I'm always getting a "ERR_CONNECTION_RESET".  
Memory at 1G
Execution Time at 3000

**Comment by echantigny** [comment]
@lukeholder After pushing the code to my staging server, and testing, I don't get anything at all now with either of these.  No errors and an empty array.

`{% set saleVariants = craft.variants.hasSales(true).all() %}`
`{% set products = craft.products.hasVariant({hasSales: true}).all() %}`

**Comment by lukeholder** [comment]
No errors is good. 

I just created a sale and used both of those queries:

```
{% set saleVariants = craft.variants.hasSales(true).all() %}

{% for variant in saleVariants %}
Sale: {{ variant.id}}<br>
{% endfor %}

{% set productsX = craft.products.hasVariant({hasSales: true}).all() %}
<br>
<br>
{% for variant in productsX %}
Sale: {{ variant.id}}<br>
{% endfor %}

```
Which is outputting:

```
Sale: 5
Sale: 11
Sale: 9
Sale: 7


Sale: 8
Sale: 4
Sale: 10
Sale: 6
```

**Comment by echantigny** [comment]
@lukeholder Well, I have a single On Sale item, which displays as such on my listing and product detail when I use the `if variant.onSale` property.  So, it means that this variant is setup correctly as such.

Why would that query return no variants/products at all then?

**Comment by lukeholder** [comment]
Is the product marked a promotable in the product edit screen?

If `.onSale` is returning true, can you loop over `variant.sales` and output the name of the sale?

**Comment by echantigny** [comment]
![2019-02-19 11_50_03-shadows of brimstone_ black fang - great boardgames](https://user-images.githubusercontent.com/4933333/53032276-8c6ac380-343c-11e9-9255-0ab31960dc50.png)

**Comment by echantigny** [comment]
Also, in my front end template
![2019-02-19 11_51_56-shadows of brimstone_ black fang great boardgames](https://user-images.githubusercontent.com/4933333/53032416-cdfb6e80-343c-11e9-8fa1-b447b2ad222a.png)

**Comment by echantigny** [comment]
@lukeholder I think the issue might be somewhere else...  It's like that variant is disabled, which is not right, of course.  You can see both the backend and front-end of that.

![2019-02-19 11_56_45-boxing day sale - great boardgames](https://user-images.githubusercontent.com/4933333/53032790-8d502500-343d-11e9-9bdd-974be78e0252.png)
