### ISSUE TITLE
Redactor Config error of unknown cause after importing team-mate's DB

### ISSUE THREAD

**Issue by JayBox325** [craftcms/commerce#770]
### Description
I am getting this error after importing a database supplied from my colleague. I have deleted the vendors directory and composer lock file in an attempt to re-install Redactor. I have also updated all plugins.

The only result when I search for this error code is this ticket: https://github.com/craftcms/commerce/issues/134

But it doesn't look relevant to what's happening with mine. What can I supply that could potentially help resolve this?

```
yii\base\UnknownPropertyException: Setting unknown property: craft\redactor\Field::configFile in /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\Component->__set('configFile', '')
#1 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\redactor\Field), Array)
#2 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/craftcms/redactor/src/Field.php(111): yii\base\BaseObject->__construct(Array)
#3 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/craftcms/cms/src/helpers/Component.php(80): craft\redactor\Field->__construct(Array)
#4 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/craftcms/cms/src/services/Fields.php(548): craft\helpers\Component::createComponent(Array, 'craft\\base\\Fiel...')
#5 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/craftcms/cms/src/services/Fields.php(573): craft\services\Fields->createField(Array)
#6 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1536): craft\services\Fields->getAllFields()
#7 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1073): craft\elements\db\ElementQuery->customFields()
#8 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#9 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/yiisoft/yii2/db/Query.php(146): yii\db\QueryBuilder->build(Object(craft\elements\db\EntryQuery))
#10 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Query->createCommand(Object(craft\db\Connection))
#11 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/craftcms/cms/src/db/Query.php(177): yii\db\Query->one(NULL)
#12 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1215): craft\db\Query->one(NULL)
#13 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/craftcms/cms/src/services/Elements.php(215): craft\elements\db\ElementQuery->one()
#14 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/craftcms/cms/src/services/Elements.php(272): craft\services\Elements->getElementById(2, 'craft\\elements\\...', 1)
#15 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(763): craft\services\Elements->getElementByUri('__home__', 1, false)
#16 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/nystudio107/craft-seomatic/src/services/MetaContainers.php(140): nystudio107\seomatic\services\MetaContainers->setMatchedElement('', '1')
#17 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/nystudio107/craft-seomatic/src/twigextensions/SeomaticTwigExtension.php(47): nystudio107\seomatic\services\MetaContainers->loadMetaContainers('', NULL)
#18 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/twig/twig/lib/Twig/ExtensionSet.php(339): nystudio107\seomatic\twigextensions\SeomaticTwigExtension->getGlobals()
#19 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/twig/twig/lib/Twig/Environment.php(903): Twig_ExtensionSet->getGlobals()
#20 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/twig/twig/lib/Twig/Environment.php(923): Twig_Environment->getGlobals()
#21 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/twig/twig/lib/Twig/Template.php(363): Twig_Environment->mergeGlobals(Array)
#22 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#23 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/twig/twig/lib/Twig/Template.php(371): craft\web\twig\Template->display(Array)
#24 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#25 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/craftcms/cms/src/web/View.php(337): Twig_Environment->render('_special/config...', Array)
#26 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/craftcms/cms/src/web/View.php(384): craft\web\View->renderTemplate('_special/config...', Array)
#27 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/craftcms/cms/src/web/Controller.php(161): craft\web\View->renderPageTemplate('_special/config...', Array)
#28 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/craftcms/cms/src/controllers/TemplatesController.php(115): craft\web\Controller->renderTemplate('_special/config...')
#29 [internal function]: craft\controllers\TemplatesController->actionConfigSyncKickoff()
#30 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#31 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#32 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('config-sync-kic...', Array)
#33 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('config-sync-kic...', Array)
#34 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('templates/confi...', Array)
#35 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/craftcms/cms/src/web/Application.php(709): craft\web\Application->runAction('templates/confi...')
#36 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/craftcms/cms/src/web/Application.php(248): craft\web\Application->_processConfigSyncLogic(Object(craft\web\Request))
#37 /Users/jaycollett/Development/dng/cmh-craft3/build/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#38 /Users/jaycollett/Development/dng/cmh-craft3/build/public/index.php(21): yii\base\Application->run()
#39 {main}
```

### Additional info

- Craft version: 3.1.15
- PHP version: 7.1.22
- Database driver & version: MySQL 5.7.23

**Comment by JayBox325** [comment]
Not commerce. Closing
