### ISSUE TITLE
Trying to get property 'fullName' of non-object on install

### ISSUE THREAD

**Issue by stianmandarin** [craftcms/commerce#807]
### Description

```
yii\base\ErrorException: Trying to get property 'fullName' of non-object

Migration: craft\commerce\migrations\m190301_161406_unique_sku_constraint_in_app

Output:

Exception: Trying to get property 'fullName' of non-object (/Users/username/dev/site.com/vendor/yiisoft/yii2/db/mysql/Schema.php:353)
#0 /Users/username/dev/site.com/vendor/craftcms/cms/src/web/ErrorHandler.php(81): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/Users/username/de...', 353)
#1 /Users/username/dev/site.com/vendor/yiisoft/yii2/db/mysql/Schema.php(353): craft\web\ErrorHandler->handleError(8, 'Trying to get p...', '/Users/username/de...', 353, Array)
#2 /Users/username/dev/site.com/vendor/craftcms/cms/src/db/mysql/Schema.php(216): yii\db\mysql\Schema->getCreateTableSql(NULL)
#3 /Users/username/dev/site.com/vendor/craftcms/cms/src/helpers/MigrationHelper.php(749): craft\db\mysql\Schema->findIndexes('commerce_purcha...')
#4 /Users/username/dev/site.com/vendor/craftcms/cms/src/helpers/MigrationHelper.php(112): craft\helpers\MigrationHelper::_findIndex('{{%commerce_pur...', Array, true, Object(craft\db\Connection))
#5 /Users/username/dev/site.com/vendor/craftcms/commerce/src/migrations/m190301_161406_unique_sku_constraint_in_app.php(18): craft\helpers\MigrationHelper::dropIndexIfExists('{{%commerce_pur...', Array, true, Object(craft\commerce\migrations\m190301_161406_unique_sku_constraint_in_app))
#6 /Users/username/dev/site.com/vendor/craftcms/cms/src/db/Migration.php(56): craft\commerce\migrations\m190301_161406_unique_sku_constraint_in_app->safeUp()
#7 /Users/username/dev/site.com/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#8 /Users/username/dev/site.com/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(craft\commerce\migrations\m190301_161406_unique_sku_constraint_in_app))
#9 /Users/username/dev/site.com/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#10 /Users/username/dev/site.com/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(521): craft\services\Updates->runMigrations(Array)
#11 /Users/username/dev/site.com/vendor/craftcms/cms/src/controllers/UpdaterController.php(209): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#12 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#13 /Users/username/dev/site.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /Users/username/dev/site.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /Users/username/dev/site.com/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('migrate', Array)
#16 /Users/username/dev/site.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#17 /Users/username/dev/site.com/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('updater/migrate', Array)
#18 /Users/username/dev/site.com/vendor/craftcms/cms/src/web/Application.php(683): craft\web\Application->runAction('updater/migrate')
#19 /Users/username/dev/site.com/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#20 /Users/username/dev/site.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 /Users/username/dev/site.com/web/index.php(21): yii\base\Application->run()
#22 {main}
```

### Steps to reproduce

1. Install with composer
2. Navigate to cp which tells me that changes to db are needed, continue with that, which results in error above

### Additional info

- Craft version: 3.1.20.1
- PHP version: 7.3.1
- Database driver & version: MySQL 5.7.25
- Plugins & versions: Commerce 2.1.2

**Comment by lukeholder** [comment]
I can't reproduce this when upgrading. Not sure where any reference to `fullName` in within that migration either. What version are you upgrading from?

**Comment by stianmandarin** [comment]
I'm not updating, which makes it even weirder. Commerce hasn't been installed previously.

Tried deleting my vendor directory, but got the same problem.

Tried deleting it again, this time along with removing all other plugins from composer, but still getting the same problem

**Comment by lukeholder** [comment]
Can you send your original DB and Logs to support@craftcms.com thanks @stianmandarin

**Comment by stianmandarin** [comment]
Just wanna make sure you got my db and logs @lukeholder Any progress on this? Thanks!

**Comment by lukehmu** [comment]
Did you ever solve this @stianmandarin ?

**Comment by lukeholder** [comment]
I was unable to reproduce. @lukehmu are you trying to upgrade or install commerce into a fresh install?

**Comment by stianmandarin** [comment]
@lukehmu @lukeholder Hey, thanks for checking in. Never solved it, but it was abandoned by the client, so it is no longer really an issue.

**Comment by lukeholder** [comment]
@lukehmu is this an issue for you on a new install?

**Comment by lukeholder** [comment]
Will re-open if this can be reproduced.
