### ISSUE TITLE
Session error when code executes from job

### ISSUE THREAD

**Issue by tim-pixeldeluxe** [craftcms/commerce#812]
### Description
So I created a bug report about this a while back but ended up using a work around. Today I ran into the same issue again and found the actual cause. When ever I try to save an order from inside a job I get the following error:
```php
session_start(): Cannot send session cookie - headers already sent by (output started at /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/web/Response.php:185)
```

This error is caused by the getCustomer() function from the Customer service which is called somewhere during execution. The getCustomer() function tries to start a session in order to set a session variable. Starting a session causes the error above.

### Steps to reproduce
1. Use the getCustomer() function from the Customer service from inside a job.
2. Error

### Additional info
- Craft version: 3.1.20.1
- PHP version: 7.1.6
- Database driver & version: MySQL 5.5.59
- Plugins & versions: Craft Commerce Pro 2.1.2

### Stacktrace
```php
2019-04-03 12:46:23 [-][33][-][error][yii\base\ErrorException:2] yii\base\ErrorException: session_start(): Cannot send session cookie - headers already sent by (output started at /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/web/Response.php:185) in /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/web/Session.php:137
Stack trace:
#0 /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/web/ErrorHandler.php(81): yii\base\ErrorHandler->handleError(2, 'session_start()...', '/Applications/M...', 137)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'session_start()...', '/Applications/M...', 137, Array)
#2 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/web/Session.php(137): session_start()
#3 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/web/Session.php(624): yii\web\Session->open()
#4 /Applications/MAMP/htdocs/privatename/vendor/craftcms/commerce/src/services/Customers.php(105): yii\web\Session->set('commerce_custom...', '2')
#5 /Applications/MAMP/htdocs/privatename/vendor/craftcms/commerce/src/services/Customers.php(504): craft\commerce\services\Customers->getCustomer()
#6 /Applications/MAMP/htdocs/privatename/vendor/craftcms/commerce/src/services/Customers.php(468): craft\commerce\services\Customers->_getSavedCustomer()
#7 /Applications/MAMP/htdocs/privatename/vendor/craftcms/commerce/src/services/OrderHistories.php(101): craft\commerce\services\Customers->getCustomerId()
#8 /Applications/MAMP/htdocs/privatename/vendor/craftcms/commerce/src/elements/Order.php(966): craft\commerce\services\OrderHistories->createOrderHistoryFromOrder(Object(craft\commerce\elements\Order), 1)
#9 /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/services/Elements.php(515): craft\commerce\elements\Order->afterSave(false)
#10 /Applications/MAMP/htdocs/privatename/plugins/privatenamecore/src/helpers/OrderHelper.php(65): craft\services\Elements->saveElement(Object(craft\commerce\elements\Order))
#11 /Applications/MAMP/htdocs/privatename/plugins/privatenamecore/src/jobs/ProcessOrderTask.php(28): pixeldeluxe\privatenamecore\helpers\OrderHelper::setStatus(Object(craft\commerce\elements\Order), Object(craft\commerce\models\OrderStatus))
#12 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2-queue/src/Queue.php(214): pixeldeluxe\privatenamecore\jobs\ProcessOrderTask->execute(Object(craft\queue\Queue))
#13 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage('31', 'O:46:"pixeldelu...', '300', 1)
#14 /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/queue/Queue.php(96): yii\queue\cli\Queue->handleMessage('31', 'O:46:"pixeldelu...', '300', 1)
#15 /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/controllers/QueueController.php(86): craft\queue\Queue->run()
#16 [internal function]: craft\controllers\QueueController->actionRun()
#17 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#19 /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('run', Array)
#20 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('run', Array)
#21 /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('queue/run', Array)
#22 /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('queue/run', Array)
#23 /Applications/MAMP/htdocs/privatename/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#24 /Applications/MAMP/htdocs/privatename/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#25 /Applications/MAMP/htdocs/privatename/public_html/index.php(21): yii\base\Application->run()
#26 {main}
```

**Comment by lukeholder** [comment]
Could you share the code you are using in the Job? If you are only dealing with order elements directly, you shouldn't need to call `Customers::getCustomer()`. Will reopen once I see what you are doing. It is the correct behaviour to need a session when calling `Customers::getCustomer()`. Also shouldn't be using the Carts service.

**Comment by tim-pixeldeluxe** [comment]
Old code (that causes the error):
```php
/**
 * Sets this orders status. The status can either be an id or handle.
 *
 * @param string|int $status
 * @param string $message
 * @throws Exception
 * @return bool
 */
public function setStatus($status, string $message = null) : bool {
    return true; // Remove once Craft Commerce bug is fixed
    // Find status
    if(is_int($status)) {
        $status = CraftCommerce::getInstance()->orderStatuses->getOrderStatusById($status);
    } else {
        $status = CraftCommerce::getInstance()->orderStatuses->getOrderStatusByHandle($status);
    }

    // Validate status
    if($status) {
        $orderStatusId = $status->id;
    } else {
        throw new Exception('Invalid order status');
    }

    // Set status
    $this->owner->orderStatusId = $orderStatusId;

    // Set message if specified
    if($message) {
        $this->owner->message = $message;
    }

    // Save order
    return Craft::$app->getElements()->saveElement($this->owner);
}
```

My current code:
```php
/**
 * Sets this orders status. The status can either be an id or handle.
 *
 * @param string|int $status
 * @param string $message
 * @throws Exception
 * @return bool
 */
public function setStatus(int $statusId, string $message = null) {
    $order = $this->owner;
    $status = CraftCommerce::getInstance()->orderStatuses->getOrderStatusById($statusId);
    $oldStatusId = $order->orderStatusId;

    // Validate status
    if($status === null) {
        throw new OrderStatusException('Invalid order status id');
    }

    // Update order status
    Craft::$app->getDb()->createCommand()->update('{{%commerce_orders}}',
        ['orderStatusId' => $statusId],
        ['id' => $order->getId()]
    )->execute();

    // Create order history
    $orderHistoryModel = new OrderHistory();
    $orderHistoryModel->orderId = $order->id;
    $orderHistoryModel->prevStatusId = $oldStatusId;
    $orderHistoryModel->newStatusId = $statusId;
    $orderHistoryModel->customerId = $order->customerId;
    $orderHistoryModel->message = $message;

    CraftCommerce::getInstance()->getOrderHistories()->saveOrderHistory($orderHistoryModel);
}
```

**Comment by RoussKS** [comment]
Hi, we have the same issue when attempting to save the order through the element service.
We believe this should be an open issue/bug

On an event, we dispatch a job to refund transactions and then change the order status on the order.
The issue comes up from line 1059 of `src/elements/Order.php` which calls `createOrderHistoryFromOrder` in `src/services/OrderHistories.php` and subsequently this calls line 102 where this is executed `$orderHistoryModel->customerId = Craft::$app->request->isConsoleRequest ? $order->customerId : Plugin::getInstance()->getCustomers()->getCustomerId();` which breaks with the same session headers already set error.

We'll use the the above fix, but it feels we shouldn't need to do a database transaction for this, but just use the available methods from the services themselves.


`    public function refundPurchasedTicket(PurchasedTicket $purchasedTicket): bool
    {
        $order = $this->getCommercePlugin()->orders->getOrderById($purchasedTicket->orderId);

        if ($order === null) {
            throw new OrderNotFoundException('There is no order ID: ' . $purchasedTicket->orderId);
        }

        // Our current handler should only include 1 transaction, but we loop them all to cover future requirements.
        // Allow for exceptions, if the queue fails due to one, what's remaining is going to be executed on the next one.
        foreach ($order->transactions as $transaction) {
            // Do not refund not-refundable transactions.
            if (!$transaction->canRefund()) {
                continue;
            }

            $refundTransaction = $this->getCommercePlugin()->payments->refundTransaction($transaction);

            // If something failed the refund transaction status is set to failed according the method called.
            if ($refundTransaction->status === Transaction::STATUS_FAILED) {
                throw new PurchasedTicketRefundException(
                    'Failed to refund Transaction ID: ' . $transaction->id . ' using Refund Transaction ID: ' . $refundTransaction->id . ' with error message: ' . $refundTransaction->message
                );
            }
        }

        // If we reached this point,
        // all transactions have been successfully refunded
        // and we can set the order status to the custom status 'refunded' (handle).
        $orderStatus = $this->getCommercePlugin()->orderStatuses->getOrderStatusByHandle('refunded');

        if ($orderStatus === null) {
            throw new OrderStatusException('OrderStatus with handle refunded does not exist.');
        }

        $order->orderStatusId = $orderStatus->id;
        $order->message = 'Order refunded due to event cancellation';

        return Craft::$app->elements->saveElement($order);
    }`

PHP: 7.2.21
Craft Commerce: 2.2.11

**Comment by lenvanessen** [comment]
We have this issues as well, same problem as @tim-pixeldeluxe and we have to use the direct db statement in order to make it work. Which also requires us to manually set the order status..

**Comment by lenvanessen** [comment]
@lukeholder can you please revisit this issue. I think @RoussKS is right on the money in terms of what the cause of the issue is.

```
<?php
/**
 * afas-order-bundle plugin for Craft CMS 3.x
 *
 * Handles order exports and status updates
 *
 * @link      wirelab.nl
 * @copyright Copyright (c) 2018 Len van Essen
 */

namespace wirelab\afasorderbundle\jobs;

use craft\commerce\elements\Order;
use craft\commerce\Plugin;

use Craft;
use craft\queue\BaseJob;
use wirelab\afasmainbundle\AfasMainBundle;
use GuzzleHttp\Client;

/**
 * Class OrderStatus
 *
 * @package wirelab\afasorderbundle\jobs
 */
class OrderStatus extends BaseJob
{
    CONST ORDER_STATUS_CONNECTOR = 'NEITA_Webshop_Orderstatus/Ordernumber';

    public $order;

    public $shippedOrderStatus;

    /**
     * When the Queue is ready to run your job, it will call this method.
     * You don't need any steps or any other special logic handling, just do the
     * jobs that needs to be done here.
     *
     * More info: https://github.com/yiisoft/yii2-queue
     */
    public function execute($queue = null)
    {
        $result = false;
        $url = AfasMainBundle::$plugin
            ->profitServiceUrl(self::ORDER_STATUS_CONNECTOR."/{$this->order->afas_id}");

        $this->shippedOrderStatus = Plugin::getInstance()
            ->getOrderStatuses()
            ->getOrderStatusByHandle('shipped');

        // Get the items from client
        $client = new Client();

        $res = $client->request('GET', $url, [
            'headers' => [
                'Authorization' => 'AfasToken ' . base64_encode(AfasMainBundle::$plugin->getInstance()->getSettings()->apiToken),
                'Accept' => 'application/json'
            ],
        ]);

        if($res->getStatusCode() === 200) {
            $body = json_decode($res->getBody()->getContents(), true);

            if(isset($body['rows'][0])) {
                $shipment = $body['rows'][0];

                if($shipment['PackinglistReadyOn']) {
                    $this->order->orderStatusId = $this->shippedOrderStatus->id;
                    $this->order->setFieldValue('trackandtrace', $shipment['TrackTrace']);

                    $result = Craft::$app->getElements()->saveElement($this->order, false);
                }
            }
        }

        return $result;
    }

    /**
     * Returns a default description for [[getDescription()]], if [[description]] isn’t set.
     *
     * @return string The default task description
     */
    protected function defaultDescription(): string
    {
        return Craft::t('afas-order-bundle', 'OrderStatus');
    }
}
```

**Comment by lenvanessen** [comment]
@nfourtythree perhaps you can revisit this issue for us? It's kind of a mess to work around this issue, and the fix seems quite simple to do in the core.

**Comment by lukeholder** [comment]
@lenvanessen @RoussKS We updated this in September 2020 to the following:

https://github.com/craftcms/commerce/blob/develop/src/services/OrderHistories.php#L115-L117

This should better account for the change happening with no session (inside a job)
