### ISSUE TITLE
Error: Call to a member function getFullName() on null

### ISSUE THREAD

**Issue by johnnyhawley** [craftcms/commerce#898]
### Description
When viewing orders in commerce where Billing Full Name is in the table view, an error occurs when an order does not have billing information.

```
2019-06-10 09:30:47 [-][1][-][error][Error] Error: Call to a member function getFullName() on null in /home/vagrant/web/demoshop/vendor/craftcms/commerce/src/elements/Order.php:1735
Stack trace:
#0 /home/vagrant/web/demoshop/vendor/craftcms/cms/src/base/Element.php(1816): craft\commerce\elements\Order->tableAttributeHtml('billingFullName')
#1 /home/vagrant/web/demoshop/vendor/twig/twig/src/Extension/CoreExtension.php(1485): craft\base\Element->getTableAttributeHtml('billingFullName')
#2 /home/vagrant/web/demoshop/vendor/craftcms/cms/src/helpers/Template.php(79): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\commerce\elements\Order), 'getTableAttribu...', Array, 'method', false, false)
#3 /home/vagrant/web/demoshop/storage/runtime/compiled_templates/3e/3e829c3a563e51aaacf70dfd18e3462346e5baa41308d4639c442ef6c0ff880a.php(156): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\commerce\elements\Order), 'getTableAttribu...', Array, 'method')
#4 /home/vagrant/web/demoshop/vendor/twig/twig/src/Template.php(395): __TwigTemplate_6d2c9ef53153f4a0fa4434f38c4ffb684d95591568333f416c144dcd4a186307->doDisplay(Array, Array)
#5 /home/vagrant/web/demoshop/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#6 /home/vagrant/web/demoshop/vendor/twig/twig/src/Template.php(372): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#7 /home/vagrant/web/demoshop/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#8 /home/vagrant/web/demoshop/storage/runtime/compiled_templates/09/0905bba4f1f42140ac006fb80303c76c41f071152d6f003579f01897e193bc72.php(95): craft\web\twig\Template->display(Array)
#9 /home/vagrant/web/demoshop/vendor/twig/twig/src/Template.php(395): __TwigTemplate_f274470f818d34940cc57c54427495b53d71e361f1b154efc5da3cf7ecdfd944->doDisplay(Array, Array)
#10 /home/vagrant/web/demoshop/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /home/vagrant/web/demoshop/vendor/twig/twig/src/Template.php(372): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#12 /home/vagrant/web/demoshop/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#13 /home/vagrant/web/demoshop/vendor/twig/twig/src/Template.php(380): craft\web\twig\Template->display(Array)
#14 /home/vagrant/web/demoshop/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#15 /home/vagrant/web/demoshop/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#16 /home/vagrant/web/demoshop/vendor/craftcms/cms/src/web/View.php(343): Twig\Environment->render('_elements/table...', Array)
#17 /home/vagrant/web/demoshop/vendor/craftcms/cms/src/base/Element.php(450): craft\web\View->renderTemplate('_elements/table...', Array)
#18 /home/vagrant/web/demoshop/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(400): craft\base\Element::indexHtml(Object(craft\commerce\elements\db\OrderQuery), Array, Array, 'orderStatus:new', 'index', true, true)
#19 /home/vagrant/web/demoshop/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(120): craft\controllers\ElementIndexesController->elementResponseData(true, true)
#20 [internal function]: craft\controllers\ElementIndexesController->actionGetElements()
#21 /home/vagrant/web/demoshop/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#22 /home/vagrant/web/demoshop/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#23 /home/vagrant/web/demoshop/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('get-elements', Array)
#24 /home/vagrant/web/demoshop/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('get-elements', Array)
#25 /home/vagrant/web/demoshop/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('element-indexes...', Array)
#26 /home/vagrant/web/demoshop/vendor/craftcms/cms/src/web/Application.php(565): craft\web\Application->runAction('element-indexes...', Array)
#27 /home/vagrant/web/demoshop/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#28 /home/vagrant/web/demoshop/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#29 /home/vagrant/web/demoshop/web/index.php(42): yii\base\Application->run()

```

### Additional info

- Craft version: 3.1.29
- PHP version: 7.2
- Plugins & versions: Commerce 2.1.6.1

**Comment by lukeholder** [comment]
Fixed in 2.1.7 https://github.com/craftcms/commerce/blob/develop/CHANGELOG-v2.md
