### ISSUE TITLE
Craft 2 > Craft 3 Migration Error 

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#932]
Updating from Commerce 1.2.1364 + Craft 2.7.2 to the latest respective versions. Running through the web migration, and the first round of updates (Craft) goes well. Then I get:

```

One of Craft Commerce’s migrations failed.

Database Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
The SQL being executed was: ALTER TABLE craft_commerce_producttypes_i18n CHANGE locale__siteId siteId

Migration: craft\commerce\migrations\m160531_154500_craft3_upgrade

Output:

> update in {{%elements}} ... done (time: 0.112s)
> update in {{%elements}} ... done (time: 0.008s)
> update in {{%elements}} ... done (time: 0.011s)
> update in {{%fields}} ... done (time: 0.002s)
> update in {{%fields}} ... done (time: 0.001s)
> update in {{%widgets}} ... done (time: 0.006s)
> update in {{%widgets}} ... done (time: 0.003s)
> drop column locale from table {{%commerce_producttypes_i18n}} ... done (time: 0.038s)
> rename column locale__siteId in table {{%commerce_producttypes_i18n}} to siteId ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
The SQL being executed was: ALTER TABLE craft_commerce_producttypes_i18n CHANGE locale__siteId siteId (/Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE cr...')
#1 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('ALTER TABLE cr...')
#2 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/db/Migration.php(405): yii\db\Command->execute()
#3 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/helpers/MigrationHelper.php(329): yii\db\Migration->renameColumn('{{%commerce_pro...', 'locale__siteId', 'siteId')
#4 /Users/joshcrawford/public_html/site/vendor/craftcms/commerce/src/migrations/m160531_154500_craft3_upgrade.php(50): craft\helpers\MigrationHelper::renameColumn('{{%commerce_pro...', 'locale__siteId', 'siteId', Object(craft\commerce\migrations\m160531_154500_craft3_upgrade))
#5 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/db/Migration.php(56): craft\commerce\migrations\m160531_154500_craft3_upgrade->safeUp()
#6 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#7 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(craft\commerce\migrations\m160531_154500_craft3_upgrade))
#8 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
#9 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(521): craft\services\Updates->runMigrations(Array)
#10 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/controllers/UpdaterController.php(208): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#11 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#12 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('migrate', Array)
#15 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#16 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/web/Application.php(298): yii\base\Module->runAction('updater/migrate', Array)
#17 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/web/Application.php(652): craft\web\Application->runAction('updater/migrate')
#18 /Users/joshcrawford/public_html/site/vendor/craftcms/cms/src/web/Application.php(250): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#19 /Users/joshcrawford/public_html/site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /Users/joshcrawford/public_html/site/public_html/index.php(30): yii\base\Application->run()
#21 {main}
```

I have included a screenshot of the database table after the initial migration has succeeded, and I have yet to click the "Finish Up" button again - to do plugin migrations.

![Screen Shot 2019-07-17 at 12 07 43 pm](https://user-images.githubusercontent.com/1221575/61341881-94178280-a88b-11e9-84dc-8584f61a476c.png)

Is seems like the native Craft migration to add column `locale__siteId` didn't work. Commerce's migration should be checking for the existence of the `locale__siteId` column before dropping the `locale` column though.

For extra info, I've added the table structure for `commerce_producttypes_i18n` to show indexes (which I believe is how Craft goes through and creates those intermediary columns?

![Screen Shot 2019-07-17 at 12 10 30 pm](https://user-images.githubusercontent.com/1221575/61341978-f6708300-a88b-11e9-8982-54d6d2d417c4.png)

**Comment by engram-design** [comment]
Manually adding a `locale__siteId` column with the populated siteId's is a workaround

**Comment by engram-design** [comment]
Both this issue and https://github.com/craftcms/commerce/issues/933 are due to bad foreign keys. For those following along:

Get a copy of https://github.com/pixelandtonic/craft-fixfks and put it in your Craft 2 site. However, you'll want to create a new fkdump based on your Craft version and plugins installed - namely Commerce, but its worth making sure there aren't any other plugins missing FKs.

You'll need to create a brand new site on a fresh Craft install (see https://craftcms.com/guides/downloading-previous-craft-versions). Get this setup without a db prefix (this is important). Install Craft with any details (it doesn't matter), and copy the plugins folder from the site you're trying to update. Install all plugins. The go through the instructions to create a dump for this site. It doesn't matter about not having your content on this site, is just needs to be the same Craft and plugin versions of the site you're trying to upgrade.

With this dump, copy it to the Craft 2 site you're upgrading and run the report to see issues.
